#!/usr/bin/make

.PHONY: all
all:	yaDSKYb1

yaDSKYb1: yaDSKYb1.cpp yaDSKYb1.h Makefile Block1DSKY-face-P67X.png
	g++ `wx-config --cxxflags` $< `wx-config --libs` -o $@

.PHONY: clean
clean:
	-rm yaDSKYb1 yaDSKYb1-nav

