/*
  File MATCH_SIMPLES.c generated by XCOM-I, 2024-08-08 04:31:11.
*/

#include "runtimeC.h"

int32_t
MATCH_SIMPLES (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "MATCH_SIMPLES");
  // T1=PSEUDO_TYPE(PTR(LOC1)); (7427)
  {
    descriptor_t *bitRHS = getBIT (
        8, mPSEUDO_TYPE
               + 1
                     * COREHALFWORD (
                         mPTR + 2 * COREHALFWORD (mMATCH_SIMPLESxLOC1)));
    putBIT (16, mMATCH_SIMPLESxT1, bitRHS);
    bitRHS->inUse = 0;
  }
  // T2=PSEUDO_TYPE(PTR(LOC2)); (7428)
  {
    descriptor_t *bitRHS = getBIT (
        8, mPSEUDO_TYPE
               + 1
                     * COREHALFWORD (
                         mPTR + 2 * COREHALFWORD (mMATCH_SIMPLESxLOC2)));
    putBIT (16, mMATCH_SIMPLESxT2, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF T1~=T2 THEN (7429)
  if (1
      & (xNEQ (COREHALFWORD (mMATCH_SIMPLESxT1),
               COREHALFWORD (mMATCH_SIMPLESxT2))))
    // DO; (7430)
    {
    rs1:;
      // IF T2=INT_TYPE THEN (7431)
      if (1 & (xEQ (COREHALFWORD (mMATCH_SIMPLESxT2), 6)))
        // LOC1=LOC2; (7432)
        {
          descriptor_t *bitRHS = getBIT (16, mMATCH_SIMPLESxLOC2);
          putBIT (16, mMATCH_SIMPLESxLOC1, bitRHS);
          bitRHS->inUse = 0;
        }
      // CALL HALMAT_TUPLE(XITOS,0,LOC1,0,0); (7433)
      {
        putBITp (16, mHALMAT_TUPLExPOPCODE, getBIT (16, mXITOS));
        putBITp (8, mHALMAT_TUPLExCOPT, fixedToBit (32, (int32_t)(0)));
        putBITp (16, mHALMAT_TUPLExOP1, getBIT (16, mMATCH_SIMPLESxLOC1));
        putBITp (16, mHALMAT_TUPLExOP2, fixedToBit (32, (int32_t)(0)));
        putBITp (8, mHALMAT_TUPLExTAG, fixedToBit (32, (int32_t)(0)));
        HALMAT_TUPLE (0);
      }
      // CALL SETUP_VAC(LOC1,SCALAR_TYPE); (7434)
      {
        putBITp (16, mSETUP_VACxLOC, getBIT (16, mMATCH_SIMPLESxLOC1));
        putBITp (16, mSETUP_VACxTYPE, fixedToBit (32, (int32_t)(5)));
        SETUP_VAC (0);
      }
    es1:;
    } // End of DO block
  {
    reentryGuard = 0;
    return 0;
  }
}
