### FILE="Main.annotation"
## Copyright:	Public domain.
## Filename:	DOWN_TELEMETRY_PROGRAM.agc
## Purpose:	A module for revision 0 of BURST120 (Sunburst). It 
##		is part of the source code for the Lunar Module's
##		(LM) Apollo Guidance Computer (AGC) for Apollo 5.
## Assembler:	yaYUL
## Contact:	Ron Burkey <info@sandroid.org>.
## Website:	www.ibiblio.org/apollo/index.html
## Mod history:	2016-09-30 RSB	Created draft version.

## Page 329
# PROGRAM NAME- DOWN TELEMETRY PROGRAM
# MOD NO.- 0
# MOD BY- KILROY
# DATE- 21NOV66
# LOG SECTION- DOWN-TELEMETRY PROGRAM
# ASSEMBLY- REV 12 OF SUNBURST
# FUNCTIONAL DESCRIPTION- THIS ROUTINE IS INITIATED BY TELEMETRY END
#	   PULSE FROM THE DOWNLINK TELEMETRY CONVERTER. THIS PULSE OCCURS
#	   AT 50 TIMES PER SEC(EVERY 20 MS) THEREFORE DODOWNTM IS
#	   EXECUTED AT THESE RATES. THIS ROUTINE SELECTS THE APPROPRIATE
#	   AGC DATA TO BE TRANSMITTED DOWNLINK AND LOADS IT INTO OUTPUT
#	   CHANNELS 34 AND 35. THE INFORMATION IS THEN GATED OUT FROM THE
#	   LGC IN SERIAL FASHION.
#	   THIS PROGRAM IS CODED FOR A 2 SECOND DOWNLIST. SINCE DOWNRUPTS
#	   OCCUR EVERY 20 MS AND 2 AGC COMPUTER WORDS CAN BE PLACED IN
#	   CHANNELS 34 AND 35 DURING EACH DOWNRUPT THE PROGRAM IS CAPABLE
# 	   OF SENDING 200 AGC WORDS EVERY 2 SECONDS.
# CALLING SEQUENCE- NONE
#	   PROGRAM IS ENTERED VIA TCF DODOWNTM WHICH IS EXECUTED AS A
#	   RESULT OF A DOWNRUPT. CONTROL IS RETURNED VIA TCF RESUME WHICH
#	   IN EFFECT IS A RESUME.
# SUBROUTINES CALLED- NONE
# NORMAL EXIT MODE- TCF RESUME
# ALARM OR ABORT EXIT MODE- NONE
# RESTART PROTECTION- NONE.
#	   EXCEPT THAT WHEN A RESTART DOES OCCUR :STARTSUB: WILL
#	   INITIALIZE THE DOWNLIST POINTER TO THE BEGINNING OF THE NOMINAL
#	   DOWNLIST. THIS HAS THE EFFECT OF IGNORING THE REMAINDER OF THE
#	   DOWNLIST WHICH THE DOWN-TELEMETRY PROGRAM WAS WORKING ON WHEN
#	   THE RESTART OCCURRED.
# OUTPUT-  EVERY 2 SECONDS 100 DOUBLE PRECISION WORDS(I.E., 200 LGC
#	   COMPUTER WORDS) ARE TRANSMITTED VIA DOWNLINK.
# ERASABLE INITIALIZATION REQUIRED- NONE
#	   DNTMGOTO,DNLSTADR AND EBANK ARE INITIALIZED IN STARTSUB(FRESH
#	   START AND RESTART)
# DEBRIS (ERASABLE LOCATIONS DESTROYED BY THIS PROGRAM)-
#	   LDATALST,ITEMP1,ITEMP2,DNTMBUFF TO DNTMBUFF + 21D,TMINDEX,DNQ


		BANK	15
		EBANK=	DNTMBUFF
		
ERASZERO	EQUALS	7
DMYECADR	EQUALS	ERASZERO		# USE DMYECADR TO GENERATE A DUMMY ECADR
DMYADRES	EQUALS	ERASZERO		# USE DMYADRES TO GENERATE A DUMMY ADRES
UNKNOWN		EQUALS	ERASZERO		# USE UNKNOWN WHEN THE MNEMONIC IS UNKNOWN
SPARE		EQUALS	ERASZERO		# USE SPARE TO INDICATE AVAILABLE SPACE

LOWIDCOD	OCT	00437
## Page 330


# DODOWNTM IS ENTERED EVERY 20 MS BY AN INTERRUPT TRIGGERED BY THE
# RECEIPT OF AN ENDPULSE FROM THE SPACECRAFT TELEMETRY PROGRAMMER.

# THE ORGANIZATION OF THE PROGRAM IS AS FOLLOWS......
# 1. A MAIN PROGRAM(DODOWNTM) WHICH CONTROLS A SERIES OF SUBROUTINES.
# 2. SUBROUTINES(SENDID,SENDSNAP ETC.) WHICH ARE DESIGNED TO HANDLE
#    SPECIFIC PORTIONS OF THE DOWNLIST.
# 3. :EQUALS: CARDS(NDP1, NDP2, LINCR) WHICH DEFINE NO. OF ITEMS IN THE
#    PORTIONS OF THE DOWNLISTS.
# 4. DOWNLISTS. - DOWNLISTS MUST BE COMPILED IN THE SAME BANK AS THE
#    DOWN-TELEMETRY PROGRAM. THIS IS DONE FOR EASE OF CODING, FASTER
#    EXECUTION AND TO INSURE THAT THE DOWNLIST ID:S(FIRST WORD OF EACH
#    2 SEC DOWNLIST.) ARE UNIQUE. THE LOCATION OF THE AGS DOWNLIST MUST BE
#    2001 OF THE FBANK IN WHICH THE DOWN-TELEMETRY PROGRAM RESIDES.
#    (I.E. AGSLIST = XX,2001). THIS WILL MAKE THE ID WORD FO RTHE AGS
#    DOWNLINK DATA = 00001.

DODOWNTM	TS	BANKRUPT
		EXTEND
		QXCH	QRUPT
		INDEX	DNTMGOTO	# GO TO APPROPRIATE
		TCF	0		# TELEMETRY PHASE
DNPHASE1	TC	SENDID		# SEND ID WORD(S)
		CAF	BIT7		# SET WORD ORDER
		EXTEND			# BACK TO 1 FOR
		WOR	13		# REMAINDER OF CYCLE
		CA	DNLINCR		# CALCULATE ADDRESS OF
		ADS	LDATALST	# SNAPSHOT WORDS TO BE SENT  (GROUP 1)
		TC	SNAPSHOT	# SAVE AND SEND SNAPSHOT WORDS  (GROUP 1)
		CA	DNDP1-1		# PLACE NO. OF DP WORDS IN GROUP 1 INTO A
		TC	SENDDP		# SEND DOUBLE PRECISION WORDS (GROUP 1)
		TC	SENDCH		# SEND CHANNELS 11-14 AND 31-33
		TC	SENDDSTB	# SEND DISPLAY TABLES
		TC	SENDTIME	# SEND TIME1 AND TIME2
		CS	DNSNAP		# CALCULATE ADDRESS OF
		ADS	LDATALST	# SNAPSHOT WORDS TO BE SENT(GROUP 2)
		TC	SNAPSHOT	# SAVE AND SEND SNAPSHOT WORDS  (GROUP 2)
		CA	DNDP2-1		# PLACE NO. OF DP WORDS IN GROUP 2
		TC	SENDDP		# SEND DOUBLE PRECISION WORDS(GROUP 2)
		TC	SENDCH		# SEND CHANNELS 11-14 AND 31-33
		TC	SENDDSTB	# SEND DISPLAY TABLE
		TCF	DNPHASE1	# GO BACK AND START OVER
		
		
# ................................................................................
SENDID		CA	DNLSTADR	# INITIALIZE DOWNLIST ADDRESS AS SELECTED
		TS	LDATALST	# BY A MISSION OR TEST PROGRAM
		CS	BIT7		# SET WORD
		EXTEND			# ORDER BIT 7 IN
## Page 331
