# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Sunburst 120.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2016-09-29 RSB	created.
# 		2016-10-04 JL	Change to use Makefile.inc.
# 		2016-10-05 JL	Set yaYUL args back to default.

BASENAME=Sunburst120
include ../Makefile.inc
