/*
  File INCR_STACK_PTR.c generated by XCOM-I, 2024-08-09 12:39:13.
*/

#include "runtimeC.h"

int32_t
INCR_STACK_PTR (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "INCR_STACK_PTR");
  // STACK_PTR = STACK_PTR + 1; (1216)
  {
    int32_t numberRHS = (int32_t)(xadd (COREHALFWORD (mSTACK_PTR), 1));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mSTACK_PTR, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF STACK_PTR > MAX_STACK_LEVEL THEN (1217)
  if (1 & (xGT (COREHALFWORD (mSTACK_PTR), COREHALFWORD (mMAX_STACK_LEVEL))))
    // MAX_STACK_LEVEL = STACK_PTR; (1218)
    {
      descriptor_t *bitRHS = getBIT (16, mSTACK_PTR);
      putBIT (16, mMAX_STACK_LEVEL, bitRHS);
      bitRHS->inUse = 0;
    }
  // IF STACK_PTR >= RECORD_TOP(STACK_FRAME) THEN (1219)
  if (1
      & (xGE (COREHALFWORD (mSTACK_PTR),
              xsubtract (COREWORD (xadd (
                             ADDR ("STACK_FRAME", 0x80000000, NULL, 0), 12)),
                         1))))
    // DO ; (1220)
    {
    rs1:;
      // IF COREWORD ( ADDR ( STACK_FRAME ) + 12 ) >= COREWORD ( ADDR (
      // STACK_FRAME ) + 8 ) THEN (1221)
      if (1
          & (xGE (
              COREWORD (xadd (ADDR ("STACK_FRAME", 0x80000000, NULL, 0), 12)),
              COREWORD (xadd (ADDR ("STACK_FRAME", 0x80000000, NULL, 0), 8)))))
        // CALL _NEEDMORE_SPACE ( ADDR ( STACK_FRAME )  ) ; (1222)
        {
          putFIXED (m_NEEDMORE_SPACExDOPE,
                    ADDR ("STACK_FRAME", 0x80000000, NULL, 0));
          _NEEDMORE_SPACE (0);
        }
      // COREWORD ( ADDR ( STACK_FRAME ) + 12 ) = COREWORD ( ADDR ( STACK_FRAME
      // ) + 12 ) + 1 ; (1223)
      {
        int32_t numberRHS = (int32_t)(xadd (
            COREWORD (xadd (ADDR ("STACK_FRAME", 0x80000000, NULL, 0), 12)),
            1));
        COREWORD2 (xadd (ADDR ("STACK_FRAME", 0x80000000, NULL, 0), 12),
                   numberRHS);
      }
    es1:;
    } // End of DO block
  {
    reentryGuard = 0;
    return 0;
  }
}
