/*
  File OUTPUT_VAC_MAP.c generated by XCOM-I, 2024-08-08 04:32:08.
*/

#include "../AUXP/runtimeC.h"

int32_t
OUTPUT_VAC_MAP (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "OUTPUT_VAC_MAP");
  // WORK = 0; (805)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mOUTPUT_VAC_MAPxWORK, bitRHS);
    bitRHS->inUse = 0;
  }
  // OUTPUT = MAP_ID || BLANK || LEFT_PAREN || MAP# || RIGHT_PAREN || EQUAL;
  // (806)
  {
    descriptor_t *stringRHS;
    stringRHS = xsCAT (
        xsCAT (xsCAT (xsCAT (xsCAT (getCHARACTER (mOUTPUT_VAC_MAPxMAP_ID),
                                    getCHARACTER (mBLANK)),
                             getCHARACTER (mLEFT_PAREN)),
                      bitToCharacter (getBIT (16, mOUTPUT_VAC_MAPxMAPp))),
               getCHARACTER (mRIGHT_PAREN)),
        getCHARACTER (mEQUAL));
    OUTPUT (0, stringRHS);
    stringRHS->inUse = 0;
  }
  // DO WHILE TRUE; (807)
  while (1 & (1))
    {
      // MESSAGE = ''; (808)
      {
        descriptor_t *stringRHS;
        stringRHS = cToDescriptor (NULL, "");
        putCHARACTER (mOUTPUT_VAC_MAPxMESSAGE, stringRHS);
        stringRHS->inUse = 0;
      }
      // DO FOR LINE_INDEX = 1 TO 10; (809)
      {
        int32_t from18, to18, by18;
        from18 = 1;
        to18 = 10;
        by18 = 1;
        for (putBIT (16, mOUTPUT_VAC_MAPxLINE_INDEX, fixedToBit (16, from18));
             bitToFixed (getBIT (16, mOUTPUT_VAC_MAPxLINE_INDEX)) <= to18;
             putBIT (16, mOUTPUT_VAC_MAPxLINE_INDEX,
                     fixedToBit (16, bitToFixed (getBIT (
                                         16, mOUTPUT_VAC_MAPxLINE_INDEX))
                                         + by18)))
          {
            // MESSAGE = MESSAGE || HEX(SHR(VAC_REF_POOL(MAP# + WORK), 16) &
            // 65535, 4) || HEX(VAC_REF_POOL(MAP# + WORK) &  65535, 4) ||
            // PAD_CHARS; (810)
            {
              descriptor_t *stringRHS;
              stringRHS = xsCAT (
                  xsCAT (
                      xsCAT (
                          getCHARACTER (mOUTPUT_VAC_MAPxMESSAGE),
                          (putBITp (
                               16, mHEXxNUMBER,
                               fixedToBit (
                                   32,
                                   (int32_t)(xAND (
                                       SHR (
                                           COREWORD (
                                               getFIXED (mV_POOL)
                                               + 4
                                                     * (xadd (
                                                         COREHALFWORD (
                                                             mOUTPUT_VAC_MAPxMAPp),
                                                         COREHALFWORD (
                                                             mOUTPUT_VAC_MAPxWORK)))
                                               + 0 + 4 * (0)),
                                           16),
                                       65535)))),
                           putBITp (16, mHEXxTOTAL_LENGTH,
                                    fixedToBit (32, (int32_t)(4))),
                           HEX (0))),
                      (putBITp (
                           16, mHEXxNUMBER,
                           fixedToBit (
                               32,
                               (int32_t)(xAND (
                                   COREWORD (
                                       getFIXED (mV_POOL)
                                       + 4
                                             * (xadd (
                                                 COREHALFWORD (
                                                     mOUTPUT_VAC_MAPxMAPp),
                                                 COREHALFWORD (
                                                     mOUTPUT_VAC_MAPxWORK)))
                                       + 0 + 4 * (0)),
                                   65535)))),
                       putBITp (16, mHEXxTOTAL_LENGTH,
                                fixedToBit (32, (int32_t)(4))),
                       HEX (0))),
                  getCHARACTER (mOUTPUT_VAC_MAPxPAD_CHARS));
              putCHARACTER (mOUTPUT_VAC_MAPxMESSAGE, stringRHS);
              stringRHS->inUse = 0;
            }
            // WORK = WORK + 1; (811)
            {
              int32_t numberRHS
                  = (int32_t)(xadd (COREHALFWORD (mOUTPUT_VAC_MAPxWORK), 1));
              descriptor_t *bitRHS;
              bitRHS = fixedToBit (32, (int32_t)(numberRHS));
              putBIT (16, mOUTPUT_VAC_MAPxWORK, bitRHS);
              bitRHS->inUse = 0;
            }
            // IF (SHL(WORK, 5) > HALMAT_PTR) | (WORK >
            // VAC_REF_POOL_FRAME_SIZE) THEN (812)
            if (1
                & (xOR (xGT (SHL (COREHALFWORD (mOUTPUT_VAC_MAPxWORK), 5),
                             COREHALFWORD (mHALMAT_PTR)),
                        xGT (COREHALFWORD (mOUTPUT_VAC_MAPxWORK),
                             COREHALFWORD (mVAC_REF_POOL_FRAME_SIZE)))))
              // DO; (813)
              {
              rs1s1s1:;
                // OUTPUT = MESSAGE; (814)
                {
                  descriptor_t *stringRHS;
                  stringRHS = getCHARACTER (mOUTPUT_VAC_MAPxMESSAGE);
                  OUTPUT (0, stringRHS);
                  stringRHS->inUse = 0;
                }
                // RETURN; (815)
                {
                  reentryGuard = 0;
                  return 0;
                }
              es1s1s1:;
              } // End of DO block
          }
      } // End of DO for-loop block
      // OUTPUT = MESSAGE; (816)
      {
        descriptor_t *stringRHS;
        stringRHS = getCHARACTER (mOUTPUT_VAC_MAPxMESSAGE);
        OUTPUT (0, stringRHS);
        stringRHS->inUse = 0;
      }
    } // End of DO WHILE block
  {
    reentryGuard = 0;
    return 0;
  }
}
