/*
  File GENERATExBIT_STORE.c generated by XCOM-I, 2024-08-09 12:41:32.
*/

#include "runtimeC.h"

int32_t
GENERATExBIT_STORE (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExBIT_STORE");
  // CALL UPDATE_ASSIGN_CHECK(OP); (7373)
  {
    putBITp (16, mGENERATExUPDATE_ASSIGN_CHECKxOP,
             getBIT (16, mGENERATExBIT_STORExOP));
    GENERATExUPDATE_ASSIGN_CHECK (0);
  }
  // IF SIZE(LEFTOP) ~= SIZE(RIGHTOP) THEN (7374)
  if (1
      & (xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mLEFTOP)) + 48 + 2 * (0)),
               COREHALFWORD (getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mRIGHTOP)) + 48
                             + 2 * (0)))))
    // CALL ERRORS(CLASS_YA,100); (7375)
    {
      putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_YA));
      putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(100)));
      ERRORS (0);
    }
  // IF TYPE(OP) = EXTRABIT THEN (7376)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 50
                            + 2 * (0)),
              BYTE0 (mEXTRABIT))))
    // DO; (7377)
    {
    rs1:;
      // D_RTL_SETUP = TRUE; (7378)
      {
        int32_t numberRHS = (int32_t)(1);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (8, mD_RTL_SETUP, bitRHS);
        bitRHS->inUse = 0;
      }
      // TARGET_REGISTER = FIXARG3; (7379)
      {
        descriptor_t *bitRHS = getBIT (8, mFIXARG3);
        putBIT (16, mTARGET_REGISTER, bitRHS);
        bitRHS->inUse = 0;
      }
      // CALL FORCE_ACCUMULATOR(ROP, FULLBIT); (7380)
      {
        putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                 getBIT (16, mGENERATExBIT_STORExROP));
        putBITp (16, mGENERATExFORCE_ACCUMULATORxOPTYPE, getBIT (8, mFULLBIT));
        GENERATExFORCE_ACCUMULATOR (0);
      }
      // TARGET_REGISTER = -1; (7381)
      {
        int32_t numberRHS = (int32_t)(-1);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mTARGET_REGISTER, bitRHS);
        bitRHS->inUse = 0;
      }
      // CALL ASSIGN_CLEAR(OP, INX(OP) ~= 0); (7382)
      {
        putBITp (16, mGENERATExASSIGN_CLEARxOP,
                 getBIT (16, mGENERATExBIT_STORExOP));
        putBITp (1, mGENERATExASSIGN_CLEARxFLAG,
                 fixedToBit (
                     32, (int32_t)(xNEQ (
                             COREHALFWORD (
                                 getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                 + 34 + 2 * (0)),
                             0))));
        GENERATExASSIGN_CLEAR (0);
      }
      // CALL CLEAR_NAME_SAFE(OP); (7383)
      {
        putBITp (16, mGENERATExCLEAR_NAME_SAFExOP,
                 getBIT (16, mGENERATExBIT_STORExOP));
        GENERATExCLEAR_NAME_SAFE (0);
      }
      // CALL STACK_REG_PARM(FORCE_ADDRESS(PTRARG1, OP, 1)); (7384)
      {
        putBITp (
            16, mGENERATExSTACK_REG_PARMxR,
            fixedToBit (
                32, (int32_t)((putBITp (16, mGENERATExFORCE_ADDRESSxTR,
                                        getBIT (8, mPTRARG1)),
                               putBITp (16, mGENERATExFORCE_ADDRESSxOP,
                                        getBIT (16, mGENERATExBIT_STORExOP)),
                               putBITp (1, mGENERATExFORCE_ADDRESSxFLAG,
                                        fixedToBit (32, (int32_t)(1))),
                               GENERATExFORCE_ADDRESS (0)))));
        GENERATExSTACK_REG_PARM (0);
      }
      // CALL SET_CHAR_DESC(OP, FIXARG1, FIXARG2); (7385)
      {
        putBITp (16, mGENERATExSET_CHAR_DESCxOP,
                 getBIT (16, mGENERATExBIT_STORExOP));
        putBITp (16, mGENERATExSET_CHAR_DESCxR1, getBIT (8, mFIXARG1));
        putBITp (16, mGENERATExSET_CHAR_DESCxR0, getBIT (8, mFIXARG2));
        GENERATExSET_CHAR_DESC (0);
      }
      // CALL CHECK_VAC(ROP, FIXARG3); (7386)
      {
        putBITp (16, mGENERATExCHECK_VACxOP,
                 getBIT (16, mGENERATExBIT_STORExROP));
        putBITp (16, mGENERATExCHECK_VACxR, getBIT (8, mFIXARG3));
        GENERATExCHECK_VAC (0);
      }
      // CALL DROP_REG(ROP); (7387)
      {
        putBITp (16, mGENERATExDROP_REGxOP,
                 getBIT (16, mGENERATExBIT_STORExROP));
        GENERATExDROP_REG (0);
      }
      // CALL DROP_PARM_STACK; (7388)
      GENERATExDROP_PARM_STACK (0);
      // CALL GENLIBCALL('DSST'); (7389)
      {
        putCHARACTERp (mGENERATExGENLIBCALLxNAME,
                       cToDescriptor (NULL, "DSST"));
        GENERATExGENLIBCALL (0);
      }
      // IF DATA_REMOTE THEN (7390)
      if (1 & (bitToFixed (getBIT (1, mDATA_REMOTE))))
        // CALL PARM_STAT(OP,'DSST'); (7391)
        {
          putBITp (16, mGENERATExPARM_STATxOP,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putCHARACTERp (mGENERATExPARM_STATxROUTINE,
                         cToDescriptor (NULL, "DSST"));
          GENERATExPARM_STAT (0);
        }
      // CONFLICT = 0; (7392)
      {
        int32_t numberRHS = (int32_t)(0);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (1, mGENERATExBIT_STORExCONFLICT, bitRHS);
        bitRHS->inUse = 0;
      }
      // RETURN; (7393)
      {
        reentryGuard = 0;
        return 0;
      }
    es1:;
    } // End of DO block
  // ELSE (7394)
  else
    // IF TYPE(OP) = CHARSUBBIT THEN (7395)
    if (1
        & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                              + 50 + 2 * (0)),
                BYTE0 (mCHARSUBBIT))))
      // DO; (7396)
      {
      rs2:;
        // CALL ASSIGN_CLEAR(OP, INX(OP) ~= 0); (7397)
        {
          putBITp (16, mGENERATExASSIGN_CLEARxOP,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putBITp (
              1, mGENERATExASSIGN_CLEARxFLAG,
              fixedToBit (
                  32, (int32_t)(xNEQ (
                          COREHALFWORD (
                              getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                              + 34 + 2 * (0)),
                          0))));
          GENERATExASSIGN_CLEAR (0);
        }
        // CALL CHAR_CALL(XCSST, XVAL(OP), OP, 0, ROP); (7398)
        {
          putBITp (16, mGENERATExCHAR_CALLxOPCODE, getBIT (8, mXCSST));
          putBITp (16, mGENERATExCHAR_CALLxOP0,
                   fixedToBit (
                       32, (int32_t)(getFIXED (
                               getFIXED (mIND_STACK)
                               + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                               + 16 + 4 * (0)))));
          putBITp (16, mGENERATExCHAR_CALLxOP1,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putBITp (16, mGENERATExCHAR_CALLxOP2, fixedToBit (32, (int32_t)(0)));
          putBITp (16, mGENERATExCHAR_CALLxOP3,
                   getBIT (16, mGENERATExBIT_STORExROP));
          GENERATExCHAR_CALL (0);
        }
        // IF DATA_REMOTE THEN (7399)
        if (1 & (bitToFixed (getBIT (1, mDATA_REMOTE))))
          // CALL PARM_STAT(OP,'CSST'); (7400)
          {
            putBITp (16, mGENERATExPARM_STATxOP,
                     getBIT (16, mGENERATExBIT_STORExOP));
            putCHARACTERp (mGENERATExPARM_STATxROUTINE,
                           cToDescriptor (NULL, "CSST"));
            GENERATExPARM_STAT (0);
          }
        // CALL RETURN_STACK_ENTRY(XVAL(OP)); (7401)
        {
          putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                   fixedToBit (
                       32, (int32_t)(getFIXED (
                               getFIXED (mIND_STACK)
                               + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                               + 16 + 4 * (0)))));
          GENERATExRETURN_STACK_ENTRY (0);
        }
        // CONFLICT = 0; (7402)
        {
          int32_t numberRHS = (int32_t)(0);
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (1, mGENERATExBIT_STORExCONFLICT, bitRHS);
          bitRHS->inUse = 0;
        }
        // RETURN; (7403)
        {
          reentryGuard = 0;
          return 0;
        }
      es2:;
      } // End of DO block
  // IF (FORM(OP)=SYM) THEN (7404)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 32
                            + 2 * (0)),
              BYTE0 (mSYM))))
    // IF (SYT_BASE(LOC(OP))=REMOTE_BASE | NR_DEREF(OP)) &  (INX(OP)=0) THEN
    // (7405)
    if (1
        & (xAND (
            xOR (
                xEQ (COREHALFWORD (getFIXED (mP2SYMS)
                                   + 12
                                         * (COREHALFWORD (
                                             getFIXED (mIND_STACK)
                                             + 73
                                                   * (COREHALFWORD (
                                                       mGENERATExBIT_STORExOP))
                                             + 40 + 2 * (0)))
                                   + 4 + 2 * (0)),
                     BYTE0 (mREMOTE_BASE)),
                BYTE0 (getFIXED (mIND_STACK)
                       + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 60
                       + 1 * (0))),
            xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                               + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                               + 34 + 2 * (0)),
                 0))))
      // DO; (7406)
      {
      rs3:;
        // TEMP2 = TARGET_REGISTER; (7407)
        {
          descriptor_t *bitRHS = getBIT (16, mTARGET_REGISTER);
          int32_t numberRHS;
          numberRHS = bitToFixed (bitRHS);
          putFIXED (mTEMP2, numberRHS);
          bitRHS->inUse = 0;
        }
        // TARGET_REGISTER = -1; (7408)
        {
          int32_t numberRHS = (int32_t)(-1);
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (16, mTARGET_REGISTER, bitRHS);
          bitRHS->inUse = 0;
        }
        // CALL SUBSCRIPT_RANGE_CHECK(OP,1); (7409)
        {
          putBITp (16, mGENERATExSUBSCRIPT_RANGE_CHECKxOP,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putBITp (1, mGENERATExSUBSCRIPT_RANGE_CHECKxNEED_INDEXING,
                   fixedToBit (32, (int32_t)(1)));
          GENERATExSUBSCRIPT_RANGE_CHECK (0);
        }
        // TARGET_REGISTER = TEMP2; (7410)
        {
          int32_t numberRHS = (int32_t)(getFIXED (mTEMP2));
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (16, mTARGET_REGISTER, bitRHS);
          bitRHS->inUse = 0;
        }
      es3:;
      } // End of DO block
  // IMPMASK, SHORTLIT, ASSIGNED = FALSE; (7411)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExBIT_STORExIMPMASK, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExBIT_STORExSHORTLIT, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExBIT_STORExASSIGNED, bitRHS);
    bitRHS->inUse = 0;
  }
  // INDEXED = INX(OP) ~= 0; (7412)
  {
    int32_t numberRHS = (int32_t)(xNEQ (
        COREHALFWORD (getFIXED (mIND_STACK)
                      + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 34
                      + 2 * (0)),
        0));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExBIT_STORExINDEXED, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF SYMFORM(FORM(OP)) THEN (7413)
  if (1
      & (bitToFixed (getBIT (
          1, mSYMFORM
                 + 1
                       * COREHALFWORD (
                           getFIXED (mIND_STACK)
                           + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 32
                           + 2 * (0))))))
    // IF DATATYPE(SYT_TYPE(LOC2(OP))) ~= BITS THEN (7414)
    if (1
        & (xNEQ (
            BYTE0 (mDATATYPE
                   + 1
                         * BYTE0 (getFIXED (mSYM_TAB)
                                  + 34
                                        * (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73
                                                  * (COREHALFWORD (
                                                      mGENERATExBIT_STORExOP))
                                            + 42 + 2 * (0)))
                                  + 32 + 1 * (0))),
            BYTE0 (mBITS))))
      // IMPMASK = TRUE; (7415)
      {
        int32_t numberRHS = (int32_t)(1);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (1, mGENERATExBIT_STORExIMPMASK, bitRHS);
        bitRHS->inUse = 0;
      }
  // IF FORM(ROP) = LIT THEN (7416)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                            + 32 + 2 * (0)),
              BYTE0 (mLIT))))
    // DO; (7417)
    {
    rs4:;
      // IF CONFLICT THEN (7418)
      if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExCONFLICT))))
        // DO; (7419)
        {
        rs4s1:;
          // ROP = COPY_STACK_ENTRY(ROP); (7420)
          {
            descriptor_t *bitRHS
                = (putBITp (16, mGENERATExCOPY_STACK_ENTRYxPTR,
                            getBIT (16, mGENERATExBIT_STORExROP)),
                   GENERATExCOPY_STACK_ENTRY (0));
            putBIT (16, mGENERATExBIT_STORExROP, bitRHS);
            bitRHS->inUse = 0;
          }
          // CONFLICT = 2; (7421)
          {
            int32_t numberRHS = (int32_t)(2);
            descriptor_t *bitRHS;
            bitRHS = fixedToBit (32, (int32_t)(numberRHS));
            putBIT (1, mGENERATExBIT_STORExCONFLICT, bitRHS);
            bitRHS->inUse = 0;
          }
        es4s1:;
        } // End of DO block
      // CALL MASK_BIT_LIT(ROP, OP); (7422)
      {
        putBITp (16, mGENERATExMASK_BIT_LITxROP,
                 getBIT (16, mGENERATExBIT_STORExROP));
        putBITp (16, mGENERATExMASK_BIT_LITxLOP,
                 getBIT (16, mGENERATExBIT_STORExOP));
        GENERATExMASK_BIT_LIT (0);
      }
    es4:;
    } // End of DO block
  // IF COLUMN(OP) = 0 THEN (7423)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 24
                            + 2 * (0)),
              0)))
    // DO; (7424)
    {
    rs5:;
      // IF FORM(ROP) = LIT THEN (7425)
      if (1
          & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                                + 32 + 2 * (0)),
                  BYTE0 (mLIT))))
        // SHORTLIT=(VAL(ROP)=0|VAL(ROP)=XITAB(SIZE(OP))) & OPMODE(TYPE(OP))=1;
        // (7426)
        {
          int32_t numberRHS = (int32_t)(xAND (
              xOR (xEQ (getFIXED (
                            getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                            + 12 + 4 * (0)),
                        0),
                   xEQ (getFIXED (
                            getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                            + 12 + 4 * (0)),
                        getFIXED (mGENERATExXITAB
                                  + 4
                                        * COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73
                                                  * (COREHALFWORD (
                                                      mGENERATExBIT_STORExOP))
                                            + 48 + 2 * (0))))),
              xEQ (BYTE0 (
                       mOPMODE
                       + 1
                             * COREHALFWORD (
                                 getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                 + 50 + 2 * (0))),
                   1)));
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (1, mGENERATExBIT_STORExSHORTLIT, bitRHS);
          bitRHS->inUse = 0;
        }
      // ELSE (7427)
      else
        // SHORTLIT = SHL(DUPLICATE_OPERANDS(OP, ROP), 1); (7428)
        {
          int32_t numberRHS = (int32_t)(SHL (
              bitToFixed ((putBITp (16, mGENERATExDUPLICATE_OPERANDSxOP1,
                                    getBIT (16, mGENERATExBIT_STORExOP)),
                           putBITp (16, mGENERATExDUPLICATE_OPERANDSxOP2,
                                    getBIT (16, mGENERATExBIT_STORExROP)),
                           GENERATExDUPLICATE_OPERANDS (0))),
              1));
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (1, mGENERATExBIT_STORExSHORTLIT, bitRHS);
          bitRHS->inUse = 0;
        }
      // IF SHORTLIT > 0 THEN (7429)
      if (1 & (xGT (BYTE0 (mGENERATExBIT_STORExSHORTLIT), 0)))
        // DO; (7430)
        {
        rs5s1:;
          // CALL MAKE_BIT_OP; (7431)
          GENERATExBIT_STORExMAKE_BIT_OP (0);
          // CALL MASK_BIT_OP; (7432)
          GENERATExBIT_STORExMASK_BIT_OP (0);
        es5s1:;
        } // End of DO block
      // IF ASSIGNED THEN (7433)
      if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExASSIGNED))))
        // CALL ASSIGN_CLEAR(OP, INDEXED, SHORTLIT, ROP); (7434)
        {
          putBITp (16, mGENERATExASSIGN_CLEARxOP,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putBITp (1, mGENERATExASSIGN_CLEARxFLAG,
                   getBIT (1, mGENERATExBIT_STORExINDEXED));
          putBITp (2, mGENERATExASSIGN_CLEARxAGAIN,
                   getBIT (1, mGENERATExBIT_STORExSHORTLIT));
          putBITp (16, mGENERATExASSIGN_CLEARxOP2,
                   getBIT (16, mGENERATExBIT_STORExROP));
          GENERATExASSIGN_CLEAR (0);
        }
      // ELSE (7435)
      else
        // DO; (7436)
        {
        rs5s2:;
          // CALL FORCE_ACCUMULATOR(ROP, TYPE(OP)); (7437)
          {
            putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                     getBIT (16, mGENERATExBIT_STORExROP));
            putBITp (
                16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
                getBIT (16, getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 50 + 2 * (0)));
            GENERATExFORCE_ACCUMULATOR (0);
          }
          // IF SIZE(ROP) > SIZE(OP) THEN (7438)
          if (1
              & (xGT (
                  COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                                + 48 + 2 * (0)),
                  COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 48 + 2 * (0)))))
            // DO; (7439)
            {
            rs5s2s1:;
              // IF SIZE(OP) ~= BIGHTS(TYPE(OP))*BITESIZE THEN (7440)
              if (1
                  & (xNEQ (
                      COREHALFWORD (
                          getFIXED (mIND_STACK)
                          + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP)) + 48
                          + 2 * (0)),
                      xmultiply (
                          BYTE0 (mBIGHTS
                                 + 1
                                       * COREHALFWORD (
                                           getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExBIT_STORExOP))
                                           + 50 + 2 * (0))),
                          BYTE0 (mBITESIZE)))))
                // DO; (7441)
                {
                rs5s2s1s1:;
                  // CALL CHECK_BIT_OP; (7442)
                  GENERATExBIT_STORExCHECK_BIT_OP (0);
                  // CALL BIT_MASK(AND, ROP, SIZE(OP)); (7443)
                  {
                    putBITp (16, mGENERATExBIT_MASKxOPCODE,
                             getBIT (16, mGENERATExAND));
                    putBITp (16, mGENERATExBIT_MASKxOP,
                             getBIT (16, mGENERATExBIT_STORExROP));
                    putBITp (16, mGENERATExBIT_MASKxXSIZE,
                             getBIT (16, getFIXED (mIND_STACK)
                                             + 73
                                                   * (COREHALFWORD (
                                                       mGENERATExBIT_STORExOP))
                                             + 48 + 2 * (0)));
                    GENERATExBIT_MASK (0);
                  }
                es5s2s1s1:;
                } // End of DO block
              // ELSE (7444)
              else
                // IMPMASK = TRUE; (7445)
                {
                  int32_t numberRHS = (int32_t)(1);
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (1, mGENERATExBIT_STORExIMPMASK, bitRHS);
                  bitRHS->inUse = 0;
                }
            es5s2s1:;
            } // End of DO block
          // CALL GEN_STORE(ROP, OP, CONFLICT); (7446)
          {
            putBITp (16, mGENERATExGEN_STORExROP,
                     getBIT (16, mGENERATExBIT_STORExROP));
            putBITp (16, mGENERATExGEN_STORExOP,
                     getBIT (16, mGENERATExBIT_STORExOP));
            putBITp (1, mGENERATExGEN_STORExFLAG,
                     getBIT (1, mGENERATExBIT_STORExCONFLICT));
            GENERATExGEN_STORE (0);
          }
          // IF IMPMASK THEN (7447)
          if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExIMPMASK))))
            // CALL UNRECOGNIZABLE(REG(ROP)); (7448)
            {
              putBITp (
                  16, mGENERATExUNRECOGNIZABLExR,
                  getBIT (16,
                          getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                              + 46 + 2 * (0)));
              GENERATExUNRECOGNIZABLE (0);
            }
        es5s2:;
        } // End of DO block
    es5:;
    } // End of DO block
  // ELSE (7449)
  else
    // DO; (7450)
    {
    rs6:;
      // IF CONFLICT THEN (7451)
      if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExCONFLICT))))
        // CALL FORCE_ACCUMULATOR(ROP, TYPE(OP)); (7452)
        {
          putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                   getBIT (16, mGENERATExBIT_STORExROP));
          putBITp (
              16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
              getBIT (16, getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                              + 50 + 2 * (0)));
          GENERATExFORCE_ACCUMULATOR (0);
        }
      // ELSE (7453)
      else
        // IF FORM(COLUMN(OP)) = LIT THEN (7454)
        if (1
            & (xEQ (
                COREHALFWORD (
                    getFIXED (mIND_STACK)
                    + 73
                          * (COREHALFWORD (
                              getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                              + 24 + 2 * (0)))
                    + 32 + 2 * (0)),
                BYTE0 (mLIT))))
          // DO; (7455)
          {
          rs6s1:;
            // IF FORM(ROP) = LIT THEN (7456)
            if (1
                & (xEQ (COREHALFWORD (
                            getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                            + 32 + 2 * (0)),
                        BYTE0 (mLIT))))
              // SHORTLIT = VAL(ROP) = 0 | VAL(ROP) = XITAB(SIZE(OP)); (7457)
              {
                int32_t numberRHS = (int32_t)(xOR (
                    xEQ (getFIXED (
                             getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                             + 12 + 4 * (0)),
                         0),
                    xEQ (getFIXED (
                             getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                             + 12 + 4 * (0)),
                         getFIXED (mGENERATExXITAB
                                   + 4
                                         * COREHALFWORD (
                                             getFIXED (mIND_STACK)
                                             + 73
                                                   * (COREHALFWORD (
                                                       mGENERATExBIT_STORExOP))
                                             + 48 + 2 * (0))))));
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (1, mGENERATExBIT_STORExSHORTLIT, bitRHS);
                bitRHS->inUse = 0;
              }
            // ELSE (7458)
            else
              // SHORTLIT = SHL(DUPLICATE_OPERANDS(OP, ROP), 1); (7459)
              {
                int32_t numberRHS = (int32_t)(SHL (
                    bitToFixed (
                        (putBITp (16, mGENERATExDUPLICATE_OPERANDSxOP1,
                                  getBIT (16, mGENERATExBIT_STORExOP)),
                         putBITp (16, mGENERATExDUPLICATE_OPERANDSxOP2,
                                  getBIT (16, mGENERATExBIT_STORExROP)),
                         GENERATExDUPLICATE_OPERANDS (0))),
                    1));
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (1, mGENERATExBIT_STORExSHORTLIT, bitRHS);
                bitRHS->inUse = 0;
              }
          es6s1:;
          } // End of DO block
        // ELSE (7460)
        else
          // CALL FORCE_ACCUMULATOR(ROP, TYPE(OP)); (7461)
          {
            putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                     getBIT (16, mGENERATExBIT_STORExROP));
            putBITp (
                16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
                getBIT (16, getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 50 + 2 * (0)));
            GENERATExFORCE_ACCUMULATOR (0);
          }
      // IF SHORTLIT > 0 THEN (7462)
      if (1 & (xGT (BYTE0 (mGENERATExBIT_STORExSHORTLIT), 0)))
        // DO; (7463)
        {
        rs6s2:;
          // CALL MAKE_BIT_OP; (7464)
          GENERATExBIT_STORExMAKE_BIT_OP (0);
          // CALL MASK_BIT_OP; (7465)
          GENERATExBIT_STORExMASK_BIT_OP (0);
        es6s2:;
        } // End of DO block
      // IF ASSIGNED THEN (7466)
      if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExASSIGNED))))
        // CALL ASSIGN_CLEAR(OP, INDEXED, SHORTLIT, ROP); (7467)
        {
          putBITp (16, mGENERATExASSIGN_CLEARxOP,
                   getBIT (16, mGENERATExBIT_STORExOP));
          putBITp (1, mGENERATExASSIGN_CLEARxFLAG,
                   getBIT (1, mGENERATExBIT_STORExINDEXED));
          putBITp (2, mGENERATExASSIGN_CLEARxAGAIN,
                   getBIT (1, mGENERATExBIT_STORExSHORTLIT));
          putBITp (16, mGENERATExASSIGN_CLEARxOP2,
                   getBIT (16, mGENERATExBIT_STORExROP));
          GENERATExASSIGN_CLEAR (0);
        }
      // ELSE (7468)
      else
        // DO; (7469)
        {
        rs6s3:;
          // IF FORM(ROP) = VAC THEN (7470)
          if (1
              & (xEQ (
                  COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                                + 32 + 2 * (0)),
                  BYTE0 (mVAC))))
            // NOT_THIS_REGISTER = REG(ROP); (7471)
            {
              descriptor_t *bitRHS = getBIT (
                  16, getFIXED (mIND_STACK)
                          + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP)) + 46
                          + 2 * (0));
              putBIT (16, mNOT_THIS_REGISTER, bitRHS);
              bitRHS->inUse = 0;
            }
          // BOP = GET_VAC(-1, FULLBIT); (7472)
          {
            descriptor_t *bitRHS
                = (putBITp (16, mGENERATExGET_VACxR,
                            fixedToBit (32, (int32_t)(-1))),
                   putBITp (16, mGENERATExGET_VACxTYP, getBIT (8, mFULLBIT)),
                   GENERATExGET_VAC (0));
            putBIT (16, mGENERATExBIT_STORExBOP, bitRHS);
            bitRHS->inUse = 0;
          }
          // IF FORM(BOP) = VAC THEN (7473)
          if (1
              & (xEQ (
                  COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExBOP))
                                + 32 + 2 * (0)),
                  BYTE0 (mVAC))))
            // NOT_THIS_REGISTER2 = REG(BOP); (7474)
            {
              descriptor_t *bitRHS = getBIT (
                  16, getFIXED (mIND_STACK)
                          + 73 * (COREHALFWORD (mGENERATExBIT_STORExBOP)) + 46
                          + 2 * (0));
              putBIT (16, mNOT_THIS_REGISTER2, bitRHS);
              bitRHS->inUse = 0;
            }
          // CALL GUARANTEE_ADDRESSABLE(OP, MAKE_INST(LOAD,TYPE(OP),RX),
          // BY_NAME_FALSE, 1); (7475)
          {
            putBITp (16, mGENERATExGUARANTEE_ADDRESSABLExOP,
                     getBIT (16, mGENERATExBIT_STORExOP));
            putBITp (
                16, mGENERATExGUARANTEE_ADDRESSABLExINST,
                (putBITp (16, mGENERATExMAKE_INSTxOPCODE,
                          getBIT (16, mGENERATExLOAD)),
                 putBITp (
                     16, mGENERATExMAKE_INSTxOPTYPE,
                     getBIT (16,
                             getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                 + 50 + 2 * (0))),
                 putBITp (16, mGENERATExMAKE_INSTxOPFORM,
                          getBIT (16, mGENERATExRX)),
                 GENERATExMAKE_INST (0)));
            putBITp (1, mGENERATExGUARANTEE_ADDRESSABLExBY_NAME,
                     fixedToBit (32, (int32_t)(0)));
            putBITp (1, mGENERATExGUARANTEE_ADDRESSABLExNEED_SRS,
                     fixedToBit (32, (int32_t)(1)));
            GENERATExGUARANTEE_ADDRESSABLE (0);
          }
          // IF FORM(OP) = CSYM THEN (7476)
          if (1
              & (xEQ (
                  COREHALFWORD (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 32 + 2 * (0)),
                  BYTE0 (mCSYM))))
            // CALL INCR_USAGE(BASE(OP)); (7477)
            {
              putBITp (
                  16, mGENERATExINCR_USAGExR,
                  getBIT (16,
                          getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                              + 22 + 2 * (0)));
              GENERATExINCR_USAGE (0);
            }
          // CALL EMIT_BY_MODE(LOAD, REG(BOP), OP, TYPE(OP)); (7478)
          {
            putBITp (16, mGENERATExEMIT_BY_MODExOP,
                     getBIT (16, mGENERATExLOAD));
            putBITp (
                16, mGENERATExEMIT_BY_MODExR,
                getBIT (16, getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExBOP))
                                + 46 + 2 * (0)));
            putBITp (16, mGENERATExEMIT_BY_MODExOP2,
                     getBIT (16, mGENERATExBIT_STORExOP));
            putBITp (
                16, mGENERATExEMIT_BY_MODExMODE,
                getBIT (16, getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 50 + 2 * (0)));
            GENERATExEMIT_BY_MODE (0);
          }
          // IF (SYT_DIMS(LOC2(OP)) &  65280) ~= 0 THEN (7479)
          if (1
              & (xNEQ (xAND (COREHALFWORD (
                                 getFIXED (mSYM_TAB)
                                 + 34
                                       * (COREHALFWORD (
                                           getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExBIT_STORExOP))
                                           + 42 + 2 * (0)))
                                 + 18 + 2 * (0)),
                             65280),
                       0)))
            // IMPMASK = TRUE; (7480)
            {
              int32_t numberRHS = (int32_t)(1);
              descriptor_t *bitRHS;
              bitRHS = fixedToBit (32, (int32_t)(numberRHS));
              putBIT (1, mGENERATExBIT_STORExIMPMASK, bitRHS);
              bitRHS->inUse = 0;
            }
          // CALL CHECK_BIT_OP; (7481)
          GENERATExBIT_STORExCHECK_BIT_OP (0);
          // IF SHORTLIT > 0 THEN (7482)
          if (1 & (xGT (BYTE0 (mGENERATExBIT_STORExSHORTLIT), 0)))
            // DO; (7483)
            {
            rs6s3s1:;
              // CALL MAKE_BIT_OP; (7484)
              GENERATExBIT_STORExMAKE_BIT_OP (0);
              // CALL ARITH_BY_MODE(TMP, BOP, LOP, TYPE(OP)); (7485)
              {
                putBITp (16, mGENERATExARITH_BY_MODExOP,
                         fixedToBit (32, (int32_t)(getFIXED (mTMP))));
                putBITp (16, mGENERATExARITH_BY_MODExOP1,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                putBITp (16, mGENERATExARITH_BY_MODExOP2,
                         getBIT (16, mGENERATExBIT_STORExLOP));
                putBITp (
                    16, mGENERATExARITH_BY_MODExOPTYPE,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 50 + 2 * (0)));
                GENERATExARITH_BY_MODE (0);
              }
              // IF SHORTLIT > 1 THEN (7486)
              if (1 & (xGT (BYTE0 (mGENERATExBIT_STORExSHORTLIT), 1)))
                // CALL DROP_UNUSED(ROP); (7487)
                {
                  putBITp (16, mGENERATExDROP_UNUSEDxOP,
                           getBIT (16, mGENERATExBIT_STORExROP));
                  GENERATExDROP_UNUSED (0);
                }
              // CALL GEN_STORE(BOP, OP, TRUE); (7488)
              {
                putBITp (16, mGENERATExGEN_STORExROP,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                putBITp (16, mGENERATExGEN_STORExOP,
                         getBIT (16, mGENERATExBIT_STORExOP));
                putBITp (1, mGENERATExGEN_STORExFLAG,
                         fixedToBit (32, (int32_t)(1)));
                GENERATExGEN_STORE (0);
              }
              // IF IMPMASK THEN (7489)
              if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExIMPMASK))))
                // CALL UNRECOGNIZABLE(REG(BOP)); (7490)
                {
                  putBITp (16, mGENERATExUNRECOGNIZABLExR,
                           getBIT (16, getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExBIT_STORExBOP))
                                           + 46 + 2 * (0)));
                  GENERATExUNRECOGNIZABLE (0);
                }
              // NOT_THIS_REGISTER2 = -1; (7491)
              {
                int32_t numberRHS = (int32_t)(-1);
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (16, mNOT_THIS_REGISTER2, bitRHS);
                bitRHS->inUse = 0;
              }
              // CALL DROP_VAC(BOP); (7492)
              {
                putBITp (16, mGENERATExDROP_VACxPTR,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                GENERATExDROP_VAC (0);
              }
            es6s3s1:;
            } // End of DO block
          // ELSE (7493)
          else
            // DO; (7494)
            {
            rs6s3s2:;
              // NOT_THIS_REGISTER2 = -1; (7495)
              {
                int32_t numberRHS = (int32_t)(-1);
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (16, mNOT_THIS_REGISTER2, bitRHS);
                bitRHS->inUse = 0;
              }
              // IF SYT_CLASS(LOC2(OP)) = TEMPLATE_CLASS THEN (7496)
              if (1
                  & (xEQ (BYTE0 (getFIXED (mSYM_TAB)
                                 + 34
                                       * (COREHALFWORD (
                                           getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExBIT_STORExOP))
                                           + 42 + 2 * (0)))
                                 + 30 + 1 * (0)),
                          COREHALFWORD (mTEMPLATE_CLASS))))
                // SYT_FLAGS(LOC2(OP)) = SYT_FLAGS(LOC2(OP)) | BITMASK_FLAG;
                // (7497)
                {
                  int32_t numberRHS = (int32_t)(xOR (
                      getFIXED (getFIXED (mSYM_TAB)
                                + 34
                                      * (COREHALFWORD (
                                          getFIXED (mIND_STACK)
                                          + 73
                                                * (COREHALFWORD (
                                                    mGENERATExBIT_STORExOP))
                                          + 42 + 2 * (0)))
                                + 8 + 4 * (0)),
                      getFIXED (mBITMASK_FLAG)));
                  putFIXED (getFIXED (mSYM_TAB)
                                + 34
                                      * (COREHALFWORD (
                                          getFIXED (mIND_STACK)
                                          + 73
                                                * (COREHALFWORD (
                                                    mGENERATExBIT_STORExOP))
                                          + 42 + 2 * (0)))
                                + 8 + 4 * (0),
                            numberRHS);
                }
              // ELSE (7498)
              else
                // SYT_FLAGS(LOC(OP)) = SYT_FLAGS(LOC(OP)) | BITMASK_FLAG;
                // (7499)
                {
                  int32_t numberRHS = (int32_t)(xOR (
                      getFIXED (getFIXED (mSYM_TAB)
                                + 34
                                      * (COREHALFWORD (
                                          getFIXED (mIND_STACK)
                                          + 73
                                                * (COREHALFWORD (
                                                    mGENERATExBIT_STORExOP))
                                          + 40 + 2 * (0)))
                                + 8 + 4 * (0)),
                      getFIXED (mBITMASK_FLAG)));
                  putFIXED (getFIXED (mSYM_TAB)
                                + 34
                                      * (COREHALFWORD (
                                          getFIXED (mIND_STACK)
                                          + 73
                                                * (COREHALFWORD (
                                                    mGENERATExBIT_STORExOP))
                                          + 40 + 2 * (0)))
                                + 8 + 4 * (0),
                            numberRHS);
                }
              // SYT_FLAGS(SELFNAMELOC) = SYT_FLAGS(SELFNAMELOC) |
              // BITMASK_FLAG; (7500)
              {
                int32_t numberRHS = (int32_t)(xOR (
                    getFIXED (getFIXED (mSYM_TAB)
                              + 34 * (COREHALFWORD (mSELFNAMELOC)) + 8
                              + 4 * (0)),
                    getFIXED (mBITMASK_FLAG)));
                putFIXED (getFIXED (mSYM_TAB)
                              + 34 * (COREHALFWORD (mSELFNAMELOC)) + 8
                              + 4 * (0),
                          numberRHS);
              }
              // CALL SET_MASKING_BIT(LINE#); (7501)
              {
                putBITp (16, mSET_MASKING_BITxSTMT_NO,
                         fixedToBit (32, (int32_t)(getFIXED (mLINEp))));
                SET_MASKING_BIT (0);
              }
              // CALL BIT_SHIFT(SLL, ROP, COLUMN(OP), 1); (7502)
              {
                putBITp (16, mGENERATExBIT_SHIFTxOPCODE, getBIT (8, mSLL));
                putBITp (16, mGENERATExBIT_SHIFTxR,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (
                    16, mGENERATExBIT_SHIFTxOP,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 24 + 2 * (0)));
                putBITp (1, mGENERATExBIT_SHIFTxFLAG,
                         fixedToBit (32, (int32_t)(1)));
                GENERATExBIT_SHIFT (0);
              }
              // CALL FORCE_ACCUMULATOR(ROP, TYPE(OP)); (7503)
              {
                putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (
                    16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 50 + 2 * (0)));
                GENERATExFORCE_ACCUMULATOR (0);
              }
              // NOT_THIS_REGISTER = REG(ROP); (7504)
              {
                descriptor_t *bitRHS = getBIT (
                    16, getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExBIT_STORExROP))
                            + 46 + 2 * (0));
                putBIT (16, mNOT_THIS_REGISTER, bitRHS);
                bitRHS->inUse = 0;
              }
              // CALL ARITH_BY_MODE(EXOR, ROP, BOP, TYPE(BOP)); (7505)
              {
                putBITp (16, mGENERATExARITH_BY_MODExOP,
                         getBIT (16, mGENERATExEXOR));
                putBITp (16, mGENERATExARITH_BY_MODExOP1,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (16, mGENERATExARITH_BY_MODExOP2,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                putBITp (
                    16, mGENERATExARITH_BY_MODExOPTYPE,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExBOP))
                                + 50 + 2 * (0)));
                GENERATExARITH_BY_MODE (0);
              }
              // CALL BIT_MASK(AND, ROP, SIZE(OP), COLUMN(OP)); (7506)
              {
                putBITp (16, mGENERATExBIT_MASKxOPCODE,
                         getBIT (16, mGENERATExAND));
                putBITp (16, mGENERATExBIT_MASKxOP,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (
                    16, mGENERATExBIT_MASKxXSIZE,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 48 + 2 * (0)));
                putBITp (
                    16, mGENERATExBIT_MASKxSHIFT,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                + 24 + 2 * (0)));
                GENERATExBIT_MASK (0);
              }
              // CALL ARITH_BY_MODE(EXOR, ROP, BOP, TYPE(BOP)); (7507)
              {
                putBITp (16, mGENERATExARITH_BY_MODExOP,
                         getBIT (16, mGENERATExEXOR));
                putBITp (16, mGENERATExARITH_BY_MODExOP1,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (16, mGENERATExARITH_BY_MODExOP2,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                putBITp (
                    16, mGENERATExARITH_BY_MODExOPTYPE,
                    getBIT (16,
                            getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mGENERATExBIT_STORExBOP))
                                + 50 + 2 * (0)));
                GENERATExARITH_BY_MODE (0);
              }
              // CALL DROP_VAC(BOP); (7508)
              {
                putBITp (16, mGENERATExDROP_VACxPTR,
                         getBIT (16, mGENERATExBIT_STORExBOP));
                GENERATExDROP_VAC (0);
              }
              // CALL GEN_STORE(ROP, OP, CONFLICT); (7509)
              {
                putBITp (16, mGENERATExGEN_STORExROP,
                         getBIT (16, mGENERATExBIT_STORExROP));
                putBITp (16, mGENERATExGEN_STORExOP,
                         getBIT (16, mGENERATExBIT_STORExOP));
                putBITp (1, mGENERATExGEN_STORExFLAG,
                         getBIT (1, mGENERATExBIT_STORExCONFLICT));
                GENERATExGEN_STORE (0);
              }
              // NOT_THIS_REGISTER = -1; (7510)
              {
                int32_t numberRHS = (int32_t)(-1);
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (16, mNOT_THIS_REGISTER, bitRHS);
                bitRHS->inUse = 0;
              }
              // IF IMPMASK THEN (7511)
              if (1 & (bitToFixed (getBIT (1, mGENERATExBIT_STORExIMPMASK))))
                // CALL UNRECOGNIZABLE(REG(ROP)); (7512)
                {
                  putBITp (16, mGENERATExUNRECOGNIZABLExR,
                           getBIT (16, getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExBIT_STORExROP))
                                           + 46 + 2 * (0)));
                  GENERATExUNRECOGNIZABLE (0);
                }
            es6s3s2:;
            } // End of DO block
        es6s3:;
        } // End of DO block
      // CALL RETURN_STACK_ENTRY(COLUMN(OP)); (7513)
      {
        putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                 getBIT (16, getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mGENERATExBIT_STORExOP))
                                 + 24 + 2 * (0)));
        GENERATExRETURN_STACK_ENTRY (0);
      }
    es6:;
    } // End of DO block
  // IF TOP > 0 THEN (7514)
  if (1 & (xGT (COREHALFWORD (mGENERATExBIT_STORExTOP), 0)))
    // CALL RETURN_STACK_ENTRY(TOP); (7515)
    {
      putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
               getBIT (16, mGENERATExBIT_STORExTOP));
      GENERATExRETURN_STACK_ENTRY (0);
    }
  // IF CONFLICT > 1 THEN (7516)
  if (1 & (xGT (BYTE0 (mGENERATExBIT_STORExCONFLICT), 1)))
    // CALL RETURN_STACK_ENTRY(ROP); (7517)
    {
      putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
               getBIT (16, mGENERATExBIT_STORExROP));
      GENERATExRETURN_STACK_ENTRY (0);
    }
  // CONFLICT, TOP = 0; (7518)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExBIT_STORExCONFLICT, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mGENERATExBIT_STORExTOP, bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
