/*
  File GENERATExCHECK_ASSIGN_PARM.c generated by XCOM-I, 2024-08-08 04:34:25.
*/

#include "runtimeC.h"

int32_t
GENERATExCHECK_ASSIGN_PARM (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExCHECK_ASSIGN_PARM");
  // SYMP = SYMFORM(FORM(RIGHTOP)); (7932)
  {
    descriptor_t *bitRHS
        = getBIT (1, mSYMFORM
                         + 1
                               * COREHALFWORD (getFIXED (mIND_STACK)
                                               + 73 * (COREHALFWORD (mRIGHTOP))
                                               + 32 + 2 * (0)));
    putBIT (1, mGENERATExCHECK_ASSIGN_PARMxSYMP, bitRHS);
    bitRHS->inUse = 0;
  }
  // SYMP = SYMP | (NR_DEREF(RIGHTOP) & FORM(RIGHTOP)=NRTEMP); (7933)
  {
    int32_t numberRHS = (int32_t)(xOR (
        BYTE0 (mGENERATExCHECK_ASSIGN_PARMxSYMP),
        xAND (BYTE0 (getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mRIGHTOP))
                     + 60 + 1 * (0)),
              xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mRIGHTOP)) + 32
                                 + 2 * (0)),
                   BYTE0 (mWORK)))));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExCHECK_ASSIGN_PARMxSYMP, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF TAG THEN (7934)
  if (1 & (bitToFixed (getBIT (1, mGENERATExCHECK_ASSIGN_PARMxTAG))))
    // CALL CHECK_ATTRIBUTES; (7935)
    GENERATExCHECK_ATTRIBUTES (0);
  // IF SYMP THEN (7936)
  if (1 & (bitToFixed (getBIT (1, mGENERATExCHECK_ASSIGN_PARMxSYMP))))
    // ARGLOC = LOC2(RIGHTOP); (7937)
    {
      descriptor_t *bitRHS
          = getBIT (16, getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mRIGHTOP))
                            + 42 + 2 * (0));
      putBIT (16, mGENERATExCHECK_ASSIGN_PARMxARGLOC, bitRHS);
      bitRHS->inUse = 0;
    }
  // ELSE (7938)
  else
    // ARGLOC = VAL(RIGHTOP); (7939)
    {
      int32_t numberRHS = (int32_t)(getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 12 + 4 * (0)));
      descriptor_t *bitRHS;
      bitRHS = fixedToBit (32, (int32_t)(numberRHS));
      putBIT (16, mGENERATExCHECK_ASSIGN_PARMxARGLOC, bitRHS);
      bitRHS->inUse = 0;
    }
  // IF ARGTYPE ~= TYPE(RIGHTOP) THEN (7940)
  if (1
      & (xNEQ (COREHALFWORD (mARGTYPE),
               COREHALFWORD (getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mRIGHTOP)) + 50
                             + 2 * (0)))))
    // IF CLASS=8 THEN (7941)
    if (1 & (xEQ (COREHALFWORD (mCLASS), 8)))
      // CALL ERRORS(CLASS_DI,108); (7942)
      {
        putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
        putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(108)));
        ERRORS (0);
      }
    // ELSE (7943)
    else
      // CALL ERRORS(CLASS_FT,101,''||ARGNO); (7944)
      {
        putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_FT));
        putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(101)));
        putCHARACTERp (mERRORSxTEXT,
                       xsCAT (cToDescriptor (NULL, ""),
                              bitToCharacter (getBIT (16, mARGNO))));
        ERRORS (0);
      }
  // ARRNESS = GETARRAY#(ARGPOINT); (7945)
  {
    descriptor_t *bitRHS
        = (putBITp (16, mGETARRAYpxOP, getBIT (16, mARGPOINT)), GETARRAYp (0));
    putBIT (16, mGENERATExCHECK_ASSIGN_PARMxARRNESS, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF ARRNESS ~= COPY(RIGHTOP) THEN (7946)
  if (1
      & (xNEQ (COREHALFWORD (mGENERATExCHECK_ASSIGN_PARMxARRNESS),
               COREHALFWORD (getFIXED (mIND_STACK)
                             + 73 * (COREHALFWORD (mRIGHTOP)) + 26
                             + 2 * (0)))))
    // IF CLASS=8 THEN (7947)
    if (1 & (xEQ (COREHALFWORD (mCLASS), 8)))
      // CALL ERRORS(CLASS_DI,110); (7948)
      {
        putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
        putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(110)));
        ERRORS (0);
      }
    // ELSE (7949)
    else
      // CALL ERRORS(CLASS_FD,100,''||ARGNO); (7950)
      {
        putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_FD));
        putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(100)));
        putCHARACTERp (mERRORSxTEXT,
                       xsCAT (cToDescriptor (NULL, ""),
                              bitToCharacter (getBIT (16, mARGNO))));
        ERRORS (0);
      }
  // DO I = 1 TO ARRNESS; (7951)
  {
    int32_t from89, to89, by89;
    from89 = 1;
    to89 = bitToFixed (getBIT (16, mGENERATExCHECK_ASSIGN_PARMxARRNESS));
    by89 = 1;
    for (putBIT (16, mGENERATExCHECK_ASSIGN_PARMxI, fixedToBit (16, from89));
         bitToFixed (getBIT (16, mGENERATExCHECK_ASSIGN_PARMxI)) <= to89;
         putBIT (16, mGENERATExCHECK_ASSIGN_PARMxI,
                 fixedToBit (16, bitToFixed (getBIT (
                                     16, mGENERATExCHECK_ASSIGN_PARMxI))
                                     + by89)))
      {
        // IF SYMP THEN (7952)
        if (1 & (bitToFixed (getBIT (1, mGENERATExCHECK_ASSIGN_PARMxSYMP))))
          // J = GETARRAYDIM(I, ARGLOC); (7953)
          {
            descriptor_t *bitRHS
                = (putBITp (8, mGETARRAYDIMxIX,
                            getBIT (16, mGENERATExCHECK_ASSIGN_PARMxI)),
                   putBITp (16, mGETARRAYDIMxOP1,
                            getBIT (16, mGENERATExCHECK_ASSIGN_PARMxARGLOC)),
                   GETARRAYDIM (0));
            putBIT (16, mGENERATExCHECK_ASSIGN_PARMxJ, bitRHS);
            bitRHS->inUse = 0;
          }
        // ELSE (7954)
        else
          // J = SF_RANGE(ARGLOC+I-1); (7955)
          {
            descriptor_t *bitRHS = getBIT (
                16,
                mGENERATExSF_RANGE
                    + 2
                          * xsubtract (
                              xadd (COREHALFWORD (
                                        mGENERATExCHECK_ASSIGN_PARMxARGLOC),
                                    COREHALFWORD (
                                        mGENERATExCHECK_ASSIGN_PARMxI)),
                              1));
            putBIT (16, mGENERATExCHECK_ASSIGN_PARMxJ, bitRHS);
            bitRHS->inUse = 0;
          }
        // K = GETARRAYDIM(I, ARGPOINT); (7956)
        {
          descriptor_t *bitRHS
              = (putBITp (8, mGETARRAYDIMxIX,
                          getBIT (16, mGENERATExCHECK_ASSIGN_PARMxI)),
                 putBITp (16, mGETARRAYDIMxOP1, getBIT (16, mARGPOINT)),
                 GETARRAYDIM (0));
          putBIT (16, mGENERATExCHECK_ASSIGN_PARMxK, bitRHS);
          bitRHS->inUse = 0;
        }
        // IF K ~< 0 THEN (7957)
        if (1 & (xGE (COREHALFWORD (mGENERATExCHECK_ASSIGN_PARMxK), 0)))
          // IF K ~= J THEN (7958)
          if (1
              & (xNEQ (COREHALFWORD (mGENERATExCHECK_ASSIGN_PARMxK),
                       COREHALFWORD (mGENERATExCHECK_ASSIGN_PARMxJ))))
            // IF CLASS=8 THEN (7959)
            if (1 & (xEQ (COREHALFWORD (mCLASS), 8)))
              // CALL ERRORS(CLASS_DI,110); (7960)
              {
                putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
                putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(110)));
                ERRORS (0);
              }
            // ELSE (7961)
            else
              // CALL ERRORS(CLASS_FD,102,''||ARGNO); (7962)
              {
                putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_FD));
                putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(102)));
                putCHARACTERp (mERRORSxTEXT,
                               xsCAT (cToDescriptor (NULL, ""),
                                      bitToCharacter (getBIT (16, mARGNO))));
                ERRORS (0);
              }
      }
  } // End of DO for-loop block
  // IF ARGTYPE >= ANY_LABEL THEN (7963)
  if (1 & (xGE (COREHALFWORD (mARGTYPE), BYTE0 (mANY_LABEL))))
    // RETURN; (7964)
    {
      reentryGuard = 0;
      return 0;
    }
  // IF PACKTYPE(ARGTYPE) = VECMAT THEN (7965)
  if (1
      & (xEQ (BYTE0 (mPACKTYPE + 1 * COREHALFWORD (mARGTYPE)),
              BYTE0 (mVECMAT))))
    // CALL CHECK_VM_ARG_DIMS; (7966)
    GENERATExCHECK_VM_ARG_DIMS (0);
  // ELSE (7967)
  else
    // IF PACKTYPE(ARGTYPE) = BITS THEN (7968)
    if (1
        & (xEQ (BYTE0 (mPACKTYPE + 1 * COREHALFWORD (mARGTYPE)),
                BYTE0 (mBITS))))
      // DO; (7969)
      {
      rs2:;
        // IF SIZE(RIGHTOP) ~= (SYT_DIMS(ARGPOINT)& 255) THEN (7970)
        if (1
            & (xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                   + 73 * (COREHALFWORD (mRIGHTOP)) + 48
                                   + 2 * (0)),
                     xAND (COREHALFWORD (getFIXED (mSYM_TAB)
                                         + 34 * (COREHALFWORD (mARGPOINT)) + 18
                                         + 2 * (0)),
                           255))))
          // DO; (7971)
          {
          rs2s1:;
            // IF CLASS=8 THEN (7972)
            if (1 & (xEQ (COREHALFWORD (mCLASS), 8)))
              // CALL ERRORS(CLASS_DI,108); (7973)
              {
                putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
                putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(108)));
                ERRORS (0);
              }
            // ELSE (7974)
            else
              // CALL ERRORS(CLASS_FT,101,''||ARGNO); (7975)
              {
                putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_FT));
                putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(101)));
                putCHARACTERp (mERRORSxTEXT,
                               xsCAT (cToDescriptor (NULL, ""),
                                      bitToCharacter (getBIT (16, mARGNO))));
                ERRORS (0);
              }
          es2s1:;
          } // End of DO block
        // ELSE (7976)
        else
          // IF SYMP & (SYT_FLAGS(ARGLOC) & DENSE_FLAG) ~= 0 THEN (7977)
          if (1
              & (xAND (
                  BYTE0 (mGENERATExCHECK_ASSIGN_PARMxSYMP),
                  xNEQ (
                      xAND (getFIXED (
                                getFIXED (mSYM_TAB)
                                + 34
                                      * (COREHALFWORD (
                                          mGENERATExCHECK_ASSIGN_PARMxARGLOC))
                                + 8 + 4 * (0)),
                            getFIXED (mDENSE_FLAG)),
                      0))))
            // CALL ERRORS(CLASS_FT,109); (7978)
            {
              putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_FT));
              putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(109)));
              ERRORS (0);
            }
      es2:;
      } // End of DO block
    // ELSE (7979)
    else
      // IF (CLASS=8) & (PACKTYPE(ARGTYPE))= CHAR THEN (7980)
      if (1
          & (xAND (xEQ (COREHALFWORD (mCLASS), 8),
                   xEQ (BYTE0 (mPACKTYPE + 1 * COREHALFWORD (mARGTYPE)),
                        BYTE0 (mCHAR)))))
        // DO; (7981)
        {
        rs3:;
          // IF (SIZE(RIGHTOP) ~= -1) &  (SYT_DIMS(ARGPOINT) ~= -1) THEN (7982)
          if (1
              & (xAND (xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                           + 73 * (COREHALFWORD (mRIGHTOP))
                                           + 48 + 2 * (0)),
                             -1),
                       xNEQ (COREHALFWORD (getFIXED (mSYM_TAB)
                                           + 34 * (COREHALFWORD (mARGPOINT))
                                           + 18 + 2 * (0)),
                             -1))))
            // DO; (7983)
            {
            rs3s1:;
              // IF SIZE(RIGHTOP)~=(SYT_DIMS(ARGPOINT)& 255) THEN (7984)
              if (1
                  & (xNEQ (
                      COREHALFWORD (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mRIGHTOP)) + 48
                                    + 2 * (0)),
                      xAND (COREHALFWORD (getFIXED (mSYM_TAB)
                                          + 34 * (COREHALFWORD (mARGPOINT))
                                          + 18 + 2 * (0)),
                            255))))
                // CALL ERRORS(CLASS_DI,108); (7985)
                {
                  putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
                  putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(108)));
                  ERRORS (0);
                }
            es3s1:;
            } // End of DO block
        es3:;
        } // End of DO block
      // ELSE (7986)
      else
        // IF (CLASS~=8) & (PACKTYPE(ARGTYPE)=CHAR) THEN (7987)
        if (1
            & (xAND (xNEQ (COREHALFWORD (mCLASS), 8),
                     xEQ (BYTE0 (mPACKTYPE + 1 * COREHALFWORD (mARGTYPE)),
                          BYTE0 (mCHAR)))))
          // DO; (7988)
          {
          rs4:;
            // IF (SYT_FLAGS(ARGPOINT) & NAME_FLAG) ~= 0 THEN (7989)
            if (1
                & (xNEQ (xAND (getFIXED (getFIXED (mSYM_TAB)
                                         + 34 * (COREHALFWORD (mARGPOINT)) + 8
                                         + 4 * (0)),
                               getFIXED (mNAME_FLAG)),
                         0)))
              // CALL ERRORS(CLASS_YF,104); (7990)
              {
                putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_YF));
                putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(104)));
                ERRORS (0);
              }
          es4:;
          } // End of DO block
  {
    reentryGuard = 0;
    return 0;
  }
}
