/*
  File GENERATExMAT_TEMP.c generated by XCOM-I, 2024-08-09 12:41:32.
*/

#include "runtimeC.h"

int32_t
GENERATExMAT_TEMP (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExMAT_TEMP");
  // IF VDLP_ACTIVE THEN (8900)
  if (1 & (bitToFixed (getBIT (1, mVDLP_ACTIVE))))
    // CALL MAT_EXPRESSION(OPCODE, (SHR(TAG,6)|COPT)&1); (8901)
    {
      putBITp (16, mGENERATExMAT_EXPRESSIONxOPCODE, getBIT (16, mOPCODE));
      putBITp (
          1, mGENERATExMAT_EXPRESSIONxTEMP,
          fixedToBit (
              32, (int32_t)(xAND (
                      xOR (SHR (COREHALFWORD (mTAG), 6), BYTE0 (mCOPT)), 1))));
      GENERATExMAT_EXPRESSION (0);
    }
  // ELSE (8902)
  else
    // DO; (8903)
    {
    rs1:;
      // IF CSE_FLAG | NO_VM_OPT THEN (8904)
      if (1 & (xOR (BYTE0 (mGENERATExCSE_FLAG), BYTE0 (mNO_VM_OPT))))
        // DO; (8905)
        {
        rs1s1:;
          // RESULT=GET_VM_TEMP; (8906)
          {
            descriptor_t *bitRHS = GENERATExGET_VM_TEMP (0);
            putBIT (16, mRESULT, bitRHS);
            bitRHS->inUse = 0;
          }
          // OK_TO_ASSIGN=FALSE; (8907)
          {
            int32_t numberRHS = (int32_t)(0);
            descriptor_t *bitRHS;
            bitRHS = fixedToBit (32, (int32_t)(numberRHS));
            putBIT (1, mGENERATExOK_TO_ASSIGN, bitRHS);
            bitRHS->inUse = 0;
          }
          // GO TO MAT_CALL; (8908)
          goto MAT_CALL;
        es1s1:;
        } // End of DO block
      // IF RETURN_EXP_OR_FN(CTR) THEN (8909)
      if (1
          & (bitToFixed (
              (putBITp (16, mGENERATExRETURN_EXP_OR_FNxPTR, getBIT (16, mCTR)),
               GENERATExRETURN_EXP_OR_FN (0)))))
        // DO; (8910)
        {
        rs1s2:;
          // OK_TO_ASSIGN=TRUE; (8911)
          {
            int32_t numberRHS = (int32_t)(1);
            descriptor_t *bitRHS;
            bitRHS = fixedToBit (32, (int32_t)(numberRHS));
            putBIT (1, mGENERATExOK_TO_ASSIGN, bitRHS);
            bitRHS->inUse = 0;
          }
          // GO TO MAT_CALL; (8912)
          goto MAT_CALL;
        es1s2:;
        } // End of DO block
      // CALL CHECK_ASSIGN(CTR); (8913)
      {
        putBITp (16, mGENERATExCHECK_ASSIGNxPTR, getBIT (16, mCTR));
        GENERATExCHECK_ASSIGN (0);
      }
      // CALL NSEC_CHECK; (8914)
      GENERATExNSEC_CHECK (0);
      // IF OK_TO_ASSIGN THEN (8915)
      if (1 & (bitToFixed (getBIT (1, mGENERATExOK_TO_ASSIGN))))
        // DO; (8916)
        {
        rs1s3:;
          // IF (NONPART & CLASS3_OP) | CLASS1_OP THEN (8917)
          if (1
              & (xOR (xAND (BYTE0 (mGENERATExNONPART),
                            BYTE0 (mGENERATExCLASS3_OP)),
                      BYTE0 (mGENERATExCLASS1_OP))))
            // GO TO STACK_ENTRY_ASN; (8918)
            goto STACK_ENTRY_ASN;
          // ELSE (8919)
          else
            // IF (LEFT_NSEC & RIGHT_NSEC) THEN (8920)
            if (1
                & (xAND (BYTE0 (mGENERATExLEFT_NSEC),
                         BYTE0 (mGENERATExRIGHT_NSEC))))
              // GO TO STACK_ENTRY_ASN; (8921)
              goto STACK_ENTRY_ASN;
            // ELSE (8922)
            else
              // DO; (8923)
              {
              rs1s3s1:;
                // CALL IDENT_DISJOINT_CHECK(LEFTOP,1); (8924)
                {
                  putBITp (16, mGENERATExIDENT_DISJOINT_CHECKxOP,
                           getBIT (16, mLEFTOP));
                  putBITp (16, mGENERATExIDENT_DISJOINT_CHECKxN,
                           fixedToBit (32, (int32_t)(1)));
                  GENERATExIDENT_DISJOINT_CHECK (0);
                }
                // CALL IDENT_DISJOINT_CHECK(RIGHTOP,2); (8925)
                {
                  putBITp (16, mGENERATExIDENT_DISJOINT_CHECKxOP,
                           getBIT (16, mRIGHTOP));
                  putBITp (16, mGENERATExIDENT_DISJOINT_CHECKxN,
                           fixedToBit (32, (int32_t)(2)));
                  GENERATExIDENT_DISJOINT_CHECK (0);
                }
                // IF (LNON_IDENT & RNON_IDENT) THEN (8926)
                if (1
                    & (xAND (BYTE0 (mGENERATExLNON_IDENT),
                             BYTE0 (mGENERATExRNON_IDENT))))
                  // GO TO STACK_ENTRY_ASN; (8927)
                  goto STACK_ENTRY_ASN;
              es1s3s1:;
              } // End of DO block
          // IF ALL_FAILS THEN (8928)
          if (1 & (bitToFixed (getBIT (1, mGENERATExALL_FAILS))))
            // IF (LEFT_DISJOINT & RIGHT_DISJOINT) THEN (8929)
            if (1
                & (xAND (BYTE0 (mGENERATExLEFT_DISJOINT),
                         BYTE0 (mGENERATExRIGHT_DISJOINT))))
              // DO; (8930)
              {
              rs1s3s2:;
              // STACK_ENTRY_ASN: (8931)
              STACK_ENTRY_ASN:
                // ALL_FAILS=FALSE; (8932)
                {
                  int32_t numberRHS = (int32_t)(0);
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (1, mGENERATExALL_FAILS, bitRHS);
                  bitRHS->inUse = 0;
                }
                // CTR=ASNCTR; (8933)
                {
                  descriptor_t *bitRHS = getBIT (16, mASNCTR);
                  putBIT (16, mCTR, bitRHS);
                  bitRHS->inUse = 0;
                }
                // CALL AUX_SYNC(CTR); (8934)
                {
                  putBITp (16, mAUX_SYNCxCTR, getBIT (16, mCTR));
                  AUX_SYNC (0);
                }
                // RESULT=GET_OPERAND(2); (8935)
                {
                  descriptor_t *bitRHS
                      = (putBITp (16, mGENERATExGET_OPERANDxOP,
                                  fixedToBit (32, (int32_t)(2))),
                         GENERATExGET_OPERAND (0));
                  putBIT (16, mRESULT, bitRHS);
                  bitRHS->inUse = 0;
                }
                // CALL ASSIGN_CLEAR(RESULT, 1); (8936)
                {
                  putBITp (16, mGENERATExASSIGN_CLEARxOP,
                           getBIT (16, mRESULT));
                  putBITp (1, mGENERATExASSIGN_CLEARxFLAG,
                           fixedToBit (32, (int32_t)(1)));
                  GENERATExASSIGN_CLEAR (0);
                }
                // OK_TO_ASSIGN=TRUE; (8937)
                {
                  int32_t numberRHS = (int32_t)(1);
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (1, mGENERATExOK_TO_ASSIGN, bitRHS);
                  bitRHS->inUse = 0;
                }
              es1s3s2:;
              } // End of DO block
          // IF ALL_FAILS THEN (8938)
          if (1 & (bitToFixed (getBIT (1, mGENERATExALL_FAILS))))
            // GO TO TEMP_ASN; (8939)
            goto TEMP_ASN;
        es1s3:;
        } // End of DO block
      // ELSE (8940)
      else
        // DO; (8941)
        {
        rs1s4:;
        // TEMP_ASN: (8942)
        TEMP_ASN:
          // RESULT=GET_VM_TEMP; (8943)
          {
            descriptor_t *bitRHS = GENERATExGET_VM_TEMP (0);
            putBIT (16, mRESULT, bitRHS);
            bitRHS->inUse = 0;
          }
          // OK_TO_ASSIGN=FALSE; (8944)
          {
            int32_t numberRHS = (int32_t)(0);
            descriptor_t *bitRHS;
            bitRHS = fixedToBit (32, (int32_t)(numberRHS));
            putBIT (1, mGENERATExOK_TO_ASSIGN, bitRHS);
            bitRHS->inUse = 0;
          }
        es1s4:;
        } // End of DO block
    // MAT_CALL: (8945)
    MAT_CALL:
      // CALL VMCALL(OPCODE,(OPTYPE&8)~=0,RESULT,LEFTOP,RIGHTOP,0); (8946)
      {
        putBITp (16, mGENERATExVMCALLxOPCODE, getBIT (16, mOPCODE));
        putBITp (8, mGENERATExVMCALLxOPTYPE,
                 fixedToBit (32, (int32_t)(xNEQ (
                                     xAND (COREHALFWORD (mOPTYPE), 8), 0))));
        putBITp (16, mGENERATExVMCALLxOP0, getBIT (16, mRESULT));
        putBITp (16, mGENERATExVMCALLxOP1, getBIT (16, mLEFTOP));
        putBITp (16, mGENERATExVMCALLxOP2, getBIT (16, mRIGHTOP));
        putFIXED (mGENERATExVMCALLxPART, 0);
        GENERATExVMCALL (0);
      }
      // CALL RETURN_STACK_ENTRIES(LEFTOP,RIGHTOP); (8947)
      {
        putBITp (16, mGENERATExRETURN_STACK_ENTRIESxPTR1,
                 getBIT (16, mLEFTOP));
        putBITp (16, mGENERATExRETURN_STACK_ENTRIESxPTR2,
                 getBIT (16, mRIGHTOP));
        GENERATExRETURN_STACK_ENTRIES (0);
      }
      // IF OK_TO_ASSIGN THEN (8948)
      if (1 & (bitToFixed (getBIT (1, mGENERATExOK_TO_ASSIGN))))
        // CALL RETURN_STACK_ENTRY(RESULT); (8949)
        {
          putBITp (16, mGENERATExRETURN_STACK_ENTRYxP, getBIT (16, mRESULT));
          GENERATExRETURN_STACK_ENTRY (0);
        }
      // ELSE (8950)
      else
        // LASTRESULT = RESULT; (8951)
        {
          descriptor_t *bitRHS = getBIT (16, mRESULT);
          putBIT (16, mLASTRESULT, bitRHS);
          bitRHS->inUse = 0;
        }
    es1:;
    } // End of DO block
  // CLASS3_OP,CLASS1_OP=FALSE; (8952)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExCLASS3_OP, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (1, mGENERATExCLASS1_OP, bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
