/*
  File GENERATExGEN_CLASS6.c generated by XCOM-I, 2024-08-09 12:41:32.
*/

#include "runtimeC.h"

int32_t
GENERATExGEN_CLASS6 (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExGEN_CLASS6");
// CLASS6: (13005)
CLASS6:
  // DO; (13006)
  {
  rs1:;
    // DO CASE SUBCODE; (13007)
    {
    rs1s1:
      switch (COREHALFWORD (mSUBCODE))
        {
        case 0:
          // DO; (13009)
          {
          rs1s1s1:;
            // CALL DO_ASSIGNMENT; (13009)
            GENERATExDO_ASSIGNMENT (0);
          es1s1s1:;
          } // End of DO block
          break;
        case 1:
          // DO; (13011)
          {
          rs1s1s2:;
            // LITTYPE = BITS; (13011)
            {
              descriptor_t *bitRHS = getBIT (8, mBITS);
              putBIT (16, mLITTYPE, bitRHS);
              bitRHS->inUse = 0;
            }
            // LEFTOP = GET_OPERAND(1); (13012)
            {
              descriptor_t *bitRHS = (putBITp (16, mGENERATExGET_OPERANDxOP,
                                               fixedToBit (32, (int32_t)(1))),
                                      GENERATExGET_OPERAND (0));
              putBIT (16, mLEFTOP, bitRHS);
              bitRHS->inUse = 0;
            }
            // IF FORM(LEFTOP) ~= LIT  | (LOC(LEFTOP)<0 & VAL(LEFTOP) ~=0) THEN
            // (13013)
            if (1
                & (xOR (
                    xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                        + 73 * (COREHALFWORD (mLEFTOP)) + 32
                                        + 2 * (0)),
                          BYTE0 (mLIT)),
                    xAND (xLT (COREHALFWORD (getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mLEFTOP))
                                             + 40 + 2 * (0)),
                               0),
                          xNEQ (getFIXED (getFIXED (mIND_STACK)
                                          + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                          + 4 * (0)),
                                0)))))
              // CALL FORCE_ACCUMULATOR(LEFTOP, NEWPREC(TAG) | INTEGER);
              // (13014)
              {
                putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                         getBIT (16, mLEFTOP));
                putBITp (16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
                         fixedToBit (
                             32, (int32_t)(xOR (
                                     COREHALFWORD (mGENERATExNEWPREC
                                                   + 2 * COREHALFWORD (mTAG)),
                                     BYTE0 (mINTEGER)))));
                GENERATExFORCE_ACCUMULATOR (0);
              }
            // ELSE (13015)
            else
              // DO; (13016)
              {
              rs1s1s2s1:;
                // IF ((TYPE(LEFTOP)&8)=8) & NEWPREC(TAG)=0 THEN (13017)
                if (1
                    & (xAND (xEQ (xAND (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 50 + 2 * (0)),
                                        8),
                                  8),
                             xEQ (COREHALFWORD (mGENERATExNEWPREC
                                                + 2 * COREHALFWORD (mTAG)),
                                  0))))
                  // DO; (13018)
                  {
                  rs1s1s2s1s1:;
                    // VAL(LEFTOP) = VAL(LEFTOP) &  65535; (13019)
                    {
                      int32_t numberRHS = (int32_t)(xAND (
                          getFIXED (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                    + 4 * (0)),
                          65535));
                      putFIXED (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                    + 4 * (0),
                                numberRHS);
                    }
                    // IF (VAL(LEFTOP)& 32768)= 32768 THEN (13020)
                    if (1
                        & (xEQ (xAND (getFIXED (getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 12 + 4 * (0)),
                                      32768),
                                32768)))
                      // VAL(LEFTOP) = VAL(LEFTOP) |  4294901760; (13021)
                      {
                        int32_t numberRHS = (int32_t)(xOR (
                            getFIXED (getFIXED (mIND_STACK)
                                      + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                      + 4 * (0)),
                            4294901760));
                        putFIXED (getFIXED (mIND_STACK)
                                      + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                      + 4 * (0),
                                  numberRHS);
                      }
                  es1s1s2s1s1:;
                  } // End of DO block
                // LOC(LEFTOP) = -1; (13022)
                {
                  int32_t numberRHS = (int32_t)(-1);
                  putBIT (16,
                          getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mLEFTOP))
                              + 40 + 2 * (0),
                          fixedToBit (16, numberRHS));
                }
              es1s1s2s1:;
              } // End of DO block
            // TYPE(LEFTOP) = NEWPREC(TAG) | INTEGER; (13023)
            {
              int32_t numberRHS = (int32_t)(xOR (
                  COREHALFWORD (mGENERATExNEWPREC + 2 * COREHALFWORD (mTAG)),
                  BYTE0 (mINTEGER)));
              putBIT (16,
                      getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mLEFTOP))
                          + 50 + 2 * (0),
                      fixedToBit (16, numberRHS));
            }
          es1s1s2:;
          } // End of DO block
          break;
        case 2:
          // DO; (13025)
          {
          rs1s1s3:;
            // LITTYPE = CHAR; (13025)
            {
              descriptor_t *bitRHS = getBIT (8, mCHAR);
              putBIT (16, mLITTYPE, bitRHS);
              bitRHS->inUse = 0;
            }
            // LEFTOP = CTON(GET_OPERAND(1), NEWPREC(TAG)|INTEGER); (13026)
            {
              descriptor_t *bitRHS
                  = (putBITp (16, mGENERATExCTONxOP,
                              (putBITp (16, mGENERATExGET_OPERANDxOP,
                                        fixedToBit (32, (int32_t)(1))),
                               GENERATExGET_OPERAND (0))),
                     putBITp (
                         16, mGENERATExCTONxOPTYPE,
                         fixedToBit (
                             32, (int32_t)(xOR (
                                     COREHALFWORD (mGENERATExNEWPREC
                                                   + 2 * COREHALFWORD (mTAG)),
                                     BYTE0 (mINTEGER))))),
                     GENERATExCTON (0));
              putBIT (16, mLEFTOP, bitRHS);
              bitRHS->inUse = 0;
            }
          es1s1s3:;
          } // End of DO block
          break;
        case 3:
            // ; (13028)
            ;
          break;
        case 4:
            // ; (13029)
            ;
          break;
        case 5:
          // DO; (13030)
          {
          rs1s1s4:;
            // LITTYPE = NEWPREC(TAG) | INTEGER; (13030)
            {
              int32_t numberRHS = (int32_t)(xOR (
                  COREHALFWORD (mGENERATExNEWPREC + 2 * COREHALFWORD (mTAG)),
                  BYTE0 (mINTEGER)));
              descriptor_t *bitRHS;
              bitRHS = fixedToBit (32, (int32_t)(numberRHS));
              putBIT (16, mLITTYPE, bitRHS);
              bitRHS->inUse = 0;
            }
            // LEFTOP=GET_OPERAND(1); (13031)
            {
              descriptor_t *bitRHS = (putBITp (16, mGENERATExGET_OPERANDxOP,
                                               fixedToBit (32, (int32_t)(1))),
                                      GENERATExGET_OPERAND (0));
              putBIT (16, mLEFTOP, bitRHS);
              bitRHS->inUse = 0;
            }
            // IF FORM(LEFTOP) ~= LIT | LOC(LEFTOP) < 0 THEN (13032)
            if (1
                & (xOR (xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 32 + 2 * (0)),
                              BYTE0 (mLIT)),
                        xLT (COREHALFWORD (getFIXED (mIND_STACK)
                                           + 73 * (COREHALFWORD (mLEFTOP)) + 40
                                           + 2 * (0)),
                             0))))
              // CALL FORCE_BY_MODE(LEFTOP, NEWPREC(TAG)|INTEGER); (13033)
              {
                putBITp (16, mGENERATExFORCE_BY_MODExOP, getBIT (16, mLEFTOP));
                putBITp (16, mGENERATExFORCE_BY_MODExMODE,
                         fixedToBit (
                             32, (int32_t)(xOR (
                                     COREHALFWORD (mGENERATExNEWPREC
                                                   + 2 * COREHALFWORD (mTAG)),
                                     BYTE0 (mINTEGER)))));
                GENERATExFORCE_BY_MODE (0);
              }
            // ELSE (13034)
            else
              // DO; (13035)
              {
              rs1s1s4s1:;
                // IF TAG1 ~= LIT THEN (13036)
                if (1 & (xNEQ (COREHALFWORD (mTAG1), BYTE0 (mLIT))))
                  // CALL LITERAL(LOC(LEFTOP),NEWPREC(TAG)|INTEGER,LEFTOP);
                  // (13037)
                  {
                    putBITp (16, mGENERATExLITERALxPTR,
                             getBIT (16, getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mLEFTOP))
                                             + 40 + 2 * (0)));
                    putBITp (
                        16, mGENERATExLITERALxLTYPE,
                        fixedToBit (
                            32, (int32_t)(xOR (
                                    COREHALFWORD (mGENERATExNEWPREC
                                                  + 2 * COREHALFWORD (mTAG)),
                                    BYTE0 (mINTEGER)))));
                    putBITp (16, mGENERATExLITERALxSTACK,
                             getBIT (16, mLEFTOP));
                    GENERATExLITERAL (0);
                  }
                // IF ((TYPE(LEFTOP)&8)=8) & TAG=1 THEN (13038)
                if (1
                    & (xAND (xEQ (xAND (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 50 + 2 * (0)),
                                        8),
                                  8),
                             xEQ (COREHALFWORD (mTAG), 1))))
                  // DO; (13039)
                  {
                  rs1s1s4s1s1:;
                    // VAL(LEFTOP) = VAL(LEFTOP) &  65535; (13040)
                    {
                      int32_t numberRHS = (int32_t)(xAND (
                          getFIXED (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                    + 4 * (0)),
                          65535));
                      putFIXED (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                    + 4 * (0),
                                numberRHS);
                    }
                    // IF (VAL(LEFTOP)& 32768)= 32768 THEN (13041)
                    if (1
                        & (xEQ (xAND (getFIXED (getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 12 + 4 * (0)),
                                      32768),
                                32768)))
                      // VAL(LEFTOP) = VAL(LEFTOP) |  4294901760; (13042)
                      {
                        int32_t numberRHS = (int32_t)(xOR (
                            getFIXED (getFIXED (mIND_STACK)
                                      + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                      + 4 * (0)),
                            4294901760));
                        putFIXED (getFIXED (mIND_STACK)
                                      + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                      + 4 * (0),
                                  numberRHS);
                      }
                    // TYPE(LEFTOP) = INTEGER; (13043)
                    {
                      descriptor_t *bitRHS = getBIT (8, mINTEGER);
                      putBIT (16,
                              getFIXED (mIND_STACK)
                                  + 73 * (COREHALFWORD (mLEFTOP)) + 50
                                  + 2 * (0),
                              bitRHS);
                      bitRHS->inUse = 0;
                    }
                  es1s1s4s1s1:;
                  } // End of DO block
                // LOC(LEFTOP) = -1; (13044)
                {
                  int32_t numberRHS = (int32_t)(-1);
                  putBIT (16,
                          getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mLEFTOP))
                              + 40 + 2 * (0),
                          fixedToBit (16, numberRHS));
                }
              es1s1s4s1:;
              } // End of DO block
          es1s1s4:;
          } // End of DO block
          break;
        case 6:
          // DO; (13046)
          {
          rs1s1s5:;
            // IF OPCODE = XXASN THEN (13046)
            if (1 & (xEQ (COREHALFWORD (mOPCODE), BYTE0 (mXXASN))))
              // DO; (13047)
              {
              rs1s1s5s1:;
                // LITTYPE = NEWPREC(TAG) | INTEGER; (13048)
                {
                  int32_t numberRHS = (int32_t)(xOR (
                      COREHALFWORD (mGENERATExNEWPREC
                                    + 2 * COREHALFWORD (mTAG)),
                      BYTE0 (mINTEGER)));
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (16, mLITTYPE, bitRHS);
                  bitRHS->inUse = 0;
                }
                // CALL GET_OPERANDS; (13049)
                GENERATExGET_OPERANDS (0);
                // IF FORM(LEFTOP) = LIT THEN (13050)
                if (1
                    & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                          + 73 * (COREHALFWORD (mLEFTOP)) + 32
                                          + 2 * (0)),
                            BYTE0 (mLIT))))
                  // DO; (13051)
                  {
                  rs1s1s5s1s1:;
                    // IF ((TYPE(LEFTOP)&8)=8) & TAG=1 THEN (13052)
                    if (1
                        & (xAND (xEQ (xAND (COREHALFWORD (
                                                getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 50 + 2 * (0)),
                                            8),
                                      8),
                                 xEQ (COREHALFWORD (mTAG), 1))))
                      // DO; (13053)
                      {
                      rs1s1s5s1s1s1:;
                        // VAL(LEFTOP) = VAL(LEFTOP) &  65535; (13054)
                        {
                          int32_t numberRHS = (int32_t)(xAND (
                              getFIXED (getFIXED (mIND_STACK)
                                        + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                        + 4 * (0)),
                              65535));
                          putFIXED (getFIXED (mIND_STACK)
                                        + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                        + 4 * (0),
                                    numberRHS);
                        }
                        // IF (VAL(LEFTOP)& 32768)= 32768 THEN (13055)
                        if (1
                            & (xEQ (
                                xAND (getFIXED (getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 12 + 4 * (0)),
                                      32768),
                                32768)))
                          // VAL(LEFTOP) = VAL(LEFTOP) |  4294901760; (13056)
                          {
                            int32_t numberRHS = (int32_t)(xOR (
                                getFIXED (getFIXED (mIND_STACK)
                                          + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                          + 4 * (0)),
                                4294901760));
                            putFIXED (getFIXED (mIND_STACK)
                                          + 73 * (COREHALFWORD (mLEFTOP)) + 12
                                          + 4 * (0),
                                      numberRHS);
                          }
                        // LOC(LEFTOP) = -1; (13057)
                        {
                          int32_t numberRHS = (int32_t)(-1);
                          putBIT (16,
                                  getFIXED (mIND_STACK)
                                      + 73 * (COREHALFWORD (mLEFTOP)) + 40
                                      + 2 * (0),
                                  fixedToBit (16, numberRHS));
                        }
                      es1s1s5s1s1s1:;
                      } // End of DO block
                    // TYPE(LEFTOP) = NEWPREC(TAG) | INTEGER; (13058)
                    {
                      int32_t numberRHS = (int32_t)(xOR (
                          COREHALFWORD (mGENERATExNEWPREC
                                        + 2 * COREHALFWORD (mTAG)),
                          BYTE0 (mINTEGER)));
                      putBIT (16,
                              getFIXED (mIND_STACK)
                                  + 73 * (COREHALFWORD (mLEFTOP)) + 50
                                  + 2 * (0),
                              fixedToBit (16, numberRHS));
                    }
                  es1s1s5s1s1:;
                  } // End of DO block
                // ELSE (13059)
                else
                  // IF TYPE(LEFTOP) ~= LITTYPE THEN (13060)
                  if (1
                      & (xNEQ (COREHALFWORD (getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mLEFTOP))
                                             + 50 + 2 * (0)),
                               COREHALFWORD (mLITTYPE))))
                    // CALL FORCE_ACCUMULATOR(LEFTOP, LITTYPE); (13061)
                    {
                      putBITp (16, mGENERATExFORCE_ACCUMULATORxOP,
                               getBIT (16, mLEFTOP));
                      putBITp (16, mGENERATExFORCE_ACCUMULATORxOPTYPE,
                               getBIT (16, mLITTYPE));
                      GENERATExFORCE_ACCUMULATOR (0);
                    }
              es1s1s5s1:;
              } // End of DO block
            // ELSE (13062)
            else
              // DO CASE OPCODE - XADD; (13063)
              {
              rs1s1s5s2:
                switch (xsubtract (COREHALFWORD (mOPCODE), BYTE0 (mXADD)))
                  {
                  case 0:
                    // DO; (13065)
                    {
                    rs1s1s5s2s1:;
                      // CALL GET_OPERANDS; (13065)
                      GENERATExGET_OPERANDS (0);
                      // IF FORM(RIGHTOP) = LIT &  ~CSE_FLAG THEN (13066)
                      if (1
                          & (xAND (xEQ (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 32 + 2 * (0)),
                                        BYTE0 (mLIT)),
                                   xNOT (BYTE0 (mGENERATExCSE_FLAG)))))
                        // DO ; (13067)
                        {
                        rs1s1s5s2s1s1:;
                          // IF FORM(LEFTOP) = LIT THEN (13068)
                          if (1
                              & (xEQ (
                                  COREHALFWORD (getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 32 + 2 * (0)),
                                  BYTE0 (mLIT))))
                            // DO; (13069)
                            {
                            rs1s1s5s2s1s1s1:;
                              // VAL(LEFTOP) = VAL(LEFTOP) + VAL(RIGHTOP);
                              // (13070)
                              {
                                int32_t numberRHS = (int32_t)(xadd (
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0)),
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 12 + 4 * (0))));
                                putFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0),
                                          numberRHS);
                              }
                              // LOC(LEFTOP) = -1; (13071)
                              {
                                int32_t numberRHS = (int32_t)(-1);
                                putBIT (16,
                                        getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 40 + 2 * (0),
                                        fixedToBit (16, numberRHS));
                              }
                            es1s1s5s2s1s1s1:;
                            } // End of DO block
                          // ELSE (13072)
                          else
                            // CONST(LEFTOP) = CONST(LEFTOP) + VAL(RIGHTOP);
                            // (13073)
                            {
                              int32_t numberRHS = (int32_t)(xadd (
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0)),
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 12 + 4 * (0))));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0),
                                        numberRHS);
                            }
                          // CALL RETURN_STACK_ENTRY(RIGHTOP); (13074)
                          {
                            putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                                     getBIT (16, mRIGHTOP));
                            GENERATExRETURN_STACK_ENTRY (0);
                          }
                        es1s1s5s2s1s1:;
                        } // End of DO block
                      // ELSE (13075)
                      else
                        // IF FORM(LEFTOP) = LIT &  ~CSE_FLAG THEN (13076)
                        if (1
                            & (xAND (xEQ (COREHALFWORD (
                                              getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 32 + 2 * (0)),
                                          BYTE0 (mLIT)),
                                     xNOT (BYTE0 (mGENERATExCSE_FLAG)))))
                          // DO ; (13077)
                          {
                          rs1s1s5s2s1s2:;
                            // CONST(RIGHTOP) = CONST(RIGHTOP) + VAL(LEFTOP);
                            // (13078)
                            {
                              int32_t numberRHS = (int32_t)(xadd (
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0)),
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 12 + 4 * (0))));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0),
                                        numberRHS);
                            }
                            // CALL COMMUTEM; (13079)
                            GENERATExCOMMUTEM (0);
                            // CALL RETURN_STACK_ENTRY(RIGHTOP); (13080)
                            {
                              putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                                       getBIT (16, mRIGHTOP));
                              GENERATExRETURN_STACK_ENTRY (0);
                            }
                          es1s1s5s2s1s2:;
                          } // End of DO block
                        // ELSE (13081)
                        else
                          // DO; (13082)
                          {
                          rs1s1s5s2s1s3:;
                            // CONST(LEFTOP) = CONST(LEFTOP) + CONST(RIGHTOP);
                            // (13083)
                            {
                              int32_t numberRHS = (int32_t)(xadd (
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0)),
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0))));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0),
                                        numberRHS);
                            }
                            // CONST(RIGHTOP) = 0; (13084)
                            {
                              int32_t numberRHS = (int32_t)(0);
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0),
                                        numberRHS);
                            }
                            // CALL EXPRESSION(OPCODE); (13085)
                            {
                              putBITp (16, mGENERATExEXPRESSIONxOPCODE,
                                       getBIT (16, mOPCODE));
                              GENERATExEXPRESSION (0);
                            }
                          es1s1s5s2s1s3:;
                          } // End of DO block
                    es1s1s5s2s1:;
                    } // End of DO block
                    break;
                  case 1:
                    // DO; (13087)
                    {
                    rs1s1s5s2s2:;
                      // CALL GET_OPERANDS; (13087)
                      GENERATExGET_OPERANDS (0);
                      // IF FORM(RIGHTOP) = LIT & ~CSE_FLAG THEN (13088)
                      if (1
                          & (xAND (xEQ (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 32 + 2 * (0)),
                                        BYTE0 (mLIT)),
                                   xNOT (BYTE0 (mGENERATExCSE_FLAG)))))
                        // DO; (13089)
                        {
                        rs1s1s5s2s2s1:;
                          // IF FORM(LEFTOP) = LIT THEN (13090)
                          if (1
                              & (xEQ (
                                  COREHALFWORD (getFIXED (mIND_STACK)
                                                + 73 * (COREHALFWORD (mLEFTOP))
                                                + 32 + 2 * (0)),
                                  BYTE0 (mLIT))))
                            // DO; (13091)
                            {
                            rs1s1s5s2s2s1s1:;
                              // VAL(LEFTOP) = VAL(LEFTOP) - VAL(RIGHTOP);
                              // (13092)
                              {
                                int32_t numberRHS = (int32_t)(xsubtract (
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0)),
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 12 + 4 * (0))));
                                putFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0),
                                          numberRHS);
                              }
                              // LOC(LEFTOP) = -1; (13093)
                              {
                                int32_t numberRHS = (int32_t)(-1);
                                putBIT (16,
                                        getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 40 + 2 * (0),
                                        fixedToBit (16, numberRHS));
                              }
                            es1s1s5s2s2s1s1:;
                            } // End of DO block
                          // ELSE (13094)
                          else
                            // CONST(LEFTOP) = CONST(LEFTOP) - VAL(RIGHTOP);
                            // (13095)
                            {
                              int32_t numberRHS = (int32_t)(xsubtract (
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0)),
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 12 + 4 * (0))));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0),
                                        numberRHS);
                            }
                          // CALL RETURN_STACK_ENTRY(RIGHTOP); (13096)
                          {
                            putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                                     getBIT (16, mRIGHTOP));
                            GENERATExRETURN_STACK_ENTRY (0);
                          }
                        es1s1s5s2s2s1:;
                        } // End of DO block
                      // ELSE (13097)
                      else
                        // IF FORM(LEFTOP) = LIT &  FORM(RIGHTOP) = VAC &
                        // ~CSE_FLAG THEN (13098)
                        if (1
                            & (xAND (
                                xAND (xEQ (COREHALFWORD (
                                               getFIXED (mIND_STACK)
                                               + 73 * (COREHALFWORD (mLEFTOP))
                                               + 32 + 2 * (0)),
                                           BYTE0 (mLIT)),
                                      xEQ (COREHALFWORD (
                                               getFIXED (mIND_STACK)
                                               + 73 * (COREHALFWORD (mRIGHTOP))
                                               + 32 + 2 * (0)),
                                           BYTE0 (mVAC))),
                                xNOT (BYTE0 (mGENERATExCSE_FLAG)))))
                          // DO ; (13099)
                          {
                          rs1s1s5s2s2s2:;
                            // VAL(LEFTOP) = VAL(LEFTOP) - CONST(RIGHTOP);
                            // (13100)
                            {
                              int32_t numberRHS = (int32_t)(xsubtract (
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 12 + 4 * (0)),
                                  getFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0))));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 12 + 4 * (0),
                                        numberRHS);
                            }
                            // CONST(RIGHTOP) = 0; (13101)
                            {
                              int32_t numberRHS = (int32_t)(0);
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0),
                                        numberRHS);
                            }
                            // CALL COMMUTEM; (13102)
                            GENERATExCOMMUTEM (0);
                            // CALL UNARYOP(PREFIXMINUS); (13103)
                            {
                              putBITp (16, mGENERATExUNARYOPxOPCODE,
                                       getBIT (8, mGENERATExPREFIXMINUS));
                              GENERATExUNARYOP (0);
                            }
                            // CONST(LEFTOP) = VAL(RIGHTOP); (13104)
                            {
                              int32_t numberRHS = (int32_t)(getFIXED (
                                  getFIXED (mIND_STACK)
                                  + 73 * (COREHALFWORD (mRIGHTOP)) + 12
                                  + 4 * (0)));
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP)) + 0
                                            + 4 * (0),
                                        numberRHS);
                            }
                            // CALL RETURN_STACK_ENTRY(RIGHTOP); (13105)
                            {
                              putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
                                       getBIT (16, mRIGHTOP));
                              GENERATExRETURN_STACK_ENTRY (0);
                            }
                          es1s1s5s2s2s2:;
                          } // End of DO block
                        // ELSE (13106)
                        else
                          // DO; (13107)
                          {
                          rs1s1s5s2s2s3:;
                            // IF FORM(LEFTOP) = LIT THEN (13108)
                            if (1
                                & (xEQ (COREHALFWORD (
                                            getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mLEFTOP))
                                            + 32 + 2 * (0)),
                                        BYTE0 (mLIT))))
                              // VAL(LEFTOP) = VAL(LEFTOP) - CONST(RIGHTOP);
                              // (13109)
                              {
                                int32_t numberRHS = (int32_t)(xsubtract (
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0)),
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 0 + 4 * (0))));
                                putFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 12 + 4 * (0),
                                          numberRHS);
                              }
                            // ELSE (13110)
                            else
                              // CONST(LEFTOP) = CONST(LEFTOP)-CONST(RIGHTOP);
                              // (13111)
                              {
                                int32_t numberRHS = (int32_t)(xsubtract (
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 0 + 4 * (0)),
                                    getFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 0 + 4 * (0))));
                                putFIXED (getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mLEFTOP))
                                              + 0 + 4 * (0),
                                          numberRHS);
                              }
                            // CONST(RIGHTOP) = 0; (13112)
                            {
                              int32_t numberRHS = (int32_t)(0);
                              putFIXED (getFIXED (mIND_STACK)
                                            + 73 * (COREHALFWORD (mRIGHTOP))
                                            + 0 + 4 * (0),
                                        numberRHS);
                            }
                            // CALL EXPRESSION(OPCODE); (13113)
                            {
                              putBITp (16, mGENERATExEXPRESSIONxOPCODE,
                                       getBIT (16, mOPCODE));
                              GENERATExEXPRESSION (0);
                            }
                          es1s1s5s2s2s3:;
                          } // End of DO block
                    es1s1s5s2s2:;
                    } // End of DO block
                    break;
                  case 2:
                    // CALL INTEGER_MULTIPLY(OPCODE); (13115)
                    {
                      putBITp (16,
                               mGENERATExGEN_CLASS6xINTEGER_MULTIPLYxOPCODE,
                               getBIT (16, mOPCODE));
                      GENERATExGEN_CLASS6xINTEGER_MULTIPLY (0);
                    }
                    break;
                  case 3:
                    // CALL INTEGER_DIVIDE; (13116)
                    GENERATExINTEGER_DIVIDE (0);
                    break;
                  case 4:
                      // ; (13117)
                      ;
                    break;
                  case 5:
                    // CALL EVALUATE(OPCODE); (13118)
                    {
                      putBITp (16, mGENERATExEVALUATExOPCODE,
                               getBIT (16, mOPCODE));
                      GENERATExEVALUATE (0);
                    }
                    break;
                  case 6:
                      // ; (13119)
                      ;
                    break;
                  case 7:
                    // CALL EXPONENTIAL(OPCODE); (13120)
                    {
                      putBITp (16, mGENERATExEXPONENTIALxOPCODE,
                               getBIT (16, mOPCODE));
                      GENERATExEXPONENTIAL (0);
                    }
                    break;
                  }
              } // End of DO CASE block
          es1s1s5:;
          } // End of DO block
          break;
        }
    } // End of DO CASE block
    // CALL SETUP_VAC(LEFTOP); (13120)
    {
      putBITp (16, mGENERATExSETUP_VACxOP, getBIT (16, mLEFTOP));
      GENERATExSETUP_VAC (0);
    }
  es1:;
  } // End of DO block
  {
    reentryGuard = 0;
    return 0;
  }
}
