/*
  File GENERATExRETURN_STACK_ENTRIES.c generated by XCOM-I, 2024-08-09
  12:41:32.
*/

#include "runtimeC.h"

int32_t
GENERATExRETURN_STACK_ENTRIES (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExRETURN_STACK_ENTRIES");
  // CALL RETURN_STACK_ENTRY(PTR2); (2880)
  {
    putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
             getBIT (16, mGENERATExRETURN_STACK_ENTRIESxPTR2));
    GENERATExRETURN_STACK_ENTRY (0);
  }
  // CALL RETURN_STACK_ENTRY(PTR1); (2881)
  {
    putBITp (16, mGENERATExRETURN_STACK_ENTRYxP,
             getBIT (16, mGENERATExRETURN_STACK_ENTRIESxPTR1));
    GENERATExRETURN_STACK_ENTRY (0);
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
