/*
  File GENERATExCHOOSE_BASE.c generated by XCOM-I, 2024-08-08 04:34:25.
*/

#include "runtimeC.h"

descriptor_t *
GENERATExCHOOSE_BASE (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (descriptor_t *)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExCHOOSE_BASE");
  // IF TARGET_R >= 0 THEN (4385)
  if (1 & (xGE (COREHALFWORD (mTARGET_R), 0)))
    // RETURN GET_R(OP,TYPE_LOAD); (4386)
    {
      reentryGuard = 0;
      return (putBITp (16, mGENERATExGET_RxOP,
                       getBIT (16, mGENERATExCHOOSE_BASExOP)),
              putBITp (8, mGENERATExGET_RxTYPE_LOAD,
                       getBIT (8, mGENERATExCHOOSE_BASExTYPE_LOAD)),
              GENERATExGET_R (0));
    }
  // IF SPAREBASE ~= R3 THEN (4387)
  if (1 & (xNEQ (COREHALFWORD (mGENERATExCHOOSE_BASExSPAREBASE), BYTE0 (mR3))))
    // RETURN GET_R(OP,TYPE_LOAD); (4388)
    {
      reentryGuard = 0;
      return (putBITp (16, mGENERATExGET_RxOP,
                       getBIT (16, mGENERATExCHOOSE_BASExOP)),
              putBITp (8, mGENERATExGET_RxTYPE_LOAD,
                       getBIT (8, mGENERATExCHOOSE_BASExTYPE_LOAD)),
              GENERATExGET_R (0));
    }
  // IF USAGE(R3) <= 1 THEN (4389)
  if (1 & (xLE (COREHALFWORD (mUSAGE + 2 * BYTE0 (mR3)), 1)))
    // TARGET_R = R3; (4390)
    {
      descriptor_t *bitRHS = getBIT (8, mR3);
      putBIT (16, mTARGET_R, bitRHS);
      bitRHS->inUse = 0;
    }
  // ELSE (4391)
  else
    // IF USAGE(PTRARG1) <= 1 THEN (4392)
    if (1 & (xLE (COREHALFWORD (mUSAGE + 2 * BYTE0 (mPTRARG1)), 1)))
      // TARGET_R = PTRARG1; (4393)
      {
        descriptor_t *bitRHS = getBIT (8, mPTRARG1);
        putBIT (16, mTARGET_R, bitRHS);
        bitRHS->inUse = 0;
      }
    // ELSE (4394)
    else
      // IF SHR(USAGE(PTRARG1),1)<SHR(USAGE(R3),1) THEN (4395)
      if (1
          & (xLT (SHR (COREHALFWORD (mUSAGE + 2 * BYTE0 (mPTRARG1)), 1),
                  SHR (COREHALFWORD (mUSAGE + 2 * BYTE0 (mR3)), 1))))
        // TARGET_R=PTRARG1; (4396)
        {
          descriptor_t *bitRHS = getBIT (8, mPTRARG1);
          putBIT (16, mTARGET_R, bitRHS);
          bitRHS->inUse = 0;
        }
      // ELSE (4397)
      else
        // TARGET_R = R3; (4398)
        {
          descriptor_t *bitRHS = getBIT (8, mR3);
          putBIT (16, mTARGET_R, bitRHS);
          bitRHS->inUse = 0;
        }
  // R = GET_R(OP,TYPE_LOAD); (4399)
  {
    descriptor_t *bitRHS
        = (putBITp (16, mGENERATExGET_RxOP,
                    getBIT (16, mGENERATExCHOOSE_BASExOP)),
           putBITp (8, mGENERATExGET_RxTYPE_LOAD,
                    getBIT (8, mGENERATExCHOOSE_BASExTYPE_LOAD)),
           GENERATExGET_R (0));
    putBIT (16, mGENERATExCHOOSE_BASExR, bitRHS);
    bitRHS->inUse = 0;
  }
  // TARGET_R = -1; (4400)
  {
    int32_t numberRHS = (int32_t)(-1);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mTARGET_R, bitRHS);
    bitRHS->inUse = 0;
  }
  // RETURN R; (4401)
  {
    reentryGuard = 0;
    return getBIT (16, mGENERATExCHOOSE_BASExR);
  }
}
