/*
  File INITIALISExSET_BIT_TYPE.c generated by XCOM-I, 2024-08-09 12:41:32.
*/

#include "runtimeC.h"

int32_t
INITIALISExSET_BIT_TYPE (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "INITIALISExSET_BIT_TYPE");
  // IF OP1 > HALFWORDSIZE THEN (2086)
  if (1
      & (xGT (COREHALFWORD (mINITIALISExSET_BIT_TYPExOP1),
              BYTE0 (mHALFWORDSIZE))))
    // RETURN FULLBIT; (2087)
    {
      reentryGuard = 0;
      return BYTE0 (mFULLBIT);
    }
  // ELSE (2088)
  else
    // RETURN BITS; (2089)
    {
      reentryGuard = 0;
      return BYTE0 (mBITS);
    }
}
