/*
  File OBJECT_GENERATORxEMIT_END_CARD.c generated by XCOM-I, 2024-08-08
  04:34:25.
*/

#include "runtimeC.h"

int32_t
OBJECT_GENERATORxEMIT_END_CARD (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "OBJECT_GENERATORxEMIT_END_CARD");
  // RECORD_ID = END_CARD_ID; (15910)
  {
    int32_t numberRHS = (int32_t)(2324);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mOBJECT_GENERATORxCARD_IMAGE, bitRHS);
    bitRHS->inUse = 0;
  }
  // CARD_COUNT = CARD_COUNTER; (15911)
  {
    descriptor_t *bitRHS = getBIT (16, mOBJECT_GENERATORxCARD_COUNTER);
    putBIT (16, mOBJECT_GENERATORxCARD_IMAGE + 2 * (1), bitRHS);
    bitRHS->inUse = 0;
  }
  // COMPILER_ID = DESC(MONITOR(23)); (15912)
  {
    descriptor_t *stringRHS;
    stringRHS = MONITOR23 ();
    putCHARACTER (mOBJECT_GENERATORxEMIT_END_CARDxCOMPILER_ID, stringRHS);
    stringRHS->inUse = 0;
  }
  // CALL MOVE_CHARS('HAL/S BFC-', HAL_VERSION_NAME, 10); (15913)
  {
    putFIXED (mOBJECT_GENERATORxMOVE_CHARSxFROM_ADDR, 167764777);
    putFIXED (mOBJECT_GENERATORxMOVE_CHARSxTO_ADDR,
              ADDR (NULL, 0, "OBJECT_GENERATORxCARD_IMAGE", 2));
    putBITp (16, mOBJECT_GENERATORxMOVE_CHARSxBYTE_COUNT,
             fixedToBit (32, (int32_t)(10)));
    OBJECT_GENERATORxMOVE_CHARS (0);
  }
  // HAL_VERSION_ID = CTOI(SUBSTR(COMPILER_ID, LENGTH(COMPILER_ID) - 5));
  // (15914)
  {
    descriptor_t *bitRHS
        = (putCHARACTERp (
               mOBJECT_GENERATORxEMIT_END_CARDxCTOIxCHARS,
               SUBSTR2 (
                   getCHARACTER (mOBJECT_GENERATORxEMIT_END_CARDxCOMPILER_ID),
                   xsubtract (
                       LENGTH (getCHARACTER (
                           mOBJECT_GENERATORxEMIT_END_CARDxCOMPILER_ID)),
                       5))),
           OBJECT_GENERATORxEMIT_END_CARDxCTOI (0));
    putBIT (16, mOBJECT_GENERATORxCARD_IMAGE + 2 * (7), bitRHS);
    bitRHS->inUse = 0;
  }
  // CALL FORMAT_DATE_AND_TIME(DATE, TIME, TIME_OF_TRANSLATION); (15915)
  {
    putFIXED (mOBJECT_GENERATORxEMIT_END_CARDxFORMAT_DATE_AND_TIMExDATE_VALUE,
              DATE ());
    putFIXED (mOBJECT_GENERATORxEMIT_END_CARDxFORMAT_DATE_AND_TIMExTIME_VALUE,
              TIME ());
    putBITp (
        16,
        mOBJECT_GENERATORxEMIT_END_CARDxFORMAT_DATE_AND_TIMExCARD_IMAGE_LOCATION,
        fixedToBit (32, (int32_t)(8)));
    OBJECT_GENERATORxEMIT_END_CARDxFORMAT_DATE_AND_TIME (0);
  }
  // CALL MOVE_CHARS('RSB-XCOM-I', XPL_VERSION_NAME, 10); (15916)
  {
    putFIXED (mOBJECT_GENERATORxMOVE_CHARSxFROM_ADDR, 167764763);
    putFIXED (mOBJECT_GENERATORxMOVE_CHARSxTO_ADDR,
              ADDR (NULL, 0, "OBJECT_GENERATORxCARD_IMAGE", 11));
    putBITp (16, mOBJECT_GENERATORxMOVE_CHARSxBYTE_COUNT,
             fixedToBit (32, (int32_t)(10)));
    OBJECT_GENERATORxMOVE_CHARS (0);
  }
  // XPL_VERSION_ID = (XPL_COMPILER_VERSION(0) * 100); (15917)
  {
    int32_t numberRHS = (int32_t)(xmultiply (XPL_COMPILER_VERSION (0), 100));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mOBJECT_GENERATORxCARD_IMAGE + 2 * (16), bitRHS);
    bitRHS->inUse = 0;
  }
  // XPL_VERSION_ID = XPL_VERSION_ID + (XPL_COMPILER_VERSION(1) * 10); (15918)
  {
    int32_t numberRHS
        = (int32_t)(xadd (COREHALFWORD (mOBJECT_GENERATORxCARD_IMAGE + 2 * 16),
                          xmultiply (XPL_COMPILER_VERSION (1), 10)));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mOBJECT_GENERATORxCARD_IMAGE + 2 * (16), bitRHS);
    bitRHS->inUse = 0;
  }
  // CALL EMIT_CARD(1); (15919)
  {
    putBITp (1, mOBJECT_GENERATORxEMIT_CARDxFLUSH_SWITCH,
             fixedToBit (32, (int32_t)(1)));
    OBJECT_GENERATORxEMIT_CARD (0);
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
