/*
  File OBJECT_GENERATORxAHEADSET.c generated by XCOM-I, 2024-08-09 12:39:31.
*/

#include "runtimeC.h"

int32_t
OBJECT_GENERATORxAHEADSET (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "OBJECT_GENERATORxAHEADSET");
  // APAGE = N; (15390)
  {
    descriptor_t *bitRHS = getBIT (16, mOBJECT_GENERATORxAHEADSETxN);
    putBIT (16, mOBJECT_GENERATORxAPAGE, bitRHS);
    bitRHS->inUse = 0;
  }
  // OUTPUT(1) = AHEAD(N); (15391)
  {
    descriptor_t *stringRHS;
    stringRHS
        = getCHARACTER (mOBJECT_GENERATORxAHEAD
                        + 4 * COREHALFWORD (mOBJECT_GENERATORxAHEADSETxN));
    OUTPUT (1, stringRHS);
    stringRHS->inUse = 0;
  }
  // OUTPUT(1) = '1'; (15392)
  {
    descriptor_t *stringRHS;
    stringRHS = cToDescriptor (NULL, "1");
    OUTPUT (1, stringRHS);
    stringRHS->inUse = 0;
  }
  // ABSLIST_COUNT = LINE_LIM; (15393)
  {
    descriptor_t *bitRHS = getBIT (16, mOBJECT_GENERATORxLINE_LIM);
    putBIT (16, mOBJECT_GENERATORxABSLIST_COUNT, bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
