/*
  File OBJECT_CONDENSERxBRANCH_UPDATE.c generated by XCOM-I, 2024-08-09
  12:39:31.
*/

#include "runtimeC.h"

int32_t
OBJECT_CONDENSERxBRANCH_UPDATE (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "OBJECT_CONDENSERxBRANCH_UPDATE");
  // PTR = LASTBRANCH(CURRENT_ESDID); (14699)
  {
    descriptor_t *bitRHS
        = getBIT (16, mLASTBRANCH + 2 * getFIXED (mCURRENT_ESDID));
    putBIT (16, mOBJECT_CONDENSERxBRANCH_UPDATExPTR, bitRHS);
    bitRHS->inUse = 0;
  }
  // DO WHILE (PTR > 0) & (BRANCH_ADDR(PTR) > CURRENT_ADDRESS); (14700)
  while (
      1
      & (xAND (
          xGT (COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExPTR), 0),
          xGT (getFIXED (
                   getFIXED (mBRANCH_TBL)
                   + 14 * (COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExPTR))
                   + 4 + 4 * (0)),
               getFIXED (mWORKSEG + 4 * getFIXED (mCURRENT_ESDID))))))
    {
      // BRANCH_ADDR(PTR) = BRANCH_ADDR(PTR) - N; (14701)
      {
        int32_t numberRHS = (int32_t)(xsubtract (
            getFIXED (
                getFIXED (mBRANCH_TBL)
                + 14 * (COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExPTR)) + 4
                + 4 * (0)),
            COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExN)));
        putFIXED (
            getFIXED (mBRANCH_TBL)
                + 14 * (COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExPTR)) + 4
                + 4 * (0),
            numberRHS);
      }
      // PTR = BRANCH_BLINK(PTR); (14702)
      {
        descriptor_t *bitRHS = getBIT (
            16, getFIXED (mBRANCH_TBL)
                    + 14 * (COREHALFWORD (mOBJECT_CONDENSERxBRANCH_UPDATExPTR))
                    + 12 + 2 * (0));
        putBIT (16, mOBJECT_CONDENSERxBRANCH_UPDATExPTR, bitRHS);
        bitRHS->inUse = 0;
      }
    } // End of DO WHILE block
  {
    reentryGuard = 0;
    return 0;
  }
}
