# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Sunburst 37 / Shepatin 0.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2017-05-24 MAS	Created.
#             	2017-06-17 MAS	Added --early-sbank.
#             	2017-06-18 MAS	Added --pos-checksums.

BASENAME=Sunburst37

EXTRA_YAYUL_ARGS=--early-sbank --pos-checksums --honeywell

include ../Makefile.inc
