# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Sunburst 37 / Shepatin 0.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2017-05-24 MAS	Created.

BASENAME=Sunburst37

NO_BINSOURCE=yes

include ../Makefile.inc
