/*
  File DISP.c generated by XCOM-I, 2024-08-08 04:35:09.
*/

#include "runtimeC.h"

int32_t
DISP (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "DISP");
  // TEMP = VMEM_PAD_DISP(VMEM_OLD_NDX); (823)
  {
    descriptor_t *bitRHS
        = getBIT (16, mVMEM_PAD_DISP + 2 * COREHALFWORD (mVMEM_OLD_NDX));
    putBIT (16, mDISPxTEMP, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF (FLAGS&MODF) ~= 0 THEN (824)
  if (1 & (xNEQ (xAND (BYTE0 (mDISPxFLAGS), BYTE0 (mMODF)), 0)))
    // TEMP = TEMP| 16384; (825)
    {
      int32_t numberRHS = (int32_t)(xOR (COREHALFWORD (mDISPxTEMP), 16384));
      descriptor_t *bitRHS;
      bitRHS = fixedToBit (32, (int32_t)(numberRHS));
      putBIT (16, mDISPxTEMP, bitRHS);
      bitRHS->inUse = 0;
    }
  // IF (FLAGS&RESV) ~= 0 THEN (826)
  if (1 & (xNEQ (xAND (BYTE0 (mDISPxFLAGS), BYTE0 (mRESV)), 0)))
    // DO; (827)
    {
    rs1:;
      // TEMP = TEMP + 1; (828)
      {
        int32_t numberRHS = (int32_t)(xadd (COREHALFWORD (mDISPxTEMP), 1));
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mDISPxTEMP, bitRHS);
        bitRHS->inUse = 0;
      }
      // VMEM_RESV_CNT = VMEM_RESV_CNT + 1; (829)
      {
        int32_t numberRHS = (int32_t)(xadd (getFIXED (mVMEM_RESV_CNT), 1));
        putFIXED (mVMEM_RESV_CNT, numberRHS);
      }
    es1:;
    } // End of DO block
  // ELSE (830)
  else
    // IF (FLAGS&RELS) ~= 0 THEN (831)
    if (1 & (xNEQ (xAND (BYTE0 (mDISPxFLAGS), BYTE0 (mRELS)), 0)))
      // DO; (832)
      {
      rs2:;
        // TEMP = TEMP - 1; (833)
        {
          int32_t numberRHS
              = (int32_t)(xsubtract (COREHALFWORD (mDISPxTEMP), 1));
          descriptor_t *bitRHS;
          bitRHS = fixedToBit (32, (int32_t)(numberRHS));
          putBIT (16, mDISPxTEMP, bitRHS);
          bitRHS->inUse = 0;
        }
        // VMEM_RESV_CNT = VMEM_RESV_CNT - 1; (834)
        {
          int32_t numberRHS
              = (int32_t)(xsubtract (getFIXED (mVMEM_RESV_CNT), 1));
          putFIXED (mVMEM_RESV_CNT, numberRHS);
        }
      es2:;
      } // End of DO block
  // VMEM_PAD_DISP(VMEM_OLD_NDX) = TEMP; (835)
  {
    descriptor_t *bitRHS = getBIT (16, mDISPxTEMP);
    putBIT (16, mVMEM_PAD_DISP + 2 * (COREHALFWORD (mVMEM_OLD_NDX)), bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
