/*
  File PAGING_STRATEGY.c generated by XCOM-I, 2024-08-09 12:42:16.
*/

#include "runtimeC.h"

int32_t
PAGING_STRATEGY (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "PAGING_STRATEGY");
  // PREV_NDX1,PREV_NDX2 = -1; (1121)
  {
    int32_t numberRHS = (int32_t)(-1);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mPAGING_STRATEGYxPREV_NDX1, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mPAGING_STRATEGYxPREV_NDX2, bitRHS);
    bitRHS->inUse = 0;
  }
  // DO I = 0 TO MAX_PAGE; (1122)
  {
    int32_t from27, to27, by27;
    from27 = 0;
    to27 = bitToFixed (getBIT (16, mMAX_PAGE));
    by27 = 1;
    for (putBIT (16, mPAGING_STRATEGYxI, fixedToBit (16, from27));
         bitToFixed (getBIT (16, mPAGING_STRATEGYxI)) <= to27;
         putBIT (16, mPAGING_STRATEGYxI,
                 fixedToBit (16, bitToFixed (getBIT (16, mPAGING_STRATEGYxI))
                                     + by27)))
      {
        // IF (PAD_DISP(I) &  16383) = 0 THEN (1123)
        if (1
            & (xEQ (
                xAND (COREHALFWORD (mPAD_DISP
                                    + 2 * COREHALFWORD (mPAGING_STRATEGYxI)),
                      16383),
                0)))
          // DO; (1124)
          {
          rs1s1:;
            // PAGE = PAD_PAGE(I); (1125)
            {
              descriptor_t *bitRHS = getBIT (
                  16, mPAD_PAGE + 2 * COREHALFWORD (mPAGING_STRATEGYxI));
              putBIT (16, mPAGING_STRATEGYxPAGE, bitRHS);
              bitRHS->inUse = 0;
            }
            // LREC# = PAGE_TO_LREC(PAGE); (1126)
            {
              descriptor_t *bitRHS = getBIT (
                  16,
                  mPAGE_TO_LREC + 2 * COREHALFWORD (mPAGING_STRATEGYxPAGE));
              putBIT (16, mPAGING_STRATEGYxLRECp, bitRHS);
              bitRHS->inUse = 0;
            }
            // IF LREC# = -1 THEN (1127)
            if (1 & (xEQ (COREHALFWORD (mPAGING_STRATEGYxLRECp), -1)))
              // DO; (1128)
              {
              rs1s1s1:;
                // IF PREV_NDX1 = -1 THEN (1129)
                if (1 & (xEQ (COREHALFWORD (mPAGING_STRATEGYxPREV_NDX1), -1)))
                  // DO; (1130)
                  {
                  rs1s1s1s1:;
                    // PREV_NDX1 = I; (1131)
                    {
                      descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxI);
                      putBIT (16, mPAGING_STRATEGYxPREV_NDX1, bitRHS);
                      bitRHS->inUse = 0;
                    }
                    // PREV_CNT1 = PAD_CNT(I); (1132)
                    {
                      descriptor_t *bitRHS = getBIT (
                          16,
                          mPAD_CNT + 2 * COREHALFWORD (mPAGING_STRATEGYxI));
                      putBIT (16, mPAGING_STRATEGYxPREV_CNT1, bitRHS);
                      bitRHS->inUse = 0;
                    }
                  es1s1s1s1:;
                  } // End of DO block
                // ELSE (1133)
                else
                  // IF PAD_CNT(I) < PREV_CNT1 THEN (1134)
                  if (1
                      & (xLT (COREHALFWORD (
                                  mPAD_CNT
                                  + 2 * COREHALFWORD (mPAGING_STRATEGYxI)),
                              COREHALFWORD (mPAGING_STRATEGYxPREV_CNT1))))
                    // DO; (1135)
                    {
                    rs1s1s1s2:;
                      // PREV_NDX1 = I; (1136)
                      {
                        descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxI);
                        putBIT (16, mPAGING_STRATEGYxPREV_NDX1, bitRHS);
                        bitRHS->inUse = 0;
                      }
                      // PREV_CNT1 = PAD_CNT(I); (1137)
                      {
                        descriptor_t *bitRHS = getBIT (
                            16,
                            mPAD_CNT + 2 * COREHALFWORD (mPAGING_STRATEGYxI));
                        putBIT (16, mPAGING_STRATEGYxPREV_CNT1, bitRHS);
                        bitRHS->inUse = 0;
                      }
                    es1s1s1s2:;
                    } // End of DO block
              es1s1s1:;
              } // End of DO block
            // ELSE (1138)
            else
              // DO; (1139)
              {
              rs1s1s2:;
                // IF PREV_NDX2 = -1 THEN (1140)
                if (1 & (xEQ (COREHALFWORD (mPAGING_STRATEGYxPREV_NDX2), -1)))
                  // DO; (1141)
                  {
                  rs1s1s2s1:;
                    // PREV_NDX2 = I; (1142)
                    {
                      descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxI);
                      putBIT (16, mPAGING_STRATEGYxPREV_NDX2, bitRHS);
                      bitRHS->inUse = 0;
                    }
                    // PREV_CNT2 = PAD_CNT(I); (1143)
                    {
                      descriptor_t *bitRHS = getBIT (
                          16,
                          mPAD_CNT + 2 * COREHALFWORD (mPAGING_STRATEGYxI));
                      putBIT (16, mPAGING_STRATEGYxPREV_CNT2, bitRHS);
                      bitRHS->inUse = 0;
                    }
                  es1s1s2s1:;
                  } // End of DO block
                // ELSE (1144)
                else
                  // IF PAD_CNT(I) < PREV_CNT2 THEN (1145)
                  if (1
                      & (xLT (COREHALFWORD (
                                  mPAD_CNT
                                  + 2 * COREHALFWORD (mPAGING_STRATEGYxI)),
                              COREHALFWORD (mPAGING_STRATEGYxPREV_CNT2))))
                    // DO; (1146)
                    {
                    rs1s1s2s2:;
                      // PREV_NDX2 = I; (1147)
                      {
                        descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxI);
                        putBIT (16, mPAGING_STRATEGYxPREV_NDX2, bitRHS);
                        bitRHS->inUse = 0;
                      }
                      // PREV_CNT2 = PAD_CNT(I); (1148)
                      {
                        descriptor_t *bitRHS = getBIT (
                            16,
                            mPAD_CNT + 2 * COREHALFWORD (mPAGING_STRATEGYxI));
                        putBIT (16, mPAGING_STRATEGYxPREV_CNT2, bitRHS);
                        bitRHS->inUse = 0;
                      }
                    es1s1s2s2:;
                    } // End of DO block
              es1s1s2:;
              } // End of DO block
          es1s1:;
          } // End of DO block
      }
  } // End of DO for-loop block
  // IF PREV_NDX2 >= 0 THEN (1149)
  if (1 & (xGE (COREHALFWORD (mPAGING_STRATEGYxPREV_NDX2), 0)))
    // NEW_NDX = PREV_NDX2; (1150)
    {
      descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxPREV_NDX2);
      putBIT (16, mNEW_NDX, bitRHS);
      bitRHS->inUse = 0;
    }
  // ELSE (1151)
  else
    // NEW_NDX = PREV_NDX1; (1152)
    {
      descriptor_t *bitRHS = getBIT (16, mPAGING_STRATEGYxPREV_NDX1);
      putBIT (16, mNEW_NDX, bitRHS);
      bitRHS->inUse = 0;
    }
  // IF NEW_NDX < 0 THEN (1153)
  if (1 & (xLT (COREHALFWORD (mNEW_NDX), 0)))
    // GO TO NO_PAGES; (1154)
    {
      resetAllReentryGuards ();
      longjmp (jbNO_PAGES, 1);
    }
  // IF (PAD_DISP(NEW_NDX) &  16384) ~= 0 THEN (1155)
  if (1
      & (xNEQ (
          xAND (COREHALFWORD (mPAD_DISP + 2 * COREHALFWORD (mNEW_NDX)), 16384),
          0)))
    // DO; (1156)
    {
    rs2:;
      // PAGE = PAD_PAGE(NEW_NDX); (1157)
      {
        descriptor_t *bitRHS
            = getBIT (16, mPAD_PAGE + 2 * COREHALFWORD (mNEW_NDX));
        putBIT (16, mPAGING_STRATEGYxPAGE, bitRHS);
        bitRHS->inUse = 0;
      }
      // LREC# = PAGE_TO_LREC(PAGE); (1158)
      {
        descriptor_t *bitRHS = getBIT (
            16, mPAGE_TO_LREC + 2 * COREHALFWORD (mPAGING_STRATEGYxPAGE));
        putBIT (16, mPAGING_STRATEGYxLRECp, bitRHS);
        bitRHS->inUse = 0;
      }
      // IF LREC# = -1 THEN (1159)
      if (1 & (xEQ (COREHALFWORD (mPAGING_STRATEGYxLRECp), -1)))
        // DO; (1160)
        {
        rs2s1:;
          // LAST_LREC = LAST_LREC + 1; (1161)
          {
            int32_t numberRHS = (int32_t)(xadd (COREHALFWORD (mLAST_LREC), 1));
            descriptor_t *bitRHS;
            bitRHS = fixedToBit (32, (int32_t)(numberRHS));
            putBIT (16, mLAST_LREC, bitRHS);
            bitRHS->inUse = 0;
          }
          // PAGE_TO_LREC(PAGE) = LAST_LREC; (1162)
          {
            descriptor_t *bitRHS = getBIT (16, mLAST_LREC);
            putBIT (16,
                    mPAGE_TO_LREC + 2 * (COREHALFWORD (mPAGING_STRATEGYxPAGE)),
                    bitRHS);
            bitRHS->inUse = 0;
          }
          // LREC# = LAST_LREC; (1163)
          {
            descriptor_t *bitRHS = getBIT (16, mLAST_LREC);
            putBIT (16, mPAGING_STRATEGYxLRECp, bitRHS);
            bitRHS->inUse = 0;
          }
        es2s1:;
        } // End of DO block
      // COREWORD(ADDR(PAGE_TEMP)) = PAD_ADDR(NEW_NDX); (1164)
      {
        int32_t numberRHS
            = (int32_t)(getFIXED (mPAD_ADDR + 4 * COREHALFWORD (mNEW_NDX)));
        COREWORD2 (ADDR ("PAGING_STRATEGYxPAGE_TEMP", 0x80000000, NULL, 0),
                   numberRHS);
      }
      // FILE(5,LREC#) = PAGE_TEMP; (1165)
      {
        lFILE (5, COREHALFWORD (mPAGING_STRATEGYxLRECp),
               ADDR ("PAGING_STRATEGYxPAGE_TEMP", 0, NULL, 0));
      }
      // WRITE_CNT = WRITE_CNT + 1; (1166)
      {
        int32_t numberRHS = (int32_t)(xadd (getFIXED (mWRITE_CNT), 1));
        putFIXED (mWRITE_CNT, numberRHS);
      }
      // PAD_DISP(NEW_NDX) = 0; (1167)
      {
        int32_t numberRHS = (int32_t)(0);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mPAD_DISP + 2 * (COREHALFWORD (mNEW_NDX)), bitRHS);
        bitRHS->inUse = 0;
      }
    es2:;
    } // End of DO block
  {
    reentryGuard = 0;
    return 0;
  }
}
