#!/bin/bash

if [[ "$1" == "--help" ]]
then
	echo "This script forms match patterns for a BASELINE AGC software"
	echo "version, and then checks those patterns against the BASELINE."
	echo "The BASELINE.patterns file can be subsequently used for matching"
	echo "a (non-BASELINE) ROPE.bin, but this script doesn't handle that."
	echo ""
	echo "Usage:"
	echo "	         workflow.sh BASELINE [OPTIONS]"
	echo ""
	echo "Both specifyAGC.py and disassemblerAGC.py must be in the PATH."
	echo "Any OPTIONS relevant to specifyAGC.py or to disassemblerAGC.py's"
	echo "--specs or --find functionality can be used."
	exit 0
fi

baseline=$1
shift

specify=""
specs=""
find=""
debug=""
ext="binsource"
format=""
while [[ "$1" != "" ]]
do
	if [[ "$1" == "--block1" || "$1" == "--blk2" ]]
	then
		specify="$specify $1"
		specs="$specs $1"
		find="$find $1"
	elif [[ "$1" == "--bin" || "$1" == "--hardware" ]]
	then
		ext="bin"
		specs="$specs $1"
		find="$find $1"
	elif [[ "$1" == "--min="* || "$1" == "--invent" ]]
	then
		specify="$specify $1"
	elif [[ "$1" == "--debug" ]]
	then
		debug="$1"
	else
		find="$find $1"
	fi
	shift
done

specifyAGC.py <$baseline.lst >$baseline-autogenerated.specs $specify
disassemblerAGC.py --specs=$baseline-autogenerated.specs <$baseline.$ext >$baseline-autogenerated.patterns $specs
disassemblerAGC.py --find=$baseline-autogenerated.patterns --check=$baseline.lst <$baseline.$ext >$baseline-autogenerated.matches $find

if [[ "$debug" != "" ]]
then
	echo "OPTIONS used:"
	echo "    specifyAGC.py:		$specify"
	echo "    disassemblerAGC.py --specs:	$specs"
	echo "    disassemblerAGC.py --find:	$find"
fi