# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Corona 261
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	www.ibiblio.org/apollo/index.html
# Mod history:	2023-05-02 RSB	So far we have no source code, so 
#				this is the octal dump of the physical
#				rope-memory modules right now.

BASENAME=Corona261
EXTRA_YAYUL_ARGS+=--block1 --parity --honeywell
OCT2BIN_ARGS+=--block1
NO_BINSOURCE=yes

#include ../Makefile.inc

# This isn't the real "default" target.  It's just here in case
# Makefile.inc is commented out above.
.PHONY: default
default:
	@echo Nothing to do yet.

