#!/usr/bin/env python
# Compile, link, and run a HAL/S program, using HALSFC, lnk101, and gpc-batch.

import sys
import subprocess
import os
from pathlib import Path

extraParms = ""
def getParms(filename):
    parmBase = extraParms + "LIST,NOTABLES,SRN,TEMPLATE,NOLFXI,REGOPT,VARSYM,CARDTYPE="
    cardtypesBySourceFile = {
        "CS2INI" : "ACFCRM",
        "CS4INI" : "ACFCRM",
        "CPTOSV" : "ACBDFCRM",
        "CPUSLS" : "ACBDFCRM",
        "GKDASC": "AMOCNCRMFDGCHC",
        "GKRORB": "ACOMNCRCFCGDHC",
        "GKGMNV": "ACOCNMRMFCGCHD"
        }
    cardtype = "FCRM"
    for name in cardtypesBySourceFile:
        if name in filename:
            cardtype = cardtypesBySourceFile[name]
            break
    return parmBase + cardtype

helpMsg = '''
Used for compiling, linking, running a standalone program implemented in a 
single HAL/S file.

Usage:
     compileLinkRun [OPTIONS] --filename=F
     
The available OPTIONs are:
    --filename=F    Required.  F is the path to the HAL/S source-code file.
    --parms=P       P is a list of HAL/S-FC compiler options that will 
                    completely override the defaults used by this program.
    --extra-parms=P P is a list of extra HAL/S-FC compiler options that will
                    be prefixed to the defaults used by this program.  P should
                    end in a comma.  
    --extra-pass1=P A list of extra "modern" command-line parameters passed to
                    the HALSFC.  The extra parameters should be 
                    separated by spaces, and should not themselves contain 
                    spaces (even if quoted).  Example: 
                            --extra-pass1="--pretty-bnf --verbose"
    --interactive   In running the compiled program, it is assumed by default
                    that the program does not require interactive user input
                    (via READ(5)), so output (from WRITE(6)) is captured and
                    printed out in a way that removes any extraneous messages
                    from the emulator.  If `--interactive` is used, the raw
                    output from the emulator is displayed, and user input can
                    be supplied via READ(5).  This distinction is primarily
                    to work around deficiencies in the emulator that are
                    hopefully temporary in nature while development of it
                    proceeds.
    --no-test       Do not use HALSFC's --test option.
'''

filename = None
parmList = None
interactive = True
extraPass1 = []
noTest = False
for parameter in sys.argv[1:]:
    if parameter.startswith("--parms="):
        parmList = parameter[8:]
    elif parameter.startswith("--extra-parms="):
        extraParms = parameter[14:]
    elif parameter.startswith("--extra-pass1="):
        extraPass1 = parameter[14:].strip().split()
    elif parameter.startswith("--filename="):
        filename = parameter[11:]
    elif parameter == "--interactive":
        interactive = True
    elif parameter == "--no-test":
        noTest = True
    else:
        print(helpMsg)
        sys.exit(1)
if parmList == None:
    parmList = getParms(filename)
basename = Path(filename).stem
objfile = f"{basename}.obj"
fcmfile = f"{basename}.fcm"
symfile = f"{basename}.json"
print(f"For file {basename}.hal, producing {objfile}, {fcmfile}, {symfile}")

# First step, compile.
command = ["HALSFC", filename, f"--parms={parmList}", "-o", objfile]
if not noTest:
    command += ["--test", "--force", "--clean", "--archive"]
command += extraPass1
print(" ".join(command))
try:
    result = subprocess.run(command, capture_output = True, text = True, check = True)
    print(result.stdout)
except subprocess.CalledProcessError as e:
    print(f"Compilation failed with exit code {e.returncode}.")
    print("STDOUT:", e.stdout)
    print("STDERR:", e.stderr)
    os._exit(1)

# Next, link.
command = ["lnk101", objfile, "-o", fcmfile, "--json-symbols", symfile]
print(" ".join(command))
try:
    result = subprocess.run(command, capture_output = True, text = True, check = True)
except subprocess.CalledProcessError as e:
    print(f"Linking failed with exit code {e.returncode}.")
    print("STDOUT:", e.stdout)
    print("STDERR:", e.stderr)
    #os._exit(1)
    command = ["rldanalyze", symfile, fcmfile, f"../{config}.fcm", 
               "--csect-table", "../csects-{config}.json", "--show-gaps", 
               "--show-csects", "--scan-gaps"]
    print(" ".join(command))
    try:
        result = subprocess.run(command, capture_output = True, text = True, check = True)
    except subprocess.CalledProcessError as e:
        print(f"rldanalyze failed with exit code {e.returncode}.")
        print("STDOUT:", e.stdout)
        print("STDERR:", e.stderr)
    os._exit(1)

# Next, run it in the emulator.
command = ["gpc", "run", "--interactive", 
	   "--no-trace", "--no-verbose", 
	   "--symbols", symfile, 
	   "--line-width", "240", fcmfile]
print(" ".join(command))
if interactive:
    result = subprocess.run(command)
else:
    try:
        result = subprocess.run(command, capture_output = True, text = True, check = True)
        #print("STDOUT:", result.stdout)
        #print("STDERR:", result.stderr)
        print("Emulation output --------------------------------------------------")
        lines = result.stdout.split("\n")
        for line in lines:
            if line.startswith("OUTPUT(6)"):
                print(line[11:])
        print("-------------------------------------------------------------------")
    except subprocess.CalledProcessError as e:
        #print(f"Comparison failed with exit code {e.returncode}.")
        print("STDOUT:", e.stdout)
        print("STDERR:", e.stderr)
        #os._exit(1)

