# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Colossus 2A (Comanche 055).
#		(The source code for the Command Module's (CM)
#		Apollo Guidance Computer (AGC), Apollo 11.)
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2009-05-20 RSB	Adapted from similar Colossus 249 Makefile.
#		2009-07-04 RSB	Added --html switch.
#		2011-05-03 JL	Replaced with newer version from Artemis072.
#						Point to moved Oct2Bin.
#		2012-09-16 JL	Updated to match tools dir changes.
#		2016-10-04 JL	Change to use Makefile.inc.

BASENAME=Comanche055
include ../Makefile.inc
