/*
  File GENERATExGEN_CLASS0xSHAPING_FUNCTIONS.c generated by XCOM-I, 2024-08-09
  12:39:31.
*/

#include "runtimeC.h"

int32_t
GENERATExGEN_CLASS0xSHAPING_FUNCTIONS (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard
      = guardReentry (reentryGuard, "GENERATExGEN_CLASS0xSHAPING_FUNCTIONS");
  // RIGHTOP = ARG_STACK(ARG); (11736)
  {
    descriptor_t *bitRHS = getBIT (
        16,
        mGENERATExARG_STACK
            + 2 * COREHALFWORD (mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxARG));
    putBIT (16, mRIGHTOP, bitRHS);
    bitRHS->inUse = 0;
  }
  // REPETITION = ARG_TYPE(ARG); (11737)
  {
    descriptor_t *bitRHS = getBIT (
        16,
        mGENERATExARG_TYPE
            + 2 * COREHALFWORD (mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxARG));
    putBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF FORM(RIGHTOP) = LIT THEN (11738)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mRIGHTOP)) + 32 + 2 * (0)),
              BYTE0 (mLIT))))
    // IF PACKTYPE(TYPE(RIGHTOP)) = INTSCA THEN (11739)
    if (1
        & (xEQ (BYTE0 (mPACKTYPE
                       + 1
                             * COREHALFWORD (getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mRIGHTOP))
                                             + 50 + 2 * (0))),
                BYTE0 (mINTSCA))))
      // CALL LITERAL(LOC(RIGHTOP), OPTYPE, RIGHTOP); (11740)
      {
        putBITp (16, mGENERATExLITERALxPTR,
                 getBIT (16, getFIXED (mIND_STACK)
                                 + 73 * (COREHALFWORD (mRIGHTOP)) + 40
                                 + 2 * (0)));
        putBITp (16, mGENERATExLITERALxLTYPE, getBIT (16, mOPTYPE));
        putBITp (16, mGENERATExLITERALxSTACK, getBIT (16, mRIGHTOP));
        GENERATExLITERAL (0);
      }
  // IF COPY(RIGHTOP) = 0 THEN (11741)
  if (1
      & (xEQ (COREHALFWORD (getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mRIGHTOP)) + 26 + 2 * (0)),
              0)))
    // DO; (11742)
    {
    rs1:;
      // DO CASE PACKTYPE(TYPE(RIGHTOP)); (11743)
      {
      rs1s1:
        switch (BYTE0 (mPACKTYPE
                       + 1
                             * COREHALFWORD (getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mRIGHTOP))
                                             + 50 + 2 * (0))))
          {
          case 0:
            // IF DATATYPE(OPTYPE) ~= INTEGER THEN (11745)
            if (1
                & (xNEQ (BYTE0 (mDATATYPE + 1 * COREHALFWORD (mOPTYPE)),
                         BYTE0 (mINTEGER))))
              {
              rs1s1s1:;
                // AREA, TEMPSPACE = ROW(RIGHTOP) * COLUMN(RIGHTOP); (11746)
                {
                  int32_t numberRHS = (int32_t)(xmultiply (
                      COREHALFWORD (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mRIGHTOP)) + 48
                                    + 2 * (0)),
                      COREHALFWORD (getFIXED (mIND_STACK)
                                    + 73 * (COREHALFWORD (mRIGHTOP)) + 24
                                    + 2 * (0))));
                  putFIXED (mAREA, numberRHS);
                  putFIXED (mTEMPSPACE, numberRHS);
                }
                // CALL BEGIN_SF_REPEAT(REPETITION); (11747)
                {
                  putBITp (
                      16, mGENERATExGEN_CLASS0xBEGIN_SF_REPEATxCT,
                      getBIT (
                          16,
                          mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
                  GENERATExGEN_CLASS0xBEGIN_SF_REPEAT (0);
                }
                // INX_CON(RESULT) = INX_CON(RESULT) - SF_DISP; (11748)
                {
                  int32_t numberRHS = (int32_t)(xsubtract (
                      getFIXED (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mRESULT)) + 4 + 4 * (0)),
                      COREHALFWORD (mSF_DISP)));
                  putFIXED (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mRESULT)) + 4 + 4 * (0),
                            numberRHS);
                }
                // CALL VECMAT_ASSIGN(RESULT, RIGHTOP); (11749)
                {
                  putBITp (16, mGENERATExVECMAT_ASSIGNxOP0,
                           getBIT (16, mRESULT));
                  putBITp (16, mGENERATExVECMAT_ASSIGNxOP1,
                           getBIT (16, mRIGHTOP));
                  GENERATExVECMAT_ASSIGN (0);
                }
                // INX_CON(RESULT) = INX_CON(RESULT) + SF_DISP; (11750)
                {
                  int32_t numberRHS = (int32_t)(xadd (
                      getFIXED (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mRESULT)) + 4 + 4 * (0)),
                      COREHALFWORD (mSF_DISP)));
                  putFIXED (getFIXED (mIND_STACK)
                                + 73 * (COREHALFWORD (mRESULT)) + 4 + 4 * (0),
                            numberRHS);
                }
                // AREA = AREA * SF_DISP; (11751)
                {
                  int32_t numberRHS = (int32_t)(xmultiply (
                      getFIXED (mAREA), COREHALFWORD (mSF_DISP)));
                  putFIXED (mAREA, numberRHS);
                }
              es1s1s1:;
              } // End of DO block
            else
              {
              rs1s1s2:;
                // IF CHECK_REMOTE(RIGHTOP) | DEL(RIGHTOP) > 0 THEN (11754)
                if (1
                    & (xOR (
                        bitToFixed ((putBITp (16, mGENERATExCHECK_REMOTExOP,
                                              getBIT (16, mRIGHTOP)),
                                     GENERATExCHECK_REMOTE (0))),
                        xGT (COREHALFWORD (getFIXED (mIND_STACK)
                                           + 73 * (COREHALFWORD (mRIGHTOP))
                                           + 28 + 2 * (0)),
                             0))))
                  // RIGHTOP = VECMAT_CONVERT(RIGHTOP); (11755)
                  {
                    int32_t numberRHS
                        = (int32_t)((putBITp (16, mGENERATExVECMAT_CONVERTxOP,
                                              getBIT (16, mRIGHTOP)),
                                     GENERATExVECMAT_CONVERT (0)));
                    descriptor_t *bitRHS;
                    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                    putBIT (16, mRIGHTOP, bitRHS);
                    bitRHS->inUse = 0;
                  }
                // IF DATA_REMOTE & (CSECT_TYPE(LOC(RIGHTOP),RIGHTOP)=LOCAL#D)
                // THEN (11756)
                if (1
                    & (xAND (
                        BYTE0 (mDATA_REMOTE),
                        xEQ (bitToFixed (
                                 (putBITp (
                                      16, mCSECT_TYPExPTR,
                                      getBIT (
                                          16,
                                          getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 40 + 2 * (0))),
                                  putBITp (16, mCSECT_TYPExOP,
                                           getBIT (16, mRIGHTOP)),
                                  CSECT_TYPE (0))),
                             6))))
                  // RIGHTOP = VECMAT_CONVERT(RIGHTOP); (11757)
                  {
                    int32_t numberRHS
                        = (int32_t)((putBITp (16, mGENERATExVECMAT_CONVERTxOP,
                                              getBIT (16, mRIGHTOP)),
                                     GENERATExVECMAT_CONVERT (0)));
                    descriptor_t *bitRHS;
                    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                    putBIT (16, mRIGHTOP, bitRHS);
                    bitRHS->inUse = 0;
                  }
                // CALL BEGIN_SF_REPEAT(REPETITION); (11758)
                {
                  putBITp (
                      16, mGENERATExGEN_CLASS0xBEGIN_SF_REPEATxCT,
                      getBIT (
                          16,
                          mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
                  GENERATExGEN_CLASS0xBEGIN_SF_REPEAT (0);
                }
                // CALL SHAPING_CALL(RIGHTOP); (11759)
                {
                  putBITp (16, mGENERATExGEN_CLASS0xSHAPING_CALLxOP,
                           getBIT (16, mRIGHTOP));
                  GENERATExGEN_CLASS0xSHAPING_CALL (0);
                }
              es1s1s2:;
              } // End of DO block
            break;
          case 1:
            // GO TO DO_ISSHP; (11761)
            goto DO_ISSHP;
            break;
          case 2:
            // DO; (11762)
            {
            rs1s1s3:;
              // RIGHTOP = CTON(RIGHTOP, OPTYPE); (11762)
              {
                descriptor_t *bitRHS
                    = (putBITp (16, mGENERATExCTONxOP, getBIT (16, mRIGHTOP)),
                       putBITp (16, mGENERATExCTONxOPTYPE,
                                getBIT (16, mOPTYPE)),
                       GENERATExCTON (0));
                putBIT (16, mRIGHTOP, bitRHS);
                bitRHS->inUse = 0;
              }
              // GO TO DO_ISSHPS; (11763)
              goto DO_ISSHPS;
            es1s1s3:;
            } // End of DO block
            break;
          case 3:
            // DO; (11765)
            {
            rs1s1s4:;
            // DO_ISSHP: (11765)
            DO_ISSHP:
              // IF PACKTYPE(OPTYPE) = VECMAT THEN (11766)
              if (1
                  & (xEQ (BYTE0 (mPACKTYPE + 1 * COREHALFWORD (mOPTYPE)),
                          BYTE0 (mVECMAT))))
                // LDTYPE = OPTYPE&8 | SCALAR; (11767)
                {
                  int32_t numberRHS = (int32_t)(xOR (
                      xAND (COREHALFWORD (mOPTYPE), 8), BYTE0 (mSCALAR)));
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxLDTYPE,
                          bitRHS);
                  bitRHS->inUse = 0;
                }
              // ELSE (11768)
              else
                // LDTYPE = OPTYPE; (11769)
                {
                  descriptor_t *bitRHS = getBIT (16, mOPTYPE);
                  putBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxLDTYPE,
                          bitRHS);
                  bitRHS->inUse = 0;
                }
              // CALL FORCE_BY_MODE(RIGHTOP, LDTYPE); (11770)
              {
                putBITp (16, mGENERATExFORCE_BY_MODExOP,
                         getBIT (16, mRIGHTOP));
                putBITp (
                    16, mGENERATExFORCE_BY_MODExMODE,
                    getBIT (16,
                            mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxLDTYPE));
                GENERATExFORCE_BY_MODE (0);
              }
            // DO_ISSHPS: (11771)
            DO_ISSHPS:
              // IF REPETITION > 4 THEN (11772)
              if (1
                  & (xGT (
                      COREHALFWORD (
                          mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION),
                      4)))
                // DO; (11773)
                {
                rs1s1s4s1:;
                  // CALL BEGIN_SF_REPEAT(REPETITION, 1); (11774)
                  {
                    putBITp (
                        16, mGENERATExGEN_CLASS0xBEGIN_SF_REPEATxCT,
                        getBIT (
                            16,
                            mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
                    putBITp (1, mGENERATExGEN_CLASS0xBEGIN_SF_REPEATxFLAG,
                             fixedToBit (32, (int32_t)(1)));
                    GENERATExGEN_CLASS0xBEGIN_SF_REPEAT (0);
                  }
                  // CALL EMIT_BY_MODE(STORE, REG(RIGHTOP), RESULT, OPTYPE);
                  // (11775)
                  {
                    putBITp (16, mGENERATExEMIT_BY_MODExOP,
                             getBIT (16, mGENERATExSTORE));
                    putBITp (16, mGENERATExEMIT_BY_MODExR,
                             getBIT (16, getFIXED (mIND_STACK)
                                             + 73 * (COREHALFWORD (mRIGHTOP))
                                             + 46 + 2 * (0)));
                    putBITp (16, mGENERATExEMIT_BY_MODExOP2,
                             getBIT (16, mRESULT));
                    putBITp (16, mGENERATExEMIT_BY_MODExMODE,
                             getBIT (16, mOPTYPE));
                    GENERATExEMIT_BY_MODE (0);
                  }
                  // CALL DROP_INX(RESULT); (11776)
                  {
                    putBITp (16, mGENERATExDROP_INXxOP, getBIT (16, mRESULT));
                    GENERATExDROP_INX (0);
                  }
                es1s1s4s1:;
                } // End of DO block
              // ELSE (11777)
              else
                // DO; (11778)
                {
                rs1s1s4s2:;
                  // DO OP2 = 1 TO REPETITION; (11779)
                  {
                    int32_t from114, to114, by114;
                    from114 = 1;
                    to114 = bitToFixed (getBIT (
                        16,
                        mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
                    by114 = 1;
                    for (putBIT (16, mOP2, fixedToBit (16, from114));
                         bitToFixed (getBIT (16, mOP2)) <= to114;
                         putBIT (16, mOP2,
                                 fixedToBit (16, bitToFixed (getBIT (16, mOP2))
                                                     + by114)))
                      {
                        // CALL EMIT_BY_MODE(STORE, REG(RIGHTOP), RESULT,
                        // OPTYPE); (11780)
                        {
                          putBITp (16, mGENERATExEMIT_BY_MODExOP,
                                   getBIT (16, mGENERATExSTORE));
                          putBITp (
                              16, mGENERATExEMIT_BY_MODExR,
                              getBIT (16, getFIXED (mIND_STACK)
                                              + 73 * (COREHALFWORD (mRIGHTOP))
                                              + 46 + 2 * (0)));
                          putBITp (16, mGENERATExEMIT_BY_MODExOP2,
                                   getBIT (16, mRESULT));
                          putBITp (16, mGENERATExEMIT_BY_MODExMODE,
                                   getBIT (16, mOPTYPE));
                          GENERATExEMIT_BY_MODE (0);
                        }
                        // INX_CON(RESULT) = INX_CON(RESULT) + SF_DISP; (11781)
                        {
                          int32_t numberRHS = (int32_t)(xadd (
                              getFIXED (getFIXED (mIND_STACK)
                                        + 73 * (COREHALFWORD (mRESULT)) + 4
                                        + 4 * (0)),
                              COREHALFWORD (mSF_DISP)));
                          putFIXED (getFIXED (mIND_STACK)
                                        + 73 * (COREHALFWORD (mRESULT)) + 4
                                        + 4 * (0),
                                    numberRHS);
                        }
                      }
                  } // End of DO for-loop block
                  // REPETITION = 0; (11782)
                  {
                    int32_t numberRHS = (int32_t)(0);
                    descriptor_t *bitRHS;
                    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                    putBIT (16,
                            mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION,
                            bitRHS);
                    bitRHS->inUse = 0;
                  }
                es1s1s4s2:;
                } // End of DO block
              // CALL DROP_REG(RIGHTOP); (11783)
              {
                putBITp (16, mGENERATExDROP_REGxOP, getBIT (16, mRIGHTOP));
                GENERATExDROP_REG (0);
              }
              // AREA = SF_DISP; (11784)
              {
                descriptor_t *bitRHS = getBIT (16, mSF_DISP);
                int32_t numberRHS;
                numberRHS = bitToFixed (bitRHS);
                putFIXED (mAREA, numberRHS);
                bitRHS->inUse = 0;
              }
            es1s1s4:;
            } // End of DO block
            break;
          }
      } // End of DO CASE block
      // CALL END_SF_REPEAT(REPETITION); (11785)
      {
        putBITp (
            16, mGENERATExGEN_CLASS0xEND_SF_REPEATxCT,
            getBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
        GENERATExGEN_CLASS0xEND_SF_REPEAT (0);
      }
    es1:;
    } // End of DO block
  // ELSE (11786)
  else
    // DO; (11787)
    {
    rs2:;
      // CALL BEGIN_SF_REPEAT(REPETITION); (11788)
      {
        putBITp (
            16, mGENERATExGEN_CLASS0xBEGIN_SF_REPEATxCT,
            getBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
        GENERATExGEN_CLASS0xBEGIN_SF_REPEAT (0);
      }
      // CALL SHAPING_CALL(RIGHTOP); (11789)
      {
        putBITp (16, mGENERATExGEN_CLASS0xSHAPING_CALLxOP,
                 getBIT (16, mRIGHTOP));
        GENERATExGEN_CLASS0xSHAPING_CALL (0);
      }
      // CALL END_SF_REPEAT(REPETITION); (11790)
      {
        putBITp (
            16, mGENERATExGEN_CLASS0xEND_SF_REPEATxCT,
            getBIT (16, mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION));
        GENERATExGEN_CLASS0xEND_SF_REPEAT (0);
      }
    es2:;
    } // End of DO block
  // INX_CON(RESULT) = AREA * REPETITION + INX_CON(RESULT); (11791)
  {
    int32_t numberRHS = (int32_t)(xadd (
        xmultiply (
            getFIXED (mAREA),
            COREHALFWORD (mGENERATExGEN_CLASS0xSHAPING_FUNCTIONSxREPETITION)),
        getFIXED (getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mRESULT)) + 4
                  + 4 * (0))));
    putFIXED (getFIXED (mIND_STACK) + 73 * (COREHALFWORD (mRESULT)) + 4
                  + 4 * (0),
              numberRHS);
  }
  // CALL DROPSAVE(RIGHTOP); (11792)
  {
    putBITp (16, mGENERATExDROPSAVExENTRY, getBIT (16, mRIGHTOP));
    GENERATExDROPSAVE (0);
  }
  // CALL RETURN_STACK_ENTRY(RIGHTOP); (11793)
  {
    putBITp (16, mGENERATExRETURN_STACK_ENTRYxP, getBIT (16, mRIGHTOP));
    GENERATExRETURN_STACK_ENTRY (0);
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
