/*
  File GENERATExSEARCH_REGS.c generated by XCOM-I, 2024-08-09 12:39:31.
*/

#include "runtimeC.h"

int32_t
GENERATExSEARCH_REGS (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GENERATExSEARCH_REGS");
  // RC = RCLASS(TYPE(OP)); (3428)
  {
    descriptor_t *bitRHS = getBIT (
        8, mRCLASS
               + 1
                     * COREHALFWORD (
                         getFIXED (mIND_STACK)
                         + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP)) + 50
                         + 2 * (0)));
    putBIT (16, mGENERATExSEARCH_REGSxRC, bitRHS);
    bitRHS->inUse = 0;
  }
  // DO J = RCLASS_START(RC) TO RCLASS_START(RC+1)-1; (3429)
  {
    int32_t from49, to49, by49;
    from49 = bitToFixed (getBIT (
        16, mRCLASS_START + 2 * COREHALFWORD (mGENERATExSEARCH_REGSxRC)));
    to49 = xsubtract (
        COREHALFWORD (mRCLASS_START
                      + 2 * xadd (COREHALFWORD (mGENERATExSEARCH_REGSxRC), 1)),
        1);
    by49 = 1;
    for (putBIT (16, mGENERATExSEARCH_REGSxJ, fixedToBit (16, from49));
         bitToFixed (getBIT (16, mGENERATExSEARCH_REGSxJ)) <= to49; putBIT (
             16, mGENERATExSEARCH_REGSxJ,
             fixedToBit (16, bitToFixed (getBIT (16, mGENERATExSEARCH_REGSxJ))
                                 + by49)))
      {
        // I = REGISTERS(J); (3430)
        {
          descriptor_t *bitRHS = getBIT (
              16, mREGISTERS + 2 * COREHALFWORD (mGENERATExSEARCH_REGSxJ));
          putBIT (16, mGENERATExSEARCH_REGSxI, bitRHS);
          bitRHS->inUse = 0;
        }
        // IF USAGE(I) THEN (3431)
        if (1
            & (bitToFixed (getBIT (
                16, mUSAGE + 2 * COREHALFWORD (mGENERATExSEARCH_REGSxI)))))
          // DO; (3432)
          {
          rs1s1:;
            // IF FORM(OP) = SYM THEN (3433)
            if (1
                & (xEQ (COREHALFWORD (
                            getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP))
                            + 32 + 2 * (0)),
                        BYTE0 (mSYM))))
              // DO; (3434)
              {
              rs1s1s1:;
                // IF R_CONTENTS(I) = SYM THEN (3435)
                if (1
                    & (xEQ (
                        BYTE0 (mR_CONTENTS
                               + 1 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                        BYTE0 (mSYM))))
                  // IF R_VAR(I) = LOC(OP) THEN (3436)
                  if (1
                      & (xEQ (
                          COREHALFWORD (
                              mR_VAR
                              + 2 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                          COREHALFWORD (
                              getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP))
                              + 40 + 2 * (0)))))
                    // IF R_INX(I) = INX(OP) THEN (3437)
                    if (1
                        & (xEQ (
                            COREHALFWORD (
                                mR_INX
                                + 2 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                            COREHALFWORD (getFIXED (mIND_STACK)
                                          + 73
                                                * (COREHALFWORD (
                                                    mGENERATExSEARCH_REGSxOP))
                                          + 34 + 2 * (0)))))
                      // IF R_INX_CON(I) = INX_CON(OP) THEN (3438)
                      if (1
                          & (xEQ (
                              getFIXED (mR_INX_CON
                                        + 4
                                              * COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxI)),
                              getFIXED (getFIXED (mIND_STACK)
                                        + 73
                                              * (COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxOP))
                                        + 4 + 4 * (0)))))
                        // IF R_CON(I) = CONST(OP) | R_CON(I) = 0 THEN (3439)
                        if (1
                            & (xOR (
                                xEQ (getFIXED (
                                         mR_CON
                                         + 4
                                               * COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxI)),
                                     getFIXED (
                                         getFIXED (mIND_STACK)
                                         + 73
                                               * (COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxOP))
                                         + 0 + 4 * (0))),
                                xEQ (getFIXED (
                                         mR_CON
                                         + 4
                                               * COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxI)),
                                     0))))
                          // IF R_INX_SHIFT(I) = INX_SHIFT(OP) THEN (3440)
                          if (1
                              & (xEQ (
                                  BYTE0 (mR_INX_SHIFT
                                         + 1
                                               * COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxI)),
                                  BYTE0 (getFIXED (mIND_STACK)
                                         + 73
                                               * (COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxOP))
                                         + 64 + 1 * (0)))))
                            // IF I >= FR0 THEN (3441)
                            if (1
                                & (xGE (COREHALFWORD (mGENERATExSEARCH_REGSxI),
                                        BYTE0 (mFR0))))
                              // DO; (3442)
                              {
                              rs1s1s1s1:;
                                // IF CHECK_REMOTE(OP) & SYT_TYPE(LOC(OP)) =
                                // STRUCTURE & SYT_ARRAY(LOC(OP)) ~= 0 THEN
                                // (3443)
                                if (1
                                    & (xAND (
                                        xAND (
                                            bitToFixed ((
                                                putBITp (
                                                    16,
                                                    mGENERATExCHECK_REMOTExOP,
                                                    getBIT (
                                                        16,
                                                        mGENERATExSEARCH_REGSxOP)),
                                                GENERATExCHECK_REMOTE (0))),
                                            xEQ (
                                                BYTE0 (
                                                    getFIXED (mSYM_TAB)
                                                    + 34
                                                          * (COREHALFWORD (
                                                              getFIXED (
                                                                  mIND_STACK)
                                                              + 73
                                                                    * (COREHALFWORD (
                                                                        mGENERATExSEARCH_REGSxOP))
                                                              + 40 + 2 * (0)))
                                                    + 32 + 1 * (0)),
                                                BYTE0 (mSTRUCTURE))),
                                        xNEQ (
                                            COREHALFWORD (
                                                getFIXED (mSYM_TAB)
                                                + 34
                                                      * (COREHALFWORD (
                                                          getFIXED (mIND_STACK)
                                                          + 73
                                                                * (COREHALFWORD (
                                                                    mGENERATExSEARCH_REGSxOP))
                                                          + 40 + 2 * (0)))
                                                + 20 + 2 * (0)),
                                            0))))
                                  // RETURN -1; (3444)
                                  {
                                    reentryGuard = 0;
                                    return -1;
                                  }
                                // RETURN I; (3445)
                                {
                                  reentryGuard = 0;
                                  return COREHALFWORD (
                                      mGENERATExSEARCH_REGSxI);
                                }
                              es1s1s1s1:;
                              } // End of DO block
                            // ELSE (3446)
                            else
                              // IF OPMODE(R_TYPE(I))=OPMODE(TYPE(OP)) THEN
                              // (3447)
                              if (1
                                  & (xEQ (
                                      BYTE0 (
                                          mOPMODE
                                          + 1
                                                * BYTE0 (
                                                    mR_TYPE
                                                    + 1
                                                          * COREHALFWORD (
                                                              mGENERATExSEARCH_REGSxI))),
                                      BYTE0 (
                                          mOPMODE
                                          + 1
                                                * COREHALFWORD (
                                                    getFIXED (mIND_STACK)
                                                    + 73
                                                          * (COREHALFWORD (
                                                              mGENERATExSEARCH_REGSxOP))
                                                    + 50 + 2 * (0))))))
                                // DO; (3448)
                                {
                                rs1s1s1s2:;
                                  // IF CHECK_REMOTE(OP) & SYT_TYPE(LOC(OP)) =
                                  // STRUCTURE & SYT_ARRAY(LOC(OP))~=0 THEN
                                  // (3449)
                                  if (1
                                      & (xAND (
                                          xAND (
                                              bitToFixed ((
                                                  putBITp (
                                                      16,
                                                      mGENERATExCHECK_REMOTExOP,
                                                      getBIT (
                                                          16,
                                                          mGENERATExSEARCH_REGSxOP)),
                                                  GENERATExCHECK_REMOTE (0))),
                                              xEQ (
                                                  BYTE0 (
                                                      getFIXED (mSYM_TAB)
                                                      + 34
                                                            * (COREHALFWORD (
                                                                getFIXED (
                                                                    mIND_STACK)
                                                                + 73
                                                                      * (COREHALFWORD (
                                                                          mGENERATExSEARCH_REGSxOP))
                                                                + 40
                                                                + 2 * (0)))
                                                      + 32 + 1 * (0)),
                                                  BYTE0 (mSTRUCTURE))),
                                          xNEQ (
                                              COREHALFWORD (
                                                  getFIXED (mSYM_TAB)
                                                  + 34
                                                        * (COREHALFWORD (
                                                            getFIXED (
                                                                mIND_STACK)
                                                            + 73
                                                                  * (COREHALFWORD (
                                                                      mGENERATExSEARCH_REGSxOP))
                                                            + 40 + 2 * (0)))
                                                  + 20 + 2 * (0)),
                                              0))))
                                    // RETURN -1; (3450)
                                    {
                                      reentryGuard = 0;
                                      return -1;
                                    }
                                  // RETURN I; (3451)
                                  {
                                    reentryGuard = 0;
                                    return COREHALFWORD (
                                        mGENERATExSEARCH_REGSxI);
                                  }
                                es1s1s1s2:;
                                } // End of DO block
              es1s1s1:;
              } // End of DO block
            // ELSE (3452)
            else
              // IF FORM(OP) = LIT THEN (3453)
              if (1
                  & (xEQ (COREHALFWORD (
                              getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP))
                              + 32 + 2 * (0)),
                          BYTE0 (mLIT))))
                // DO; (3454)
                {
                rs1s1s2:;
                  // IF R_CONTENTS(I) = LIT THEN (3455)
                  if (1
                      & (xEQ (
                          BYTE0 (mR_CONTENTS
                                 + 1 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                          BYTE0 (mLIT))))
                    // IF R_CON(I) = VAL(OP) THEN (3456)
                    if (1
                        & (xEQ (
                            getFIXED (
                                mR_CON
                                + 4 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                            getFIXED (getFIXED (mIND_STACK)
                                      + 73
                                            * (COREHALFWORD (
                                                mGENERATExSEARCH_REGSxOP))
                                      + 12 + 4 * (0)))))
                      // DO; (3457)
                      {
                      rs1s1s2s1:;
                        // IF TYPE(OP) = SCALAR THEN (3458)
                        if (1
                            & (xEQ (COREHALFWORD (
                                        getFIXED (mIND_STACK)
                                        + 73
                                              * (COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxOP))
                                        + 50 + 2 * (0)),
                                    BYTE0 (mSCALAR))))
                          // RETURN I; (3459)
                          {
                            reentryGuard = 0;
                            return COREHALFWORD (mGENERATExSEARCH_REGSxI);
                          }
                        // IF R_TYPE(I) = TYPE(OP) THEN (3460)
                        if (1
                            & (xEQ (BYTE0 (mR_TYPE
                                           + 1
                                                 * COREHALFWORD (
                                                     mGENERATExSEARCH_REGSxI)),
                                    COREHALFWORD (
                                        getFIXED (mIND_STACK)
                                        + 73
                                              * (COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxOP))
                                        + 50 + 2 * (0)))))
                          // DO; (3461)
                          {
                          rs1s1s2s1s1:;
                            // IF I < FR0 THEN (3462)
                            if (1
                                & (xLT (COREHALFWORD (mGENERATExSEARCH_REGSxI),
                                        BYTE0 (mFR0))))
                              // RETURN I; (3463)
                              {
                                reentryGuard = 0;
                                return COREHALFWORD (mGENERATExSEARCH_REGSxI);
                              }
                            // IF R_XCON(I) = XVAL(OP) THEN (3464)
                            if (1
                                & (xEQ (
                                    getFIXED (
                                        mR_XCON
                                        + 4
                                              * COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxI)),
                                    getFIXED (
                                        getFIXED (mIND_STACK)
                                        + 73
                                              * (COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxOP))
                                        + 16 + 4 * (0)))))
                              // RETURN I; (3465)
                              {
                                reentryGuard = 0;
                                return COREHALFWORD (mGENERATExSEARCH_REGSxI);
                              }
                          es1s1s2s1s1:;
                          } // End of DO block
                      es1s1s2s1:;
                      } // End of DO block
                es1s1s2:;
                } // End of DO block
              // ELSE (3466)
              else
                // IF FORM(OP) = AIDX THEN (3467)
                if (1
                    & (xEQ (
                        COREHALFWORD (
                            getFIXED (mIND_STACK)
                            + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP))
                            + 32 + 2 * (0)),
                        BYTE0 (mAIDX))))
                  // DO; (3468)
                  {
                  rs1s1s3:;
                    // IF R_CONTENTS(I) = AIDX THEN (3469)
                    if (1
                        & (xEQ (
                            BYTE0 (
                                mR_CONTENTS
                                + 1 * COREHALFWORD (mGENERATExSEARCH_REGSxI)),
                            BYTE0 (mAIDX))))
                      // IF R_VAR(I) = LOC(OP) THEN (3470)
                      if (1
                          & (xEQ (COREHALFWORD (
                                      mR_VAR
                                      + 2
                                            * COREHALFWORD (
                                                mGENERATExSEARCH_REGSxI)),
                                  COREHALFWORD (
                                      getFIXED (mIND_STACK)
                                      + 73
                                            * (COREHALFWORD (
                                                mGENERATExSEARCH_REGSxOP))
                                      + 40 + 2 * (0)))))
                        // IF R_INX_SHIFT(I) = INX_SHIFT(OP) THEN (3471)
                        if (1
                            & (xEQ (BYTE0 (mR_INX_SHIFT
                                           + 1
                                                 * COREHALFWORD (
                                                     mGENERATExSEARCH_REGSxI)),
                                    BYTE0 (getFIXED (mIND_STACK)
                                           + 73
                                                 * (COREHALFWORD (
                                                     mGENERATExSEARCH_REGSxOP))
                                           + 64 + 1 * (0)))))
                          // IF R_CON(I) = 0 THEN (3472)
                          if (1
                              & (xEQ (getFIXED (
                                          mR_CON
                                          + 4
                                                * COREHALFWORD (
                                                    mGENERATExSEARCH_REGSxI)),
                                      0)))
                            // RETURN I; (3473)
                            {
                              reentryGuard = 0;
                              return COREHALFWORD (mGENERATExSEARCH_REGSxI);
                            }
                  es1s1s3:;
                  } // End of DO block
                // ELSE (3474)
                else
                  // IF FORM(OP) = WORK THEN (3475)
                  if (1
                      & (xEQ (
                          COREHALFWORD (
                              getFIXED (mIND_STACK)
                              + 73 * (COREHALFWORD (mGENERATExSEARCH_REGSxOP))
                              + 32 + 2 * (0)),
                          BYTE0 (mWORK))))
                    // DO; (3476)
                    {
                    rs1s1s4:;
                      // IF R_CONTENTS(I) = VAC THEN (3477)
                      if (1
                          & (xEQ (BYTE0 (mR_CONTENTS
                                         + 1
                                               * COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxI)),
                                  BYTE0 (mVAC))))
                        // IF R_VAR(I) = LOC2(OP) THEN (3478)
                        if (1
                            & (xEQ (COREHALFWORD (
                                        mR_VAR
                                        + 2
                                              * COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxI)),
                                    COREHALFWORD (
                                        getFIXED (mIND_STACK)
                                        + 73
                                              * (COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxOP))
                                        + 42 + 2 * (0)))))
                          // IF R_INX_SHIFT(I) = INX_SHIFT(OP) THEN (3479)
                          if (1
                              & (xEQ (
                                  BYTE0 (mR_INX_SHIFT
                                         + 1
                                               * COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxI)),
                                  BYTE0 (getFIXED (mIND_STACK)
                                         + 73
                                               * (COREHALFWORD (
                                                   mGENERATExSEARCH_REGSxOP))
                                         + 64 + 1 * (0)))))
                            // IF R_CON(I) = 0 THEN (3480)
                            if (1
                                & (xEQ (
                                    getFIXED (
                                        mR_CON
                                        + 4
                                              * COREHALFWORD (
                                                  mGENERATExSEARCH_REGSxI)),
                                    0)))
                              // RETURN I; (3481)
                              {
                                reentryGuard = 0;
                                return COREHALFWORD (mGENERATExSEARCH_REGSxI);
                              }
                    es1s1s4:;
                    } // End of DO block
          es1s1:;
          } // End of DO block
      }
  } // End of DO for-loop block
  // RETURN -1; (3482)
  {
    reentryGuard = 0;
    return -1;
  }
}
