/*
  File GENERATExGEN_CLASS8xGET_INIT_LIT.c generated by XCOM-I, 2024-08-08
  04:32:26.
*/

#include "runtimeC.h"

descriptor_t *
GENERATExGEN_CLASS8xGET_INIT_LIT (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (descriptor_t *)0;
    }
  reentryGuard
      = guardReentry (reentryGuard, "GENERATExGEN_CLASS8xGET_INIT_LIT");
  // CALL DECODEPIP(OP); (14077)
  {
    putBITp (16, mGENERATExDECODEPIPxOP,
             getBIT (16, mGENERATExGEN_CLASS8xGET_INIT_LITxOP));
    GENERATExDECODEPIP (0);
  }
  // IF TAG1 ~= LIT THEN (14078)
  if (1 & (xNEQ (COREHALFWORD (mTAG1), BYTE0 (mLIT))))
    // CALL ERRORS(CLASS_DI, 105); (14079)
    {
      putBITp (16, mERRORSxCLASS, getBIT (8, mCLASS_DI));
      putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(105)));
      ERRORS (0);
    }
  // PTR = GET_STACK_ENTRY; (14080)
  {
    int32_t numberRHS = (int32_t)(GENERATExGET_STACK_ENTRY (0));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mGENERATExGEN_CLASS8xGET_INIT_LITxPTR, bitRHS);
    bitRHS->inUse = 0;
  }
  // CALL LITERAL(OP1+N, LITTYPE, PTR); (14081)
  {
    putBITp (
        16, mGENERATExLITERALxPTR,
        fixedToBit (32,
                    (int32_t)(xadd (
                        COREHALFWORD (mOP1),
                        COREHALFWORD (mGENERATExGEN_CLASS8xGET_INIT_LITxN)))));
    putBITp (16, mGENERATExLITERALxLTYPE, getBIT (16, mLITTYPE));
    putBITp (16, mGENERATExLITERALxSTACK,
             getBIT (16, mGENERATExGEN_CLASS8xGET_INIT_LITxPTR));
    GENERATExLITERAL (0);
  }
  // LOC(PTR) = OP1 + N; (14082)
  {
    int32_t numberRHS
        = (int32_t)(xadd (COREHALFWORD (mOP1),
                          COREHALFWORD (mGENERATExGEN_CLASS8xGET_INIT_LITxN)));
    putBIT (16,
            getFIXED (mIND_STACK)
                + 73 * (COREHALFWORD (mGENERATExGEN_CLASS8xGET_INIT_LITxPTR))
                + 40 + 2 * (0),
            fixedToBit (16, numberRHS));
  }
  // FORM(PTR) = LIT; (14083)
  {
    descriptor_t *bitRHS = getBIT (8, mLIT);
    putBIT (16,
            getFIXED (mIND_STACK)
                + 73 * (COREHALFWORD (mGENERATExGEN_CLASS8xGET_INIT_LITxPTR))
                + 32 + 2 * (0),
            bitRHS);
    bitRHS->inUse = 0;
  }
  // N = 0; (14084)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mGENERATExGEN_CLASS8xGET_INIT_LITxN, bitRHS);
    bitRHS->inUse = 0;
  }
  // RETURN PTR; (14085)
  {
    reentryGuard = 0;
    return getBIT (16, mGENERATExGEN_CLASS8xGET_INIT_LITxPTR);
  }
}
