/*
  File GENERATExGEN_CLASS0xPOP_ENVIRONMENT.c generated by XCOM-I, 2024-08-08
  04:32:26.
*/

#include "runtimeC.h"

int32_t
GENERATExGEN_CLASS0xPOP_ENVIRONMENT (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard
      = guardReentry (reentryGuard, "GENERATExGEN_CLASS0xPOP_ENVIRONMENT");
  // ENV_LBL(ENV_PTR) = 0; (12753)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mENV_LBL + 2 * (COREHALFWORD (mENV_PTR)), bitRHS);
    bitRHS->inUse = 0;
  }
  // ENV_PTR = (ENV_PTR + ENV_NUM) MOD (ENV_NUM+1); (12754)
  {
    int32_t numberRHS = (int32_t)(xmod (xadd (COREHALFWORD (mENV_PTR), 2), 3));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mENV_PTR, bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
