/*
  File OBJECT_CONDENSERxLABEL_UPDATE.c generated by XCOM-I, 2024-08-09
  12:39:31.
*/

#include "runtimeC.h"

int32_t
OBJECT_CONDENSERxLABEL_UPDATE (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "OBJECT_CONDENSERxLABEL_UPDATE");
  // LOCCTR(CURRENT_ESDID) = LOCCTR(CURRENT_ESDID) - LEN; (14703)
  {
    int32_t numberRHS = (int32_t)(xsubtract (
        getFIXED (mLOCCTR + 4 * getFIXED (mCURRENT_ESDID)),
        COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExLEN)));
    putFIXED (mLOCCTR + 4 * (getFIXED (mCURRENT_ESDID)), numberRHS);
  }
  // PTR = LASTLABEL(CURRENT_ESDID); (14704)
  {
    descriptor_t *bitRHS
        = getBIT (16, mLASTLABEL + 2 * getFIXED (mCURRENT_ESDID));
    putBIT (16, mOBJECT_CONDENSERxLABEL_UPDATExPTR, bitRHS);
    bitRHS->inUse = 0;
  }
  // DO WHILE PTR > 0; (14705)
  while (1 & (xGT (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR), 0)))
    {
      // IF LOCATION(PTR) > CURRENT_ADDRESS THEN (14706)
      if (1
          & (xGT (getFIXED (
                      getFIXED (mLAB_LOC)
                      + 8 * (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR))
                      + 0 + 4 * (0)),
                  getFIXED (mWORKSEG + 4 * getFIXED (mCURRENT_ESDID)))))
        // LOCATION(PTR) = LOCATION(PTR) - LEN; (14707)
        {
          int32_t numberRHS = (int32_t)(xsubtract (
              getFIXED (
                  getFIXED (mLAB_LOC)
                  + 8 * (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR)) + 0
                  + 4 * (0)),
              COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExLEN)));
          putFIXED (
              getFIXED (mLAB_LOC)
                  + 8 * (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR)) + 0
                  + 4 * (0),
              numberRHS);
        }
      // ELSE (14708)
      else
        // IF LOCATION(PTR) >= 0 THEN (14709)
        if (1
            & (xGE (
                getFIXED (
                    getFIXED (mLAB_LOC)
                    + 8 * (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR))
                    + 0 + 4 * (0)),
                0)))
          // RETURN; (14710)
          {
            reentryGuard = 0;
            return 0;
          }
      // PTR = LOCATION_LINK(PTR); (14711)
      {
        descriptor_t *bitRHS = getBIT (
            16, getFIXED (mLAB_LOC)
                    + 8 * (COREHALFWORD (mOBJECT_CONDENSERxLABEL_UPDATExPTR))
                    + 6 + 2 * (0));
        putBIT (16, mOBJECT_CONDENSERxLABEL_UPDATExPTR, bitRHS);
        bitRHS->inUse = 0;
      }
    } // End of DO WHILE block
  {
    reentryGuard = 0;
    return 0;
  }
}
