#		+-----------------------------------------------+
#		+						+
#		+   This file is no longer used for anything.	+
#		+   Don't be deceived into thinking it is used  +
#		+   for Win32 builds of Virtual AGC.		+
#		+						+
#		+-----------------------------------------------+


# Copyright 2003-4 Ronald S. Burkey <info@sandroid.org>
# 
# This file is part of yaAGC.
#
# yaAGC is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# yaAGC is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with yaAGC; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
# Filename:	Makefile.Win32
# Purpose:	Makefile for the yaAGC Validation Suite.
# Mods:		07/17/04 RSB.	Began.
#		08/30/04 RSB	Loosened up error checking in the validation
#				suite build to work around some yaYUL bugs.

ifndef PREFIX
PREFIX=/mingw
endif
SSOURCE:=$(wildcard *.s)

default:	Validation.bin

Validation.bin:	${SSOURCE} ../yaYUL/yaYUL.exe
	-../yaYUL/yaYUL.exe --force Validation.s >Validation.lst
	mv Validation.s.bin Validation.bin

clean:
	-rm -f Validation.bin Validation.lst Validation.s.bin Validation.txt
	
install:	default
	cp -a Validation.bin ${PREFIX}/bin


