/*
  File MOVE_LOOP_STACK.c generated by XCOM-I, 2024-08-09 12:38:53.
*/

#include "runtimeC.h"

int32_t
MOVE_LOOP_STACK (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "MOVE_LOOP_STACK");
  // LOOP_HEAD(ST) = LOOP_HEAD(ST1); (2458)
  {
    descriptor_t *bitRHS = getBIT (16, mLOOP_HEAD + 2 * COREHALFWORD (mST1));
    putBIT (16, mLOOP_HEAD + 2 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  // LOOP_END(ST) = LOOP_END(ST1); (2459)
  {
    descriptor_t *bitRHS = getBIT (16, mLOOP_END + 2 * COREHALFWORD (mST1));
    putBIT (16, mLOOP_END + 2 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  // AR_SIZE(ST) = AR_SIZE(ST1); (2460)
  {
    descriptor_t *bitRHS = getBIT (16, mAR_SIZE + 2 * COREHALFWORD (mST1));
    putBIT (16, mAR_SIZE + 2 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  // ADJACENT(ST) = ADJACENT(ST1); (2461)
  {
    descriptor_t *bitRHS = getBIT (8, mADJACENT + 1 * COREHALFWORD (mST1));
    putBIT (8, mADJACENT + 1 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  // REF_TO_DSUB(ST) = REF_TO_DSUB(ST1); (2462)
  {
    descriptor_t *bitRHS = getBIT (8, mREF_TO_DSUB + 1 * COREHALFWORD (mST1));
    putBIT (8, mREF_TO_DSUB + 1 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  // ASSIGN(ST) = ASSIGN(ST1); (2463)
  {
    descriptor_t *bitRHS = getBIT (8, mASSIGN + 1 * COREHALFWORD (mST1));
    putBIT (8, mASSIGN + 1 * (COREHALFWORD (mST)), bitRHS);
    bitRHS->inUse = 0;
  }
  {
    reentryGuard = 0;
    return 0;
  }
}
