# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Borealis.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2017-01-30 MAS	Cleaned up from Aurora12 Makefile.

BASENAME=Borealis
EXTRA_YAYUL_ARGS+=--blk2 --parity

# Borealis, being a custom program, will never have a binsource.
NO_BINSOURCE=yes

include ../Makefile.inc
