# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Aurora (revision 12).
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2016-09-20 JL	Adapted from similar Luminary 099 Makefile.
#		2016-10-04 JL	Change to use Makefile.inc.

BASENAME=Aurora12
include ../Makefile.inc
