# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for LUM99R2.
#		(The source code for the Lunar Module's (LM)
#		Apollo Guidance Computer (AGC), Apollo 11, Rev 2.)
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2009-06-05 RSB	Adapted from similar Comanche 055
#				Makefile.
#		2009-07-04 RSB	Added --html switch.
#		2011-05-03 JL	Fixed so that errors will cause rebuild next
#				time make is run. Point to moved Oct2Bin.
#		2012-09-16 JL	Updated to match tools dir changes.
#		2016-10-04 JL	Change to use Makefile.inc.
#		2017-03-03 RSB	Adapted this Luminary 99 Rev 2 Makefile from
#				the corresponding Luminary 99 Rev 1 file.

BASENAME=LUM99R2
NO_BINSOURCE=yes

include ../Makefile.inc
