# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Zerlina 56.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	http://www.ibiblio.org/apollo
# Mod history:	2017-07-28 MAS	Created.

BASENAME=Zerlina56

include ../Makefile.inc
