/* This is a test of parameter datatype promotion, particularly in procedure 
   parameters and return values. */
   
MYPROC:
PROCEDURE(F, B, C) BIT(4);
   DECLARE F FIXED, B BIT(5), C CHARACTER;
   OUTPUT = 'F = ' || F;
   OUTPUT = 'B = ' || B;
   OUTPUT = 'C = ' || C;
   RETURN F + B;
END;

DECLARE F1 FIXED INITIAL(12345), F2 FIXED INITIAL(678), F3 FIXED INITIAL(912);
DECLARE B1 BIT(5) INITIAL(67), B2 BIT(3) INITIAL(7), B3 BIT(22) INITIAL(0);
DECLARE C1 CHARACTER INITIAL('Hello'), C2 CHARACTER INITIAL(5987);

CALL MYPROC(F1, B1, C1);
CALL MYPROC(F2, B2, C2);
CALL MYPROC(F3, B3, C1);
CALL MYPROC(F1, B2, F2);
CALL MYPROC(F1, B2, B3);
CALL MYPROC(B1, B2, C1);
CALL MYPROC(F1, F2, C2);

OUTPUT = MYPROC(F1, B1, C1);
OUTPUT = MYPROC(F2, B2, C2);
OUTPUT = MYPROC(F3, B3, C1);
OUTPUT = MYPROC(F1, B2, F2);
OUTPUT = MYPROC(F1, B2, B3);
OUTPUT = MYPROC(B1, B2, C1);
OUTPUT = MYPROC(F1, F2, C2);
