# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Luminary revision 210.
#		(The source code for the Lunar Module's (LM)
#		Apollo Guidance Computer (AGC) for Apollo 15-17.)
# Contact:	Ron Burkey <info@sandroid.org>.
# History:	2016-11-16 	JL 	Created.

BASENAME=Luminary210
include ../Makefile.inc
