/*
  File GET_STMT_VARS.c generated by XCOM-I, 2024-08-08 04:31:35.
*/

#include "runtimeC.h"

int32_t
GET_STMT_VARS (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (int32_t)0;
    }
  reentryGuard = guardReentry (reentryGuard, "GET_STMT_VARS");
  // IF PROC_TRACE THEN (2126)
  if (1 & (bitToFixed (getBIT (8, mPROC_TRACE))))
    // OUTPUT='GET_STMT_VARS('||STMT#||','||PTR||')'; (2127)
    {
      descriptor_t *stringRHS;
      stringRHS
          = xsCAT (xsCAT (xsCAT (xsCAT (cToDescriptor (NULL, "GET_STMT_VARS("),
                                        bitToCharacter (getBIT (
                                            16, mGET_STMT_VARSxSTMTp))),
                                 cToDescriptor (NULL, ",")),
                          fixedToCharacter (getFIXED (mGET_STMT_VARSxPTR))),
                   cToDescriptor (NULL, ")"));
      OUTPUT (0, stringRHS);
      stringRHS->inUse = 0;
    }
  // NAME_ASSIGN,RHS_PTR,LHS_PTR,VAR_INX,PTR_INX = 0; (2128)
  {
    int32_t numberRHS = (int32_t)(0);
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mGET_STMT_VARSxNAME_ASSIGN, bitRHS);
    putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
    putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mVAR_INX, bitRHS);
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mPTR_INX, bitRHS);
    bitRHS->inUse = 0;
  }
  // DO FOREVER; (2129)
  while (1 & (1))
    {
      // CALL DECODEPOP(PTR); (2130)
      {
        putBITp (16, mDECODEPOPxCTR,
                 fixedToBit (32, (int32_t)(getFIXED (mGET_STMT_VARSxPTR))));
        DECODEPOP (0);
      }
      // IF OPCODE=ADLP | OPCODE=DLPE | OPCODE=TDCL | OPCODE=LBL THEN (2131)
      if (1
          & (xOR (
              xOR (xOR (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mADLP)),
                        xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mDLPE))),
                   xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mTDCL))),
              xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mLBL)))))
        // PTR = LAST_OP(PTR); (2132)
        {
          descriptor_t *bitRHS
              = (putBITp (16, mLAST_OPxLOC,
                          fixedToBit (
                              32, (int32_t)(getFIXED (mGET_STMT_VARSxPTR)))),
                 LAST_OP (0));
          int32_t numberRHS;
          numberRHS = bitToFixed (bitRHS);
          putFIXED (mGET_STMT_VARSxPTR, numberRHS);
          bitRHS->inUse = 0;
        }
      // ELSE (2133)
      else
        // ESCAPE; (2134)
        break;
    } // End of DO WHILE block
  // IF OPCODE=SMRK | OPCODE=IMRK | OPCODE=CLBL | OPCODE=EDCL | OPCODE=XREC |
  // OPCODE=PXRC THEN (2135)
  if (1
      & (xOR (
          xOR (xOR (xOR (xOR (xEQ (COREHALFWORD (mOPCODE),
                                   COREHALFWORD (mSMRK)),
                              xEQ (COREHALFWORD (mOPCODE),
                                   COREHALFWORD (mIMRK))),
                         xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mCLBL))),
                    xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mEDCL))),
               xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mXREC))),
          xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mPXRC)))))
    // RETURN; (2136)
    {
      reentryGuard = 0;
      return 0;
    }
  // IF ASSIGN_TYPE THEN (2137)
  if (1 & (bitToFixed (GET_STMT_VARSxASSIGN_TYPE (0))))
    // DO; (2138)
    {
    rs2:;
      // DO J = PTR+2 TO PTR+NUMOP; (2139)
      {
        int32_t from47, to47, by47;
        from47 = xadd (getFIXED (mGET_STMT_VARSxPTR), 2);
        to47 = xadd (getFIXED (mGET_STMT_VARSxPTR), COREHALFWORD (mNUMOP));
        by47 = 1;
        for (putBIT (16, mGET_STMT_VARSxJ, fixedToBit (16, from47));
             bitToFixed (getBIT (16, mGET_STMT_VARSxJ)) <= to47;
             putBIT (16, mGET_STMT_VARSxJ,
                     fixedToBit (16, bitToFixed (getBIT (16, mGET_STMT_VARSxJ))
                                         + by47)))
          {
            // CALL STACK_OPERAND_VARS(J); (2140)
            {
              putBITp (16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                       getBIT (16, mGET_STMT_VARSxJ));
              GET_STMT_VARSxSTACK_OPERAND_VARS (0);
            }
          }
      } // End of DO for-loop block
      // IF PTR_INX > 0 THEN (2141)
      if (1 & (xGT (COREHALFWORD (mPTR_INX), 0)))
        // LHS_PTR = GET_EXP_VARS_CELL; (2142)
        {
          int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
          putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
        }
      // VAR_INX,PTR_INX = 0; (2143)
      {
        int32_t numberRHS = (int32_t)(0);
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mVAR_INX, bitRHS);
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mPTR_INX, bitRHS);
        bitRHS->inUse = 0;
      }
      // CALL STACK_OPERAND_VARS(PTR+1); (2144)
      {
        putBITp (16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                 fixedToBit (
                     32, (int32_t)(xadd (getFIXED (mGET_STMT_VARSxPTR), 1))));
        GET_STMT_VARSxSTACK_OPERAND_VARS (0);
      }
      // RHS_PTR = GET_EXP_VARS_CELL; (2145)
      {
        int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
        putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
      }
    es2:;
    } // End of DO block
  // ELSE (2146)
  else
    // IF OPCODE=FBRA | OPCODE=RTRN THEN (2147)
    if (1
        & (xOR (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mFBRA)),
                xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mRTRN)))))
      // DO; (2148)
      {
      rs3:;
        // IF NUMOP>0 THEN (2149)
        if (1 & (xGT (COREHALFWORD (mNUMOP), 0)))
          // DO; (2150)
          {
          rs3s1:;
            // IF OPCODE=FBRA THEN (2151)
            if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mFBRA))))
              // CALL SEARCH_EXPRESSION(PTR+2); (2152)
              {
                putBITp (
                    16, mSEARCH_EXPRESSIONxCTR,
                    fixedToBit (32, (int32_t)(xadd (
                                        getFIXED (mGET_STMT_VARSxPTR), 2))));
                SEARCH_EXPRESSION (0);
              }
            // ELSE (2153)
            else
              // CALL SEARCH_EXPRESSION(PTR+1); (2154)
              {
                putBITp (
                    16, mSEARCH_EXPRESSIONxCTR,
                    fixedToBit (32, (int32_t)(xadd (
                                        getFIXED (mGET_STMT_VARSxPTR), 1))));
                SEARCH_EXPRESSION (0);
              }
            // RHS_PTR = GET_EXP_VARS_CELL; (2155)
            {
              int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
              putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
            }
          es3s1:;
          } // End of DO block
      es3:;
      } // End of DO block
    // ELSE (2156)
    else
      // IF OPCODE=XXND THEN (2157)
      if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mXXND))))
        // DO; (2158)
        {
        rs4:;
          // PTR = LAST_OP(PTR); (2159)
          {
            descriptor_t *bitRHS
                = (putBITp (16, mLAST_OPxLOC,
                            fixedToBit (
                                32, (int32_t)(getFIXED (mGET_STMT_VARSxPTR)))),
                   LAST_OP (0));
            int32_t numberRHS;
            numberRHS = bitToFixed (bitRHS);
            putFIXED (mGET_STMT_VARSxPTR, numberRHS);
            bitRHS->inUse = 0;
          }
          // OPCODE = POPCODE(PTR); (2160)
          {
            descriptor_t *bitRHS
                = (putBITp (16, mPOPCODExCTR,
                            fixedToBit (
                                32, (int32_t)(getFIXED (mGET_STMT_VARSxPTR)))),
                   POPCODE (0));
            putBIT (16, mOPCODE, bitRHS);
            bitRHS->inUse = 0;
          }
          // IF CLASS0(OPCODE) = 8 THEN (2161)
          if (1 & (xEQ (BYTE0 (mCLASS0 + 1 * COREHALFWORD (mOPCODE)), 8)))
            // DO; (2162)
            {
            rs4s1:;
              // PTR_INX = PTR_INX + 1; (2163)
              {
                int32_t numberRHS
                    = (int32_t)(xadd (COREHALFWORD (mPTR_INX), 1));
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (16, mPTR_INX, bitRHS);
                bitRHS->inUse = 0;
              }
              // EXP_PTRS(PTR_INX) = HALMAT_PTR(PTR); (2164)
              {
                int32_t numberRHS = (int32_t)(getFIXED (
                    mHALMAT_PTR + 4 * getFIXED (mGET_STMT_VARSxPTR)));
                putFIXED (mEXP_PTRS + 4 * (COREHALFWORD (mPTR_INX)),
                          numberRHS);
              }
              // RHS_PTR = GET_EXP_VARS_CELL; (2165)
              {
                int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
                putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
              }
            es4s1:;
            } // End of DO block
          // ELSE (2166)
          else
            // IF CLASS0(OPCODE) = 9 THEN (2167)
            if (1 & (xEQ (BYTE0 (mCLASS0 + 1 * COREHALFWORD (mOPCODE)), 9)))
              // DO; (2168)
              {
              rs4s2:;
                // PTR = NEXT_OP(HALMAT_PTR(PTR)); (2169)
                {
                  descriptor_t *bitRHS
                      = (putBITp (
                             16, mNEXT_OPxLOC,
                             fixedToBit (
                                 32,
                                 (int32_t)(getFIXED (
                                     mHALMAT_PTR
                                     + 4 * getFIXED (mGET_STMT_VARSxPTR))))),
                         NEXT_OP (0));
                  int32_t numberRHS;
                  numberRHS = bitToFixed (bitRHS);
                  putFIXED (mGET_STMT_VARSxPTR, numberRHS);
                  bitRHS->inUse = 0;
                }
                // OPCODE = POPCODE(PTR); (2170)
                {
                  descriptor_t *bitRHS
                      = (putBITp (16, mPOPCODExCTR,
                                  fixedToBit (32, (int32_t)(getFIXED (
                                                      mGET_STMT_VARSxPTR)))),
                         POPCODE (0));
                  putBIT (16, mOPCODE, bitRHS);
                  bitRHS->inUse = 0;
                }
                // DO WHILE OPCODE ~= XXND; (2171)
                while (1
                       & (xNEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mXXND))))
                  {
                    // IF (OPCODE=XXAR) & (X_BITS(PTR+1) = 0) THEN (2172)
                    if (1
                        & (xAND (
                            xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mXXAR)),
                            xEQ (bitToFixed ((
                                     putBITp (
                                         16, mX_BITSxCTR,
                                         fixedToBit (
                                             32,
                                             (int32_t)(xadd (
                                                 getFIXED (mGET_STMT_VARSxPTR),
                                                 1)))),
                                     X_BITS (0))),
                                 0))))
                      // CALL STACK_OPERAND_VARS(PTR+1); (2173)
                      {
                        putBITp (
                            16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                            fixedToBit (
                                32, (int32_t)(xadd (
                                        getFIXED (mGET_STMT_VARSxPTR), 1))));
                        GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                      }
                    // ELSE (2174)
                    else
                      // IF OPCODE = WRIT THEN (2175)
                      if (1
                          & (xEQ (COREHALFWORD (mOPCODE),
                                  COREHALFWORD (mWRIT))))
                        // RHS_PTR = GET_EXP_VARS_CELL; (2176)
                        {
                          int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
                          putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
                        }
                      // ELSE (2177)
                      else
                        // IF (OPCODE=READ | OPCODE=RDAL) & PTR_INX>0 THEN
                        // (2178)
                        if (1
                            & (xAND (xOR (xEQ (COREHALFWORD (mOPCODE),
                                               COREHALFWORD (mREAD)),
                                          xEQ (COREHALFWORD (mOPCODE),
                                               COREHALFWORD (mRDAL))),
                                     xGT (COREHALFWORD (mPTR_INX), 0))))
                          // LHS_PTR = GET_EXP_VARS_CELL; (2179)
                          {
                            int32_t numberRHS
                                = (int32_t)(GET_EXP_VARS_CELL (0));
                            putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
                          }
                    // PTR = NEXT_OP(PTR); (2180)
                    {
                      descriptor_t *bitRHS
                          = (putBITp (
                                 16, mNEXT_OPxLOC,
                                 fixedToBit (32, (int32_t)(getFIXED (
                                                     mGET_STMT_VARSxPTR)))),
                             NEXT_OP (0));
                      int32_t numberRHS;
                      numberRHS = bitToFixed (bitRHS);
                      putFIXED (mGET_STMT_VARSxPTR, numberRHS);
                      bitRHS->inUse = 0;
                    }
                    // OPCODE = POPCODE(PTR); (2181)
                    {
                      descriptor_t *bitRHS
                          = (putBITp (
                                 16, mPOPCODExCTR,
                                 fixedToBit (32, (int32_t)(getFIXED (
                                                     mGET_STMT_VARSxPTR)))),
                             POPCODE (0));
                      putBIT (16, mOPCODE, bitRHS);
                      bitRHS->inUse = 0;
                    }
                  } // End of DO WHILE block
              es4s2:;
              } // End of DO block
        es4:;
        } // End of DO block
      // ELSE (2182)
      else
        // IF OPCODE=DFOR | OPCODE=AFOR | OPCODE=CFOR THEN (2183)
        if (1
            & (xOR (xOR (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mDFOR)),
                         xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mAFOR))),
                    xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mCFOR)))))
          // DO; (2184)
          {
          rs5:;
            // IF DFOR_LOC ~= 0 THEN (2185)
            if (1 & (xNEQ (COREHALFWORD (mDFOR_LOC), 0)))
              // DO; (2186)
              {
              rs5s1:;
                // J = DFOR_LOC; (2187)
                {
                  descriptor_t *bitRHS = getBIT (16, mDFOR_LOC);
                  putBIT (16, mGET_STMT_VARSxJ, bitRHS);
                  bitRHS->inUse = 0;
                }
                // DFOR_LOC = 0; (2188)
                {
                  int32_t numberRHS = (int32_t)(0);
                  descriptor_t *bitRHS;
                  bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                  putBIT (16, mDFOR_LOC, bitRHS);
                  bitRHS->inUse = 0;
                }
              es5s1:;
              } // End of DO block
            // ELSE (2189)
            else
              // J = PTR; (2190)
              {
                int32_t numberRHS = (int32_t)(getFIXED (mGET_STMT_VARSxPTR));
                descriptor_t *bitRHS;
                bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                putBIT (16, mGET_STMT_VARSxJ, bitRHS);
                bitRHS->inUse = 0;
              }
            // DO WHILE J <= PTR; (2191)
            while (1
                   & (xLE (COREHALFWORD (mGET_STMT_VARSxJ),
                           getFIXED (mGET_STMT_VARSxPTR))))
              {
                // OPCODE = POPCODE(J); (2192)
                {
                  descriptor_t *bitRHS
                      = (putBITp (16, mPOPCODExCTR,
                                  getBIT (16, mGET_STMT_VARSxJ)),
                         POPCODE (0));
                  putBIT (16, mOPCODE, bitRHS);
                  bitRHS->inUse = 0;
                }
                // IF OPCODE = DFOR THEN (2193)
                if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mDFOR))))
                  // DO; (2194)
                  {
                  rs5s2s1:;
                    // CALL STACK_OPERAND_VARS(J+2); (2195)
                    {
                      putBITp (
                          16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                          fixedToBit (
                              32, (int32_t)(xadd (
                                      COREHALFWORD (mGET_STMT_VARSxJ), 2))));
                      GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                    }
                    // IF PTR_INX > 0 THEN (2196)
                    if (1 & (xGT (COREHALFWORD (mPTR_INX), 0)))
                      // LHS_PTR = GET_EXP_VARS_CELL; (2197)
                      {
                        int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
                        putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
                      }
                    // ELSE (2198)
                    else
                      // VAR_INX = 0; (2199)
                      {
                        int32_t numberRHS = (int32_t)(0);
                        descriptor_t *bitRHS;
                        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
                        putBIT (16, mVAR_INX, bitRHS);
                        bitRHS->inUse = 0;
                      }
                    // DO K = J+3 TO J+POPNUM(J); (2200)
                    {
                      int32_t from48, to48, by48;
                      from48 = xadd (COREHALFWORD (mGET_STMT_VARSxJ), 3);
                      to48 = xadd (
                          COREHALFWORD (mGET_STMT_VARSxJ),
                          bitToFixed ((putBITp (16, mPOPNUMxCTR,
                                                getBIT (16, mGET_STMT_VARSxJ)),
                                       POPNUM (0))));
                      by48 = 1;
                      for (putBIT (16, mGET_STMT_VARSxK,
                                   fixedToBit (16, from48));
                           bitToFixed (getBIT (16, mGET_STMT_VARSxK)) <= to48;
                           putBIT (16, mGET_STMT_VARSxK,
                                   fixedToBit (16, bitToFixed (getBIT (
                                                       16, mGET_STMT_VARSxK))
                                                       + by48)))
                        {
                          // CALL STACK_OPERAND_VARS(K); (2201)
                          {
                            putBITp (16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                                     getBIT (16, mGET_STMT_VARSxK));
                            GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                          }
                        }
                    } // End of DO for-loop block
                  es5s2s1:;
                  } // End of DO block
                // ELSE (2202)
                else
                  // IF OPCODE=AFOR | OPCODE=CFOR THEN (2203)
                  if (1
                      & (xOR (
                          xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mAFOR)),
                          xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mCFOR)))))
                    // CALL STACK_OPERAND_VARS(J+1); (2204)
                    {
                      putBITp (
                          16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                          fixedToBit (
                              32, (int32_t)(xadd (
                                      COREHALFWORD (mGET_STMT_VARSxJ), 1))));
                      GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                    }
                // J = NEXT_OP(J); (2205)
                {
                  descriptor_t *bitRHS
                      = (putBITp (16, mNEXT_OPxLOC,
                                  getBIT (16, mGET_STMT_VARSxJ)),
                         NEXT_OP (0));
                  putBIT (16, mGET_STMT_VARSxJ, bitRHS);
                  bitRHS->inUse = 0;
                }
              } // End of DO WHILE block
            // RHS_PTR = GET_EXP_VARS_CELL; (2206)
            {
              int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
              putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
            }
          es5:;
          } // End of DO block
        // ELSE (2207)
        else
          // IF OPCODE=CTST | OPCODE=DCAS THEN (2208)
          if (1
              & (xOR (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mCTST)),
                      xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mDCAS)))))
            // DO; (2209)
            {
            rs6:;
              // CALL STACK_OPERAND_VARS(PTR+NUMOP); (2210)
              {
                putBITp (16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                         fixedToBit (
                             32, (int32_t)(xadd (getFIXED (mGET_STMT_VARSxPTR),
                                                 COREHALFWORD (mNUMOP)))));
                GET_STMT_VARSxSTACK_OPERAND_VARS (0);
              }
              // RHS_PTR = GET_EXP_VARS_CELL; (2211)
              {
                int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
                putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
              }
            es6:;
            } // End of DO block
          // ELSE (2212)
          else
            // IF OPCODE = PMIN THEN (2213)
            if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mPMIN))))
              // DO; (2214)
              {
              rs7:;
                // CALL GET_PMACRO_ARGS(PTR); (2215)
                {
                  putBITp (16, mGET_STMT_VARSxGET_PMACRO_ARGSxLOC,
                           fixedToBit (
                               32, (int32_t)(getFIXED (mGET_STMT_VARSxPTR))));
                  GET_STMT_VARSxGET_PMACRO_ARGS (0);
                }
              es7:;
              } // End of DO block
            // ELSE (2216)
            else
              // IF OPCODE >=WAIT & OPCODE <=SCHD THEN (2217)
              if (1
                  & (xAND (
                      xGE (COREHALFWORD (mOPCODE), COREHALFWORD (mWAIT)),
                      xLE (COREHALFWORD (mOPCODE), COREHALFWORD (mSCHD)))))
                // CALL GET_REALTIME_ARGS; (2218)
                GET_STMT_VARSxGET_REALTIME_ARGS (0);
              // ELSE (2219)
              else
                // IF OPCODE=ERON THEN (2220)
                if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mERON))))
                  // DO; (2221)
                  {
                  rs8:;
                    // IF NUMOP = 2 THEN (2222)
                    if (1 & (xEQ (COREHALFWORD (mNUMOP), 2)))
                      // IF TYPE_BITS(PTR+2) ~= INL THEN (2223)
                      if (1
                          & (xNEQ (
                              bitToFixed ((
                                  putBITp (16, mTYPE_BITSxCTR,
                                           fixedToBit (
                                               32, (int32_t)(xadd (
                                                       getFIXED (
                                                           mGET_STMT_VARSxPTR),
                                                       2)))),
                                  TYPE_BITS (0))),
                              COREHALFWORD (mINL))))
                        // DO; (2224)
                        {
                        rs8s1:;
                          // CALL STACK_OPERAND_VARS(PTR+2); (2225)
                          {
                            putBITp (16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                                     fixedToBit (
                                         32, (int32_t)(xadd (
                                                 getFIXED (mGET_STMT_VARSxPTR),
                                                 2))));
                            GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                          }
                          // IF PTR_INX > 0 THEN (2226)
                          if (1 & (xGT (COREHALFWORD (mPTR_INX), 0)))
                            // LHS_PTR = GET_EXP_VARS_CELL; (2227)
                            {
                              int32_t numberRHS
                                  = (int32_t)(GET_EXP_VARS_CELL (0));
                              putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
                            }
                        es8s1:;
                        } // End of DO block
                  es8:;
                  } // End of DO block
                // ELSE (2228)
                else
                  // IF OPCODE = BRA THEN (2229)
                  if (1 & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mBRA))))
                    // DO; (2230)
                    {
                    rs9:;
                      // CALL STACK_OPERAND_VARS(PTR+1); (2231)
                      {
                        putBITp (
                            16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                            fixedToBit (
                                32, (int32_t)(xadd (
                                        getFIXED (mGET_STMT_VARSxPTR), 1))));
                        GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                      }
                      // RHS_PTR = GET_EXP_VARS_CELL; (2232)
                      {
                        int32_t numberRHS = (int32_t)(GET_EXP_VARS_CELL (0));
                        putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
                      }
                    es9:;
                    } // End of DO block
                  // ELSE (2233)
                  else
                    // IF OPCODE = XFIL THEN (2234)
                    if (1
                        & (xEQ (COREHALFWORD (mOPCODE), COREHALFWORD (mXFIL))))
                      // DO; (2235)
                      {
                      rs10:;
                        // CALL STACK_OPERAND_VARS(PTR+2); (2236)
                        {
                          putBITp (
                              16, mGET_STMT_VARSxSTACK_OPERAND_VARSxLOC,
                              fixedToBit (
                                  32, (int32_t)(xadd (
                                          getFIXED (mGET_STMT_VARSxPTR), 2))));
                          GET_STMT_VARSxSTACK_OPERAND_VARS (0);
                        }
                        // DO CASE X_BITS(PTR+2); (2237)
                        {
                        rs10s1:
                          switch (bitToFixed ((
                              putBITp (
                                  16, mX_BITSxCTR,
                                  fixedToBit (
                                      32,
                                      (int32_t)(xadd (
                                          getFIXED (mGET_STMT_VARSxPTR), 2)))),
                              X_BITS (0))))
                            {
                            case 0:
                              // IF PTR_INX>0 THEN (2239)
                              if (1 & (xGT (COREHALFWORD (mPTR_INX), 0)))
                                {
                                  int32_t numberRHS
                                      = (int32_t)(GET_EXP_VARS_CELL (0));
                                  putFIXED (mGET_STMT_VARSxLHS_PTR, numberRHS);
                                }
                              break;
                            case 1:
                              // RHS_PTR = GET_EXP_VARS_CELL; (2241)
                              {
                                int32_t numberRHS
                                    = (int32_t)(GET_EXP_VARS_CELL (0));
                                putFIXED (mGET_STMT_VARSxRHS_PTR, numberRHS);
                              }
                              break;
                            }
                        } // End of DO CASE block
                      es10:;
                      } // End of DO block
                    // ELSE (2241)
                    else
                      // CALL ERRORS (CLASS_BI, 216, ' '||HEX(OPCODE,3));
                      // (2242)
                      {
                        putBITp (16, mERRORSxCLASS, getBIT (16, mCLASS_BI));
                        putBITp (16, mERRORSxNUM,
                                 fixedToBit (32, (int32_t)(216)));
                        putCHARACTERp (
                            mERRORSxTEXT,
                            xsCAT (
                                cToDescriptor (NULL, " "),
                                (putFIXED (mHEXxHVAL, COREHALFWORD (mOPCODE)),
                                 putFIXED (mHEXxN, 3), HEX (0))));
                        ERRORS (0);
                      }
  // IF RHS_PTR = 0 THEN (2243)
  if (1 & (xEQ (getFIXED (mGET_STMT_VARSxRHS_PTR), 0)))
    // IF LHS_PTR = 0 THEN (2244)
    if (1 & (xEQ (getFIXED (mGET_STMT_VARSxLHS_PTR), 0)))
      // RETURN; (2245)
      {
        reentryGuard = 0;
        return 0;
      }
  // DO FOREVER; (2246)
  while (1 & (1))
    {
      // IF STMT_DATA_CELL = - 1 THEN (2247)
      if (1 & (xEQ (getFIXED (mSTMT_DATA_CELL), -1)))
        // CALL ERRORS (CLASS_BI, 218, ' '||STMT#); (2248)
        {
          putBITp (16, mERRORSxCLASS, getBIT (16, mCLASS_BI));
          putBITp (16, mERRORSxNUM, fixedToBit (32, (int32_t)(218)));
          putCHARACTERp (
              mERRORSxTEXT,
              xsCAT (cToDescriptor (NULL, " "),
                     bitToCharacter (getBIT (16, mGET_STMT_VARSxSTMTp))));
          ERRORS (0);
        }
      // CALL LOCATE(STMT_DATA_CELL,ADDR(VMEM_F),0); (2249)
      {
        putFIXED (mLOCATExPTR, getFIXED (mSTMT_DATA_CELL));
        putFIXED (mLOCATExBVAR, ADDR ("VMEM_F", 0x80000000, NULL, 0));
        putBITp (8, mLOCATExFLAGS, fixedToBit (32, (int32_t)(0)));
        LOCATE (0);
      }
      // CELL_STMT# = SHR(VMEM_F(7),16); (2250)
      {
        int32_t numberRHS
            = (int32_t)(SHR (getFIXED (getFIXED (mVMEM_F) + 4 * 7), 16));
        descriptor_t *bitRHS;
        bitRHS = fixedToBit (32, (int32_t)(numberRHS));
        putBIT (16, mGET_STMT_VARSxCELL_STMTp, bitRHS);
        bitRHS->inUse = 0;
      }
      // IF CELL_STMT# = STMT# THEN (2251)
      if (1
          & (xEQ (COREHALFWORD (mGET_STMT_VARSxCELL_STMTp),
                  COREHALFWORD (mGET_STMT_VARSxSTMTp))))
        // DO; (2252)
        {
        rs11s1:;
          // CALL DISP(MODF); (2253)
          {
            putBITp (8, mDISPxFLAGS, getBIT (8, mMODF));
            DISP (0);
          }
          // VMEM_F(4) = LHS_PTR; (2254)
          {
            int32_t numberRHS = (int32_t)(getFIXED (mGET_STMT_VARSxLHS_PTR));
            putFIXED (getFIXED (mVMEM_F) + 4 * (4), numberRHS);
          }
          // VMEM_F(5) = RHS_PTR; (2255)
          {
            int32_t numberRHS = (int32_t)(getFIXED (mGET_STMT_VARSxRHS_PTR));
            putFIXED (getFIXED (mVMEM_F) + 4 * (5), numberRHS);
          }
          // IF NAME_ASSIGN THEN (2256)
          if (1 & (bitToFixed (getBIT (16, mGET_STMT_VARSxNAME_ASSIGN))))
            // VMEM_F(6) = VMEM_F(6) |  2048; (2257)
            {
              int32_t numberRHS = (int32_t)(xOR (
                  getFIXED (getFIXED (mVMEM_F) + 4 * 6), 2048));
              putFIXED (getFIXED (mVMEM_F) + 4 * (6), numberRHS);
            }
          // RETURN; (2258)
          {
            reentryGuard = 0;
            return 0;
          }
        es11s1:;
        } // End of DO block
      // STMT_DATA_CELL = VMEM_F(0); (2259)
      {
        int32_t numberRHS = (int32_t)(getFIXED (getFIXED (mVMEM_F) + 4 * 0));
        putFIXED (mSTMT_DATA_CELL, numberRHS);
      }
    } // End of DO WHILE block
  {
    reentryGuard = 0;
    return 0;
  }
}
