#!/bin/bash
# This shell script runs the CM elements of the Virtual AGC 
# emulation for software version 072 of Artemis (i.e., Colossus 3).

# What all the stuff with PIDS does is to record the process IDs of all the 
# programs we start.  We use this list to terminate all of them if any of 
# them terminates.

# Notice a lot of commented-out lines that say "xterm ...".  It's nicer in 
# a lot of ways to run these various apps inside of X-terminals, but opens
# up so incredibly many windows on the screen that I don't do it normally.
# Just remove the comment symbol from in front of any apps that you want in
# an xterm.  For example, if you want to run yaAGC with the --debug switch.

# If --test-downlink is used, always run yaDSKY in an xterm, or else 
# displaying the digital downlink lists will be really crummy..
xterm -geometry 80x43 -e yadsky $1 --cfg=CM.ini --test-downlink &
PIDS="$!"
xterm -sb -geometry 72x1 -e \
  LM_Simulator --cfg=lm_simulator_nodsky.ini --port=19701 &
PIDS="$! ${PIDS}"
#xterm -sb -geometry 112x40 -e \
  yaAGC --core=Artemis072.bin --cfg=CM.ini $2 &
PIDS="$! ${PIDS}"
export PIDS

# Scan for any of the programs to exit.  
SimStop


