# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:      Makefile for an attempt to reconstruct Sundance revision 306
#               as closely as possible with available information.
#               Sundance 306 is the source code for the Lunar Module's (LM) 
#               Apollo Guidance Computer (AGC) for Apollo 9. This program was
#               created using the mixed-revision SundanceXXX as a starting
#               point, and pulling back features from Luminary 69 believed to
#               have been added based on memos, checklists, observed address
#               changes, or the Sundance GSOPs.
# Contact:	Ron Burkey <info@sandroid.org>.
# History:	2020-07-24 	MAS	Created.

BASENAME=Sundance306ish

EXTRA_YAYUL_ARGS+=--parity
NO_BINSOURCE=yes

include ../Makefile.inc
