# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for a reconstructed, mixed version of Sundance,
#		the software for the Lunar Module's (LM) Apollo Guidance
#		Computer (AGC) for Apollo 9. It has been reconstructed
#		from binary dumps of original core rope program modules.
# Contact:	Ron Burkey <info@sandroid.org>.
# History:	2019-07-27 	MAS	Created.

BASENAME=Sundance306ish

EXTRA_YAYUL_ARGS+=--parity
NO_BINSOURCE=yes

include ../Makefile.inc
