#include "opcode_table.h"

/* Mechanically generated from reengineered-documentation/HALMAT.md's
 * "By Opcode (numeric)" index (Phase 3, M0.2). Operand-role data and
 * exec/disasm handlers are filled in per-opcode, just-in-time, as each
 * is implemented (see Plan.md Phase 3 / M4 bring-up order) -- not
 * hand-authored en masse ahead of need. */

const opcode_desc_t g_opcode_table[179] = {
    { 0x000, 0, "NOP", "No operation", NULL, 0, false, NULL, NULL },
    { 0x001, 0, "EXTN", "Extended (qualified-name) pointer", NULL, 0, false, NULL, NULL },
    { 0x002, 0, "XREC", "End-of-record marker", NULL, 0, false, NULL, NULL },
    { 0x003, 0, "IMRK", "Inline-function statement marker", NULL, 0, false, NULL, NULL },
    { 0x004, 0, "SMRK", "Statement marker", NULL, 0, false, NULL, NULL },
    { 0x005, 0, "PXRC", "Record header, points to closing XREC", NULL, 0, false, NULL, NULL },
    { 0x007, 0, "IFHD", "IF statement header", NULL, 0, false, NULL, NULL },
    { 0x008, 0, "LBL", "Branch destination label", NULL, 0, false, NULL, NULL },
    { 0x009, 0, "BRA", "Unconditional branch", NULL, 0, false, NULL, NULL },
    { 0x00A, 0, "FBRA", "Conditional (false) branch", NULL, 0, false, NULL, NULL },
    { 0x00B, 0, "DCAS", "DO CASE statement header, computed branch", NULL, 0, false, NULL, NULL },
    { 0x00C, 0, "ECAS", "DO CASE statement end / join point", NULL, 0, false, NULL, NULL },
    { 0x00D, 0, "CLBL", "Computed-branch (DO CASE) destination label", NULL, 0, false, NULL, NULL },
    { 0x00E, 0, "DTST", "DO WHILE/UNTIL loop header", NULL, 0, false, NULL, NULL },
    { 0x00F, 0, "ETST", "DO WHILE/UNTIL loop end", NULL, 0, false, NULL, NULL },
    { 0x010, 0, "DFOR", "DO FOR statement header", NULL, 0, false, NULL, NULL },
    { 0x011, 0, "EFOR", "DO FOR statement end", NULL, 0, false, NULL, NULL },
    { 0x012, 0, "CFOR", "DO FOR supplementary WHILE/UNTIL condition test", NULL, 0, false, NULL, NULL },
    { 0x013, 0, "DSMP", "Plain DO; ... END; group header", NULL, 0, false, NULL, NULL },
    { 0x014, 0, "ESMP", "Plain DO; ... END; group end", NULL, 0, false, NULL, NULL },
    { 0x015, 0, "AFOR", "Per-value instruction for list-form DO FOR", NULL, 0, false, NULL, NULL },
    { 0x016, 0, "CTST", "DO WHILE/UNTIL per-cycle condition test", NULL, 0, false, NULL, NULL },
    { 0x017, 0, "ADLP", "Arrayness specifier, brackets array loops", NULL, 0, false, NULL, NULL },
    { 0x018, 0, "DLPE", "End of array/structure specification", NULL, 0, false, NULL, NULL },
    { 0x019, 0, "DSUB", "Array/component subscript specifier", NULL, 0, false, NULL, NULL },
    { 0x01A, 0, "IDLP", "STATIC-array counterpart of ADLP (uniform-value init)", NULL, 0, false, NULL, NULL },
    { 0x01B, 0, "TSUB", "Structure (copy) subscript specifier", NULL, 0, false, NULL, NULL },
    { 0x01D, 0, "PCAL", "Procedure call header", NULL, 0, false, NULL, NULL },
    { 0x01E, 0, "FCAL", "Function call header", NULL, 0, false, NULL, NULL },
    { 0x01F, 0, "READ", "READ statement header", NULL, 0, false, NULL, NULL },
    { 0x020, 0, "RDAL", "READALL statement header", NULL, 0, false, NULL, NULL },
    { 0x021, 0, "WRIT", "WRITE statement header", NULL, 0, false, NULL, NULL },
    { 0x022, 0, "FILE", "File I/O specifier", NULL, 0, false, NULL, NULL },
    { 0x025, 0, "XXST", "I/O statement start, carries I/O-kind code", NULL, 0, false, NULL, NULL },
    { 0x026, 0, "XXND", "I/O statement end", NULL, 0, false, NULL, NULL },
    { 0x027, 0, "XXAR", "I/O statement argument", NULL, 0, false, NULL, NULL },
    { 0x02A, 0, "TDEF", "Task definition header", NULL, 0, false, NULL, NULL },
    { 0x02B, 0, "MDEF", "Program definition header", NULL, 0, false, NULL, NULL },
    { 0x02C, 0, "FDEF", "Function definition header", NULL, 0, false, NULL, NULL },
    { 0x02D, 0, "PDEF", "Procedure definition header", NULL, 0, false, NULL, NULL },
    { 0x02E, 0, "UDEF", "Update block header", NULL, 0, false, NULL, NULL },
    { 0x02F, 0, "CDEF", "Compool definition header", NULL, 0, false, NULL, NULL },
    { 0x030, 0, "CLOS", "CLOSE statement, closes a program/procedure/function/task", NULL, 0, false, NULL, NULL },
    { 0x031, 0, "EDCL", "End-of-declarations marker", NULL, 0, false, NULL, NULL },
    { 0x032, 0, "RTRN", "Subprogram return", NULL, 0, false, NULL, NULL },
    { 0x033, 0, "TDCL", "TEMPORARY data-item declaration", NULL, 0, false, NULL, NULL },
    { 0x034, 0, "WAIT", "WAIT statement (interval/UNTIL/FOR DEPENDENT)", NULL, 0, false, NULL, NULL },
    { 0x035, 0, "SGNL", "SIGNAL statement", NULL, 0, false, NULL, NULL },
    { 0x036, 0, "CANC", "CANCEL statement, self or named process", NULL, 0, false, NULL, NULL },
    { 0x037, 0, "TERM", "Terminate program execution", NULL, 0, false, NULL, NULL },
    { 0x038, 0, "PRIO", "UPDATE PRIORITY statement", NULL, 0, false, NULL, NULL },
    { 0x039, 0, "SCHD", "SCHEDULE statement", NULL, 0, false, NULL, NULL },
    { 0x03C, 0, "ERON", "ON ERROR / OFF ERROR statement (all forms)", NULL, 0, false, NULL, NULL },
    { 0x03D, 0, "ERSE", "SEND ERROR statement (error simulation/signaling)", NULL, 0, false, NULL, NULL },
    { 0x040, 0, "MSHP", "MATRIX(...) shaping function", NULL, 0, false, NULL, NULL },
    { 0x041, 0, "VSHP", "VECTOR(...) shaping function", NULL, 0, false, NULL, NULL },
    { 0x042, 0, "SSHP", "List-form SCALAR(...) shaping function", NULL, 0, false, NULL, NULL },
    { 0x043, 0, "ISHP", "List-form INTEGER(...) shaping function", NULL, 0, false, NULL, NULL },
    { 0x045, 0, "SFST", "Start of shaping-function specification", NULL, 0, false, NULL, NULL },
    { 0x046, 0, "SFND", "End of shaping-function specification", NULL, 0, false, NULL, NULL },
    { 0x047, 0, "SFAR", "Shaping-function argument separator", NULL, 0, false, NULL, NULL },
    { 0x04A, 0, "BFNC", "Built-in function call (e.g. PRIO, SINCOS)", NULL, 0, false, NULL, NULL },
    { 0x04B, 0, "LFNC", "MAX/MIN built-in functions (\"L-FUNC\" category)", NULL, 0, false, NULL, NULL },
    { 0x04D, 0, "TNEQ", "Structure not-equal comparison", NULL, 0, false, NULL, NULL },
    { 0x04E, 0, "TEQU", "Structure equal comparison", NULL, 0, false, NULL, NULL },
    { 0x04F, 0, "TASN", "Structure assign", NULL, 0, false, NULL, NULL },
    { 0x051, 0, "IDEF", "Inline function definition header", NULL, 0, false, NULL, NULL },
    { 0x052, 0, "ICLS", "Inline function close", NULL, 0, false, NULL, NULL },
    { 0x055, 0, "NNEQ", "NAME (pointer) not-equal comparison", NULL, 0, false, NULL, NULL },
    { 0x056, 0, "NEQU", "NAME (pointer) equal comparison", NULL, 0, false, NULL, NULL },
    { 0x057, 0, "NASN", "NAME (pointer) assign", NULL, 0, false, NULL, NULL },
    { 0x059, 0, "PMHD", "%macro invocation header", NULL, 0, false, NULL, NULL },
    { 0x05A, 0, "PMAR", "%macro invocation argument", NULL, 0, false, NULL, NULL },
    { 0x05B, 0, "PMIN", "%macro invocation end", NULL, 0, false, NULL, NULL },
    { 0x101, 1, "BASN", "Bit-string assign", NULL, 0, false, NULL, NULL },
    { 0x102, 1, "BAND", "Bit-string AND", NULL, 0, false, NULL, NULL },
    { 0x103, 1, "BOR", "Bit-string OR", NULL, 0, false, NULL, NULL },
    { 0x104, 1, "BNOT", "Bit-string complement", NULL, 0, false, NULL, NULL },
    { 0x105, 1, "BCAT", "Bit-string catenate", NULL, 0, false, NULL, NULL },
    { 0x121, 1, "BTOB", "Bit-string length conversion", NULL, 0, false, NULL, NULL },
    { 0x122, 1, "BTOQ", "SUBBIT pseudo-conversion, bit-string argument", NULL, 0, false, NULL, NULL },
    { 0x141, 1, "CTOB", "Character to bit conversion", NULL, 0, false, NULL, NULL },
    { 0x142, 1, "CTOQ", "SUBBIT pseudo-conversion, character argument", NULL, 0, false, NULL, NULL },
    { 0x1A1, 1, "STOB", "Scalar to bit conversion", NULL, 0, false, NULL, NULL },
    { 0x1A2, 1, "STOQ", "SUBBIT pseudo-conversion, scalar argument", NULL, 0, false, NULL, NULL },
    { 0x1C1, 1, "ITOB", "Integer to bit conversion", NULL, 0, false, NULL, NULL },
    { 0x1C2, 1, "ITOQ", "SUBBIT pseudo-conversion, integer argument", NULL, 0, false, NULL, NULL },
    { 0x201, 2, "CASN", "Character assign", NULL, 0, false, NULL, NULL },
    { 0x202, 2, "CCAT", "Character catenate", NULL, 0, false, NULL, NULL },
    { 0x221, 2, "BTOC", "Bit to character conversion", NULL, 0, false, NULL, NULL },
    { 0x241, 2, "CTOC", "Character-length conversion", NULL, 0, false, NULL, NULL },
    { 0x2A1, 2, "STOC", "Scalar to character conversion", NULL, 0, false, NULL, NULL },
    { 0x2C1, 2, "ITOC", "Integer to character conversion", NULL, 0, false, NULL, NULL },
    { 0x301, 3, "MASN", "Matrix assign", NULL, 0, false, NULL, NULL },
    { 0x329, 3, "MTRA", "Matrix transpose", NULL, 0, false, NULL, NULL },
    { 0x341, 3, "MTOM", "Matrix precision scale", NULL, 0, false, NULL, NULL },
    { 0x344, 3, "MNEG", "Matrix negate", NULL, 0, false, NULL, NULL },
    { 0x362, 3, "MADD", "Matrix add", NULL, 0, false, NULL, NULL },
    { 0x363, 3, "MSUB", "Matrix subtract", NULL, 0, false, NULL, NULL },
    { 0x368, 3, "MMPR", "Matrix-matrix product", NULL, 0, false, NULL, NULL },
    { 0x387, 3, "VVPR", "Vector outer product, matrix result", NULL, 0, false, NULL, NULL },
    { 0x3A5, 3, "MSPR", "Matrix multiply by scalar", NULL, 0, false, NULL, NULL },
    { 0x3A6, 3, "MSDV", "Matrix divide by scalar", NULL, 0, false, NULL, NULL },
    { 0x3CA, 3, "MINV", "Matrix invert", NULL, 0, false, NULL, NULL },
    { 0x401, 4, "VASN", "Vector assign", NULL, 0, false, NULL, NULL },
    { 0x441, 4, "VTOV", "Vector precision scale", NULL, 0, false, NULL, NULL },
    { 0x444, 4, "VNEG", "Vector negate", NULL, 0, false, NULL, NULL },
    { 0x46C, 4, "MVPR", "Matrix-vector product", NULL, 0, false, NULL, NULL },
    { 0x46D, 4, "VMPR", "Vector-matrix product", NULL, 0, false, NULL, NULL },
    { 0x482, 4, "VADD", "Vector add", NULL, 0, false, NULL, NULL },
    { 0x483, 4, "VSUB", "Vector subtract", NULL, 0, false, NULL, NULL },
    { 0x48B, 4, "VCRS", "Vector cross product", NULL, 0, false, NULL, NULL },
    { 0x4A5, 4, "VSPR", "Vector multiply by scalar", NULL, 0, false, NULL, NULL },
    { 0x4A6, 4, "VSDV", "Vector divide by scalar", NULL, 0, false, NULL, NULL },
    { 0x501, 5, "SASN", "Scalar assign", NULL, 0, false, NULL, NULL },
    { 0x521, 5, "BTOS", "Bit string to scalar conversion", NULL, 0, false, NULL, NULL },
    { 0x541, 5, "CTOS", "Character to scalar conversion", NULL, 0, false, NULL, NULL },
    { 0x571, 5, "SIEX", "Scalar exponentiation by integer", NULL, 0, false, NULL, NULL },
    { 0x572, 5, "SPEX", "Scalar exponentiation by positive integer", NULL, 0, false, NULL, NULL },
    { 0x58E, 5, "VDOT", "Vector dot product, scalar result", NULL, 0, false, NULL, NULL },
    { 0x5A1, 5, "STOS", "Scalar precision scale", NULL, 0, false, NULL, NULL },
    { 0x5AB, 5, "SADD", "Scalar add", NULL, 0, false, NULL, NULL },
    { 0x5AC, 5, "SSUB", "Scalar subtract", NULL, 0, false, NULL, NULL },
    { 0x5AD, 5, "SSPR", "Scalar multiply", NULL, 0, false, NULL, NULL },
    { 0x5AE, 5, "SSDV", "Scalar divide", NULL, 0, false, NULL, NULL },
    { 0x5AF, 5, "SEXP", "Scalar exponentiation by scalar", NULL, 0, false, NULL, NULL },
    { 0x5B0, 5, "SNEG", "Scalar negate", NULL, 0, false, NULL, NULL },
    { 0x5C1, 5, "ITOS", "Integer to scalar conversion", NULL, 0, false, NULL, NULL },
    { 0x601, 6, "IASN", "Integer assign", NULL, 0, false, NULL, NULL },
    { 0x621, 6, "BTOI", "Bit to integer conversion", NULL, 0, false, NULL, NULL },
    { 0x641, 6, "CTOI", "Character to integer conversion", NULL, 0, false, NULL, NULL },
    { 0x6A1, 6, "STOI", "Scalar to integer conversion", NULL, 0, false, NULL, NULL },
    { 0x6C1, 6, "ITOI", "Integer precision scale", NULL, 0, false, NULL, NULL },
    { 0x6CB, 6, "IADD", "Integer add", NULL, 0, false, NULL, NULL },
    { 0x6CC, 6, "ISUB", "Integer subtract", NULL, 0, false, NULL, NULL },
    { 0x6CD, 6, "IIPR", "Integer multiply", NULL, 0, false, NULL, NULL },
    { 0x6D0, 6, "INEG", "Integer negate", NULL, 0, false, NULL, NULL },
    { 0x6D2, 6, "IPEX", "Integer exponentiation by positive integer", NULL, 0, false, NULL, NULL },
    { 0x720, 7, "BTRU", "Bit-is-true test (conditional context)", NULL, 0, false, NULL, NULL },
    { 0x725, 7, "BNEQ", "Bit string not equal", NULL, 0, false, NULL, NULL },
    { 0x726, 7, "BEQU", "Bit string equal", NULL, 0, false, NULL, NULL },
    { 0x745, 7, "CNEQ", "Character not equal", NULL, 0, false, NULL, NULL },
    { 0x746, 7, "CEQU", "Character equal", NULL, 0, false, NULL, NULL },
    { 0x747, 7, "CNGT", "Character not greater than", NULL, 0, false, NULL, NULL },
    { 0x748, 7, "CGT", "Character greater than", NULL, 0, false, NULL, NULL },
    { 0x749, 7, "CNLT", "Character not less than", NULL, 0, false, NULL, NULL },
    { 0x74A, 7, "CLT", "Character less than", NULL, 0, false, NULL, NULL },
    { 0x765, 7, "MNEQ", "Matrix not equal", NULL, 0, false, NULL, NULL },
    { 0x766, 7, "MEQU", "Matrix equal", NULL, 0, false, NULL, NULL },
    { 0x785, 7, "VNEQ", "Vector not equal", NULL, 0, false, NULL, NULL },
    { 0x786, 7, "VEQU", "Vector equal", NULL, 0, false, NULL, NULL },
    { 0x7A5, 7, "SNEQ", "Scalar not equal", NULL, 0, false, NULL, NULL },
    { 0x7A6, 7, "SEQU", "Scalar equal", NULL, 0, false, NULL, NULL },
    { 0x7A7, 7, "SNGT", "Scalar not greater than", NULL, 0, false, NULL, NULL },
    { 0x7A8, 7, "SGT", "Scalar greater than", NULL, 0, false, NULL, NULL },
    { 0x7A9, 7, "SNLT", "Scalar not less than", NULL, 0, false, NULL, NULL },
    { 0x7AA, 7, "SLT", "Scalar less than", NULL, 0, false, NULL, NULL },
    { 0x7C5, 7, "INEQ", "Integer not equal", NULL, 0, false, NULL, NULL },
    { 0x7C6, 7, "IEQU", "Integer equal", NULL, 0, false, NULL, NULL },
    { 0x7C7, 7, "INGT", "Integer not greater than", NULL, 0, false, NULL, NULL },
    { 0x7C8, 7, "IGT", "Integer greater than", NULL, 0, false, NULL, NULL },
    { 0x7C9, 7, "INLT", "Integer not less than", NULL, 0, false, NULL, NULL },
    { 0x7CA, 7, "ILT", "Integer less than", NULL, 0, false, NULL, NULL },
    { 0x7E2, 7, "CAND", "Logical AND", NULL, 0, false, NULL, NULL },
    { 0x7E3, 7, "COR", "Logical OR", NULL, 0, false, NULL, NULL },
    { 0x7E4, 7, "CNOT", "Logical NOT", NULL, 0, false, NULL, NULL },
    { 0x801, 8, "STRI", "Repeated-initialize specifier", NULL, 0, false, NULL, NULL },
    { 0x802, 8, "SLRI", "Start repeated-initialize loop", NULL, 0, false, NULL, NULL },
    { 0x803, 8, "ELRI", "End (one unit of a) repeated-initialize loop", NULL, 0, false, NULL, NULL },
    { 0x804, 8, "ETRI", "End repeated-initialize loop", NULL, 0, false, NULL, NULL },
    { 0x821, 8, "BINT", "Bit-string initialize", NULL, 0, false, NULL, NULL },
    { 0x841, 8, "CINT", "Character initialize", NULL, 0, false, NULL, NULL },
    { 0x861, 8, "MINT", "Matrix initialize", NULL, 0, false, NULL, NULL },
    { 0x881, 8, "VINT", "Vector initialize", NULL, 0, false, NULL, NULL },
    { 0x8A1, 8, "SINT", "Scalar initialize", NULL, 0, false, NULL, NULL },
    { 0x8C1, 8, "IINT", "Integer initialize", NULL, 0, false, NULL, NULL },
    { 0x8E1, 8, "NINT", "NAME (pointer) initialize", NULL, 0, false, NULL, NULL },
    { 0x8E2, 8, "TINT", "Structure-terminal initialize", NULL, 0, false, NULL, NULL },
    { 0x8E3, 8, "EINT", "EQUATE EXTERNAL statement", NULL, 0, false, NULL, NULL },
};

const size_t g_opcode_table_count = 179;
