C     COPYRIGHT:        NONE, PUBLIC DOMAIN
C     FILENAME:         ASM.F
C     PURPOSE:          PROVIDES REPLACEMENT FOR THE IBM 7090/7094
C                       ASSEMBLY-LANGUAGE FUNCTIONS OF THE GEMINI
C                       CATCH-UP AND RENDEZVOUS SIMULATION PROGRAM,
C                       FOR COMPILING WITH FORTRAN 66/77/90/95/ETC.
C     HISTORY:          2010-08-17 RSB  CREATED.
C
C     I PRESENTLY HAVE NO IDEA AT ALL WHAT THIS IS SUPPOSED TO DO.
C     PERHAPS IT IS SOME KIND OF INTERRUPT-DISABLE.  ANYHOW, IGNORE
C     IT FOR NOW AND HOPE IT GOES AWAY.
      SUBROUTINE DSB
      RETURN
      END
C
C     I DO NOT KNOW WHAT THIS IS FOR.  IT IS PAIRED WITH DSB.
C     IGNORE IT FOR NOW.
      SUBROUTINE ENB (I)
      RETURN
      END
C
C     THIS SETS TAPE A7 TO HIGH DENSITY.  I THINK WE CAN SAFELY IGNORE IT
C     IN THE ABSENCE OF TAPES FOR THE SIMULATED SYSTEM.
      SUBROUTINE HDA7
      RETURN
      END
C
C     THIS SETS TAPE A9 TO HIGH DENSITY.  I THINK WE CAN SAFELY IGNORE IT
C     IN THE ABSENCE OF TAPES FOR THE SIMULATED SYSTEM.
      SUBROUTINE HDA9
      RETURN
      END
C
C     THIS SETS TAPE B6 TO LOW DENSITY.  I THINK WE CAN SAFELY IGNORE IT
C     IN THE ABSENCE OF TAPES FOR THE SIMULATED SYSTEM.
      SUBROUTINE LDB6
      RETURN
      END
C
      SUBROUTINE KEYCN (K)
      RETURN
      END
C
      SUBROUTINE KEYS (K,N)
      RETURN
      END
C
      SUBROUTINE CTRL1
      RETURN
      END
C
C     MAR, DEV, AND PRT SEEM TO COMPRISE A MODIFIED EULER INTEGRATION
C     ALGORITHM FOR COMPUTING THE ATTITUDE.  THEREFORE, THEY CANNOT
C     BE IGNORED AND MUST BE IMPLMENTED.  THE ORIGINAL SOURCE FOR ALL
C     IS THE FILE MEDP3.S.
      SUBROUTINE MAR (I,X,Y,J,K,N)
      RETURN
      END
C
      SUBROUTINE PRT
      RETURN
      END
C
      SUBROUTINE DEV
      RETURN
      END
C
C     I BELIEVE THIS SKIPS PAST FILES ON THE TAPE.  I THINK WE CAN 
C     SAFELY IGNORE IT IN THE ABSENCE OF TAPES FOR THE SIMULATED 
C     SYSTEM.
      SUBROUTINE SKPN (X,I,J)
      RETURN
      END
C
C     GENERATES A SELF-LOADING TAPE ON DRIVE A7.  NOT SURE WHAT THAT
C     MEANS, BUT SEEMS SAFE TO IGNORE.
      SUBROUTINE SELFLD
      RETURN
      END
