/*
  File TRACE_MSG.c generated by XCOM-I, 2024-08-08 04:32:08.
*/

#include "runtimeC.h"

descriptor_t *
TRACE_MSG (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (descriptor_t *)0;
    }
  reentryGuard = guardReentry (reentryGuard, "TRACE_MSG");
  // HALMAT_BLOCK = CURR_HALMAT_BLOCK - 1; (817)
  {
    int32_t numberRHS
        = (int32_t)(xsubtract (COREHALFWORD (mCURR_HALMAT_BLOCK), 1));
    descriptor_t *bitRHS;
    bitRHS = fixedToBit (32, (int32_t)(numberRHS));
    putBIT (16, mTRACE_MSGxHALMAT_BLOCK, bitRHS);
    bitRHS->inUse = 0;
  }
  // IF (HALMAT_PTR >= 1800) & (HALMAT# < 1800) THEN (818)
  if (1
      & (xAND (xGE (COREHALFWORD (mHALMAT_PTR), 1800),
               xLT (COREHALFWORD (mTRACE_MSGxHALMATp), 1800))))
    // HALMAT_BLOCK = HALMAT_BLOCK - 1; (819)
    {
      int32_t numberRHS
          = (int32_t)(xsubtract (COREHALFWORD (mTRACE_MSGxHALMAT_BLOCK), 1));
      descriptor_t *bitRHS;
      bitRHS = fixedToBit (32, (int32_t)(numberRHS));
      putBIT (16, mTRACE_MSGxHALMAT_BLOCK, bitRHS);
      bitRHS->inUse = 0;
    }
  // RETURN MSG || BLANK || LEFT_PAREN || HALMAT_BLOCK || COMMA || HALMAT# ||
  // RIGHT_PAREN; (820)
  {
    reentryGuard = 0;
    return xsCAT (
        xsCAT (xsCAT (xsCAT (xsCAT (xsCAT (getCHARACTER (mTRACE_MSGxMSG),
                                           getCHARACTER (mBLANK)),
                                    getCHARACTER (mLEFT_PAREN)),
                             bitToCharacter (
                                 getBIT (16, mTRACE_MSGxHALMAT_BLOCK))),
                      getCHARACTER (mCOMMA)),
               bitToCharacter (getBIT (16, mTRACE_MSGxHALMATp))),
        getCHARACTER (mRIGHT_PAREN));
  }
}
