/*
  File CHARTIME.c generated by XCOM-I, 2024-08-08 04:33:20.
*/

#include "runtimeC.h"

descriptor_t *
CHARTIME (int reset)
{
  static int reentryGuard = 0;
  if (reset)
    {
      reentryGuard = 0;
      return (descriptor_t *)0;
    }
  reentryGuard = guardReentry (reentryGuard, "CHARTIME");
  // C=T/360000||COLON||T MOD 360000/6000||COLON|| T MOD 6000/100||'.'; (668)
  {
    descriptor_t *stringRHS;
    stringRHS = xsCAT (
        xsCAT (
            xsCAT (xsCAT (xsCAT (fixedToCharacter (
                                     xdivide (getFIXED (mCHARTIMExT), 360000)),
                                 getCHARACTER (mCOLON)),
                          fixedToCharacter (xdivide (
                              xmod (getFIXED (mCHARTIMExT), 360000), 6000))),
                   getCHARACTER (mCOLON)),
            fixedToCharacter (
                xdivide (xmod (getFIXED (mCHARTIMExT), 6000), 100))),
        cToDescriptor (NULL, "."));
    putCHARACTER (mCHARTIMExC, stringRHS);
    stringRHS->inUse = 0;
  }
  // T=T MOD 100; (669)
  {
    int32_t numberRHS = (int32_t)(xmod (getFIXED (mCHARTIMExT), 100));
    putFIXED (mCHARTIMExT, numberRHS);
  }
  // IF T < 10 THEN (670)
  if (1 & (xLT (getFIXED (mCHARTIMExT), 10)))
    // C=C||'0'; (671)
    {
      descriptor_t *stringRHS;
      stringRHS
          = xsCAT (getCHARACTER (mCHARTIMExC), cToDescriptor (NULL, "0"));
      putCHARACTER (mCHARTIMExC, stringRHS);
      stringRHS->inUse = 0;
    }
  // RETURN C||T; (672)
  {
    reentryGuard = 0;
    return xsCAT (getCHARACTER (mCHARTIMExC),
                  fixedToCharacter (getFIXED (mCHARTIMExT)));
  }
}
